// Plan comptable SYSCOHADA révisé 2017 : INTÉGRAL
// Source : Acte uniforme relatif au droit comptable et à l'information financière, 26 janvier 2017

export interface CompteOHADA {
  numero: string
  intitule: string
  classe: number
  type: 'actif' | 'passif' | 'charge' | 'produit' | 'autre'
}

function t(n: string, i: string, c: number, ty: CompteOHADA['type']): CompteOHADA {
  return { numero: n, intitule: i, classe: c, type: ty }
}

export const PLAN_COMPTABLE_OHADA: CompteOHADA[] = [
  // ─── CLASSE 1 ───────────────────────────────────────────────
  t("10","Capital",1,"passif"),
  t("101","Capital social",1,"passif"),
  t("1011","Capital souscrit, non appelé",1,"passif"),
  t("1012","Capital souscrit, appelé, non versé",1,"passif"),
  t("1013","Capital souscrit, appelé, versé, non amorti",1,"passif"),
  t("1014","Capital souscrit, appelé, versé, amorti",1,"passif"),
  t("1018","Capital souscrit soumis à des conditions particulières",1,"passif"),
  t("102","Capital par dotation",1,"passif"),
  t("1021","Dotation initiale",1,"passif"),
  t("1022","Dotations complémentaires",1,"passif"),
  t("1028","Autres dotations",1,"passif"),
  t("103","Capital personnel",1,"passif"),
  t("104","Compte de l'exploitant",1,"passif"),
  t("1041","Apports temporaires",1,"passif"),
  t("1042","Opérations courantes",1,"passif"),
  t("1043","Rémunérations, impôts et autres charges personnelles",1,"passif"),
  t("1047","Prélèvements d'autoconsommation",1,"passif"),
  t("1048","Autres prélèvements",1,"passif"),
  t("105","Primes liées au capital social",1,"passif"),
  t("1051","Primes d'émission",1,"passif"),
  t("1052","Primes d'apport",1,"passif"),
  t("1053","Primes de fusion",1,"passif"),
  t("1054","Primes de conversion",1,"passif"),
  t("1058","Autres primes",1,"passif"),
  t("106","Écarts de réévaluation",1,"passif"),
  t("1061","Écarts de réévaluation légale",1,"passif"),
  t("1062","Écarts de réévaluation libre",1,"passif"),
  t("109","Apporteurs, capital souscrit, non appelé",1,"passif"),
  t("11","Réserves",1,"passif"),
  t("111","Réserve légale",1,"passif"),
  t("112","Réserves statutaires ou contractuelles",1,"passif"),
  t("113","Réserves réglementées",1,"passif"),
  t("1131","Réserves de plus-values nettes à long terme",1,"passif"),
  t("1132","Réserves d'attribution gratuite d'actions au personnel salarié et aux dirigeants",1,"passif"),
  t("1133","Réserves consécutives à l'octroi de subventions d'investissement",1,"passif"),
  t("1134","Réserves des valeurs mobilières donnant accès au capital",1,"passif"),
  t("1138","Autres réserves réglementées",1,"passif"),
  t("118","Autres réserves",1,"passif"),
  t("1181","Réserves facultatives",1,"passif"),
  t("1188","Réserves diverses",1,"passif"),
  t("12","Report à nouveau",1,"passif"),
  t("121","Report à nouveau créditeur",1,"passif"),
  t("129","Report à nouveau débiteur",1,"passif"),
  t("1291","Perte nette à reporter",1,"passif"),
  t("1292","Perte - Amortissements réputés différés",1,"passif"),
  t("13","Résultat net de l'exercice",1,"passif"),
  t("130","Résultat en instance d'affectation",1,"passif"),
  t("1301","Résultat en instance d'affectation : bénéfice",1,"passif"),
  t("1309","Résultat en instance d'affectation : perte",1,"passif"),
  t("131","Résultat net : bénéfice",1,"passif"),
  t("132","Marge commerciale (MC)",1,"passif"),
  t("133","Valeur ajoutée (VA)",1,"passif"),
  t("134","Excédent brut d'exploitation (EBE)",1,"passif"),
  t("135","Résultat d'exploitation (RE)",1,"passif"),
  t("136","Résultat financier (RF)",1,"passif"),
  t("137","Résultat des activités ordinaires (RAO)",1,"passif"),
  t("138","Résultat hors activités ordinaires (RHAO)",1,"passif"),
  t("1381","Résultat de fusion",1,"passif"),
  t("1382","Résultat d'apport partiel d'actif",1,"passif"),
  t("1383","Résultat de scission",1,"passif"),
  t("1384","Résultat de liquidation",1,"passif"),
  t("139","Résultat net : perte",1,"passif"),
  t("14","Subventions d'investissement",1,"passif"),
  t("141","Subventions d'équipement",1,"passif"),
  t("1411","État",1,"passif"),
  t("1412","Régions",1,"passif"),
  t("1413","Départements",1,"passif"),
  t("1414","Communes et collectivités publiques décentralisées",1,"passif"),
  t("1415","Entités publiques ou mixtes",1,"passif"),
  t("1416","Entités et organismes privés",1,"passif"),
  t("1417","Organismes internationaux",1,"passif"),
  t("1418","Autres",1,"passif"),
  t("148","Autres subventions d'investissement",1,"passif"),
  t("15","Provisions réglementées et fonds assimilés",1,"passif"),
  t("151","Amortissements dérogatoires",1,"passif"),
  t("152","Plus-values de cession à réinvestir",1,"passif"),
  t("153","Fonds réglementés",1,"passif"),
  t("1531","Fonds National",1,"passif"),
  t("1532","Prélèvement pour le Budget",1,"passif"),
  t("154","Provisions spéciales de réévaluation",1,"passif"),
  t("155","Provisions réglementées relatives aux immobilisations",1,"passif"),
  t("1551","Reconstitution des gisements miniers et pétroliers",1,"passif"),
  t("156","Provisions réglementées relatives aux stocks",1,"passif"),
  t("1561","Hausse de prix",1,"passif"),
  t("1562","Fluctuation des cours",1,"passif"),
  t("157","Provisions pour investissement",1,"passif"),
  t("158","Autres provisions et fonds réglementés",1,"passif"),
  t("16","Emprunts et dettes assimilées",1,"passif"),
  t("161","Emprunts obligataires",1,"passif"),
  t("1611","Emprunts obligataires ordinaires",1,"passif"),
  t("1612","Emprunts obligataires convertibles en actions",1,"passif"),
  t("1613","Emprunts obligataires remboursables en actions",1,"passif"),
  t("1618","Autres emprunts obligataires",1,"passif"),
  t("162","Emprunts et dettes auprès des établissements de crédit",1,"passif"),
  t("163","Avances reçues de l'État",1,"passif"),
  t("164","Avances reçues et comptes courants bloqués",1,"passif"),
  t("165","Dépôts et cautionnements reçus",1,"passif"),
  t("1651","Dépôts",1,"passif"),
  t("1652","Cautionnements",1,"passif"),
  t("166","Intérêts courus",1,"passif"),
  t("1661","Sur emprunts obligataires",1,"passif"),
  t("1662","Sur emprunts et dettes auprès des établissements de crédit",1,"passif"),
  t("1663","Sur avances reçues de l'État",1,"passif"),
  t("1664","Sur avances reçues et comptes courants bloqués",1,"passif"),
  t("1665","Sur dépôts et cautionnements reçus",1,"passif"),
  t("1667","Sur avances assorties de conditions particulières",1,"passif"),
  t("1668","Sur autres emprunts et dettes",1,"passif"),
  t("167","Avances assorties de conditions particulières",1,"passif"),
  t("1671","Avances bloquées pour augmentation du capital",1,"passif"),
  t("1672","Avances conditionnées par l'État",1,"passif"),
  t("1673","Avances conditionnées par les autres organismes africains",1,"passif"),
  t("1674","Avances conditionnées par les organismes internationaux",1,"passif"),
  t("168","Autres emprunts et dettes",1,"passif"),
  t("1681","Rentes viagères capitalisées",1,"passif"),
  t("1682","Billets de fonds",1,"passif"),
  t("1683","Dettes consécutives à des titres empruntés",1,"passif"),
  t("1684","Emprunts participatifs",1,"passif"),
  t("1685","Participation des travailleurs aux bénéfices",1,"passif"),
  t("1686","Emprunts et dettes contractés auprès des autres tiers",1,"passif"),
  t("17","Dettes de location acquisition",1,"passif"),
  t("172","Dettes de location acquisition / crédit-bail immobilier",1,"passif"),
  t("173","Dettes de location acquisition / crédit-bail mobilier",1,"passif"),
  t("174","Dettes de location acquisition / location de vente",1,"passif"),
  t("176","Intérêts courus",1,"passif"),
  t("1762","Sur dettes de location acquisition / crédit-bail immobilier",1,"passif"),
  t("1763","Sur dettes de location acquisition / crédit-bail mobilier",1,"passif"),
  t("1764","Sur dettes de location acquisition / location-vente",1,"passif"),
  t("1768","Sur autres dettes de location acquisition",1,"passif"),
  t("178","Autres dettes de location acquisition",1,"passif"),
  t("18","Dettes liées à des participations",1,"passif"),
  t("181","Dettes liées à des participations",1,"passif"),
  t("1811","Dettes liées à des participations (groupe)",1,"passif"),
  t("1812","Dettes liées à des participations (hors groupe)",1,"passif"),
  t("182","Dettes liées à des sociétés en participation",1,"passif"),
  t("183","Intérêts courus sur dettes liées à des participations",1,"passif"),
  t("184","Comptes permanents bloqués des établissements et succursales",1,"passif"),
  t("185","Comptes permanents non bloqués des établissements et succursales",1,"passif"),
  t("186","Comptes de liaison charges",1,"passif"),
  t("187","Comptes de liaison produits",1,"passif"),
  t("188","Comptes de liaison des sociétés en participation",1,"passif"),
  t("19","Provisions pour risques et charges",1,"passif"),
  t("191","Provisions pour litiges",1,"passif"),
  t("192","Provisions pour garanties données aux clients",1,"passif"),
  t("193","Provisions pour pertes sur marchés à achèvement futur",1,"passif"),
  t("194","Provisions pour pertes de change",1,"passif"),
  t("195","Provisions pour impôts",1,"passif"),
  t("196","Provisions pour pensions et obligations similaires",1,"passif"),
  t("1961","Provisions pour pensions - engagement de retraite",1,"passif"),
  t("1962","Actif du régime de retraite",1,"passif"),
  t("197","Provisions pour restructuration",1,"passif"),
  t("198","Autres provisions pour risques et charges",1,"passif"),
  t("1981","Provisions pour amendes et pénalités",1,"passif"),
  t("1983","Provisions pour propre assureur",1,"passif"),
  t("1984","Provisions pour démantèlement et remise en état",1,"passif"),
  t("1985","Provisions pour droits à réduction ou avantage en nature",1,"passif"),
  t("1988","Provisions pour divers risques et charges",1,"passif"),
  // ─── CLASSE 2 ───────────────────────────────────────────────
  t("21","Immobilisations incorporelles",2,"actif"),
  t("211","Frais de développement",2,"actif"),
  t("212","Brevets, licences, concessions et droits similaires",2,"actif"),
  t("2121","Brevets",2,"actif"),
  t("2122","Licences",2,"actif"),
  t("2123","Concessions de service public",2,"actif"),
  t("2128","Autres concessions et droits similaires",2,"actif"),
  t("213","Logiciels et sites internet",2,"actif"),
  t("2131","Logiciels",2,"actif"),
  t("2132","Sites internet",2,"actif"),
  t("214","Marques",2,"actif"),
  t("215","Fonds commercial",2,"actif"),
  t("216","Droit au bail",2,"actif"),
  t("217","Investissements de création",2,"actif"),
  t("218","Autres droits et valeurs incorporels",2,"actif"),
  t("2181","Frais de prospection et d'évaluation de ressources minérales",2,"actif"),
  t("2182","Coûts d'obtention du contrat",2,"actif"),
  t("2183","Fichiers clients, notices, titres de journaux et magazines",2,"actif"),
  t("2184","Coûts des franchises",2,"actif"),
  t("2188","Divers droits et valeurs incorporelles",2,"actif"),
  t("219","Immobilisations incorporelles en cours",2,"actif"),
  t("2191","Frais de développement en cours",2,"actif"),
  t("2193","Logiciels et internet en cours",2,"actif"),
  t("2198","Autres droits et valeurs incorporels en cours",2,"actif"),
  t("22","Terrains",2,"actif"),
  t("221","Terrains agricoles et forestiers",2,"actif"),
  t("2211","Terrains d'exploitation agricole",2,"actif"),
  t("2212","Terrains d'exploitation forestière",2,"actif"),
  t("2218","Autres terrains",2,"actif"),
  t("222","Terrains nus",2,"actif"),
  t("2221","Terrains à bâtir",2,"actif"),
  t("2228","Autres terrains nus",2,"actif"),
  t("223","Terrains bâtis",2,"actif"),
  t("2231","Pour bâtiments industriels et agricoles",2,"actif"),
  t("2232","Pour bâtiments administratifs et commerciaux",2,"actif"),
  t("2234","Pour bâtiments affectés aux autres opérations professionnelles",2,"actif"),
  t("2235","Pour bâtiments affectés aux autres opérations non professionnelles",2,"actif"),
  t("2238","Autres terrains bâtis",2,"actif"),
  t("224","Travaux de mise en valeur des terrains",2,"actif"),
  t("2241","Plantation d'arbres et d'arbustes",2,"actif"),
  t("2245","Améliorations du fonds",2,"actif"),
  t("2248","Autres travaux",2,"actif"),
  t("225","Terrains de carrières - tréfonds",2,"actif"),
  t("2251","Carrières",2,"actif"),
  t("226","Terrains aménagés",2,"actif"),
  t("2261","Parkings",2,"actif"),
  t("227","Terrains mis en concession",2,"actif"),
  t("228","Autres terrains",2,"actif"),
  t("2281","Terrains - immeubles de placement",2,"actif"),
  t("2285","Terrains des logements affectés au personnel",2,"actif"),
  t("2286","Terrains de location - acquisition",2,"actif"),
  t("2288","Divers terrains",2,"actif"),
  t("229","Aménagements de terrains en cours",2,"actif"),
  t("2291","Terrains agricoles et forestiers en cours",2,"actif"),
  t("2292","Terrains nus en cours",2,"actif"),
  t("2295","Terrains de carrières - tréfonds en cours",2,"actif"),
  t("2298","Autres terrains en cours",2,"actif"),
  t("23","Bâtiments, installations techniques et agencements",2,"actif"),
  t("231","Bâtiments industriels, agricoles, administratifs et commerciaux sur sol propre",2,"actif"),
  t("2311","Bâtiments industriels",2,"actif"),
  t("2312","Bâtiments agricoles",2,"actif"),
  t("2313","Bâtiments administratifs et commerciaux",2,"actif"),
  t("2314","Bâtiments affectés au logement du personnel",2,"actif"),
  t("2315","Bâtiments - immeubles de placement",2,"actif"),
  t("2316","Bâtiments de location - acquisition",2,"actif"),
  t("232","Bâtiments industriels, agricoles, administratifs et commerciaux sur sol d'autrui",2,"actif"),
  t("2321","Bâtiments industriels sur sol d'autrui",2,"actif"),
  t("2322","Bâtiments agricoles sur sol d'autrui",2,"actif"),
  t("2323","Bâtiments administratifs et commerciaux sur sol d'autrui",2,"actif"),
  t("2324","Bâtiments affectés au logement du personnel sur sol d'autrui",2,"actif"),
  t("2325","Bâtiments - immeubles de placement sur sol d'autrui",2,"actif"),
  t("2326","Bâtiments de location - acquisition sur sol d'autrui",2,"actif"),
  t("233","Ouvrages d'infrastructure",2,"actif"),
  t("2331","Voies de terre",2,"actif"),
  t("2332","Voies de fer",2,"actif"),
  t("2333","Voies d'eau",2,"actif"),
  t("2334","Barrages, Digues",2,"actif"),
  t("2335","Pistes d'aérodrome",2,"actif"),
  t("2338","Autres ouvrages d'infrastructures",2,"actif"),
  t("234","Aménagements, agencements et installations techniques",2,"actif"),
  t("2341","Installations complexes spécialisées sur sol propre",2,"actif"),
  t("2342","Installations complexes spécialisées sur sol d'autrui",2,"actif"),
  t("2343","Installations à caractère spécifique sur sol propre",2,"actif"),
  t("2344","Installations à caractère spécifique sur sol d'autrui",2,"actif"),
  t("2345","Aménagements et agencements des bâtiments",2,"actif"),
  t("235","Aménagements de bureaux",2,"actif"),
  t("2351","Installations générales",2,"actif"),
  t("2358","Autres aménagements de bureaux",2,"actif"),
  t("237","Bâtiments industriels, agricoles et commerciaux mis en concession",2,"actif"),
  t("238","Autres installations et agencements",2,"actif"),
  t("239","Bâtiments, aménagements et installations en cours",2,"actif"),
  t("2391","Bâtiments en cours",2,"actif"),
  t("2392","Installations en cours",2,"actif"),
  t("2393","Ouvrages d'infrastructure en cours",2,"actif"),
  t("2394","Aménagements et agencements et installations techniques en cours",2,"actif"),
  t("2395","Aménagements de bureaux en cours",2,"actif"),
  t("2398","Autres installations et agencements en cours",2,"actif"),
  t("24","Matériel, mobilier et actifs biologiques",2,"actif"),
  t("241","Matériel et outillage industriel et commercial",2,"actif"),
  t("2411","Matériel industriel",2,"actif"),
  t("2412","Outillage industriel",2,"actif"),
  t("2413","Matériel commercial",2,"actif"),
  t("2414","Outillage commercial",2,"actif"),
  t("2416","Matériel & outillage industriel et commercial de location-acquisition",2,"actif"),
  t("242","Matériel et outillage agricole",2,"actif"),
  t("2421","Matériel agricole",2,"actif"),
  t("2422","Outillage agricole",2,"actif"),
  t("2426","Matériel & outillage agricole de location-acquisition",2,"actif"),
  t("243","Matériel d'emballage récupérable et identifiable",2,"actif"),
  t("244","Matériel et mobilier",2,"actif"),
  t("2441","Matériel de bureau",2,"actif"),
  t("2442","Matériel informatique",2,"actif"),
  t("2443","Matériel bureautique",2,"actif"),
  t("2444","Mobilier de bureau",2,"actif"),
  t("2445","Matériel et mobilier - immeubles de placement",2,"actif"),
  t("2446","Matériel et mobilier de location - acquisition",2,"actif"),
  t("2447","Matériel et mobilier des logements du personnel",2,"actif"),
  t("245","Matériel de transport",2,"actif"),
  t("2451","Matériel automobile",2,"actif"),
  t("2452","Matériel ferroviaire",2,"actif"),
  t("2453","Matériel fluvial, lagunaire",2,"actif"),
  t("2454","Matériel naval",2,"actif"),
  t("2455","Matériel aérien",2,"actif"),
  t("2456","Matériel de transport de location-acquisition",2,"actif"),
  t("2457","Matériel hippomobile",2,"actif"),
  t("2458","Autres matériels de transport",2,"actif"),
  t("246","Actifs biologiques",2,"actif"),
  t("2461","Cheptel, animaux de trait",2,"actif"),
  t("2462","Cheptel, animaux reproducteurs",2,"actif"),
  t("2463","Animaux de garde",2,"actif"),
  t("2465","Plantations agricoles",2,"actif"),
  t("2468","Autres actifs biologiques",2,"actif"),
  t("247","Agencements, aménagements du matériel et actifs biologiques",2,"actif"),
  t("2471","Agencements et aménagements du matériel",2,"actif"),
  t("2472","Agencements et aménagements des actifs biologiques",2,"actif"),
  t("2478","Autres agencements, aménagements du matériel et actifs biologiques",2,"actif"),
  t("248","Autres matériels et mobiliers",2,"actif"),
  t("2481","Collections et œuvres d'art",2,"actif"),
  t("2488","Divers matériels mobiliers",2,"actif"),
  t("249","Matériels et actifs biologiques en cours",2,"actif"),
  t("2491","Matériel et outillage industriel et commercial en cours",2,"actif"),
  t("2492","Matériel et outillage agricole en cours",2,"actif"),
  t("2493","Matériel d'emballage récupérable et identifiable en cours",2,"actif"),
  t("2494","Matériel et mobilier de bureau en cours",2,"actif"),
  t("2495","Matériel de transport en cours",2,"actif"),
  t("2496","Actifs biologiques en cours",2,"actif"),
  t("2497","Agencements aménagements du matériel et actifs biologiques en cours",2,"actif"),
  t("2498","Autres matériels et actifs biologiques en cours",2,"actif"),
  t("25","Avances et acomptes versés sur immobilisations",2,"actif"),
  t("251","Avances et acomptes versés sur immobilisations incorporelles",2,"actif"),
  t("252","Avances et acomptes versés sur immobilisations corporelles",2,"actif"),
  t("26","Titres de participation",2,"actif"),
  t("261","Titres de participation dans des sociétés sous contrôle exclusif",2,"actif"),
  t("262","Titres de participation dans des sociétés sous contrôle conjoint",2,"actif"),
  t("263","Titres de participation dans des sociétés conférant une influence notable",2,"actif"),
  t("265","Participations dans des organismes professionnels",2,"actif"),
  t("266","Parts dans des groupements d'intérêt économique (GIE)",2,"actif"),
  t("268","Autres titres de participation",2,"actif"),
  t("27","Autres immobilisations financières",2,"actif"),
  t("271","Prêts et créances",2,"actif"),
  t("2711","Prêts participatifs",2,"actif"),
  t("2712","Prêts aux associés",2,"actif"),
  t("2713","Billets de fonds",2,"actif"),
  t("2714","Titres prêtés",2,"actif"),
  t("2718","Autres prêts et créances",2,"actif"),
  t("272","Prêts au personnel",2,"actif"),
  t("2721","Prêts immobiliers",2,"actif"),
  t("2722","Prêts mobiliers et d'installation",2,"actif"),
  t("2728","Autres prêts au personnel",2,"actif"),
  t("273","Créances sur l'État",2,"actif"),
  t("2731","Retenues de garantie",2,"actif"),
  t("2733","Fonds réglementé",2,"actif"),
  t("2734","Créances sur le concédant",2,"actif"),
  t("2738","Autres créances sur l'État",2,"actif"),
  t("274","Titres immobilisés",2,"actif"),
  t("2741","Titres immobilisés de l'activité de portefeuille (TIAP)",2,"actif"),
  t("2742","Titres participatifs",2,"actif"),
  t("2743","Certificats d'investissement",2,"actif"),
  t("2744","Parts de fonds commun de placement (FCP)",2,"actif"),
  t("2745","Obligations",2,"actif"),
  t("2746","Actions ou parts propres",2,"actif"),
  t("2748","Autres titres immobilisés",2,"actif"),
  t("275","Dépôts et cautionnements versés",2,"actif"),
  t("2751","Dépôts pour loyers d'avance",2,"actif"),
  t("2752","Dépôts pour l'électricité",2,"actif"),
  t("2753","Dépôts pour l'eau",2,"actif"),
  t("2754","Dépôts pour le gaz",2,"actif"),
  t("2755","Dépôts pour le téléphone, le télex, la télécopie",2,"actif"),
  t("2756","Cautionnements sur marchés publics",2,"actif"),
  t("2757","Cautionnements sur autres opérations",2,"actif"),
  t("2758","Autres dépôts et cautionnements",2,"actif"),
  t("276","Intérêts courus",2,"actif"),
  t("2761","Prêts et créances non commerciales",2,"actif"),
  t("2762","Prêts au personnel",2,"actif"),
  t("2763","Créances sur l'État",2,"actif"),
  t("2764","Titres immobilisés",2,"actif"),
  t("2765","Dépôts et cautionnements versés",2,"actif"),
  t("2767","Créances rattachées à des participations",2,"actif"),
  t("2768","Immobilisations financières diverses",2,"actif"),
  t("277","Créances rattachées à des participations et avances à des GIE",2,"actif"),
  t("2771","Créances rattachées à des participations (groupe)",2,"actif"),
  t("2772","Créances rattachées à des participations (hors groupe)",2,"actif"),
  t("2773","Créances rattachées à des sociétés en participation",2,"actif"),
  t("2774","Avances à des Groupements d'intérêt économique (GIE)",2,"actif"),
  t("278","Immobilisations financières diverses",2,"actif"),
  t("2781","Créances diverses groupe",2,"actif"),
  t("2782","Créances diverses hors groupe",2,"actif"),
  t("2784","Banques dépôts à terme",2,"actif"),
  t("2785","Or et métaux précieux",2,"actif"),
  t("2788","Autres immobilisations financières",2,"actif"),
  t("28","Amortissements",2,"actif"),
  t("281","Amortissements des immobilisations incorporelles",2,"actif"),
  t("2811","Amortissements des frais de développement",2,"actif"),
  t("2812","Amortissements des brevets, licences, concessions et droits similaires",2,"actif"),
  t("2813","Amortissements des logiciels et sites internet",2,"actif"),
  t("2814","Amortissements des marques",2,"actif"),
  t("2815","Amortissements du fonds commercial",2,"actif"),
  t("2816","Amortissements du droit au bail",2,"actif"),
  t("2817","Amortissements des investissements de création",2,"actif"),
  t("2818","Amortissements des autres droits et valeurs incorporels",2,"actif"),
  t("282","Amortissements des terrains",2,"actif"),
  t("2824","Amortissements des travaux de mise en valeur des terrains",2,"actif"),
  t("283","Amortissements des bâtiments, installations techniques et agencements",2,"actif"),
  t("2831","Amortissements des bâtiments industriels, agricoles, administratifs et commerciaux sur sol propre",2,"actif"),
  t("2832","Amortissements des bâtiments industriels, agricoles, administratifs et commerciaux sur sol d'autrui",2,"actif"),
  t("2833","Amortissements des ouvrages d'infrastructure",2,"actif"),
  t("2834","Amortissements des aménagements, agencements et installations techniques",2,"actif"),
  t("2835","Amortissements des aménagements de bureaux",2,"actif"),
  t("2837","Amortissements des bâtiments industriels, agricoles et commerciaux mis en concession",2,"actif"),
  t("2838","Amortissements des autres installations et agencements",2,"actif"),
  t("284","Amortissements du matériel",2,"actif"),
  t("2841","Amortissements du matériel et outillage industriel et commercial",2,"actif"),
  t("2842","Amortissements du matériel et outillage agricole",2,"actif"),
  t("2843","Amortissements du matériel d'emballage récupérable et identifiable",2,"actif"),
  t("2844","Amortissements du matériel et mobilier",2,"actif"),
  t("2845","Amortissements du matériel de transport",2,"actif"),
  t("2846","Amortissements des actifs biologiques",2,"actif"),
  t("2847","Amortissements des agencements et aménagements du matériel et des actifs biologiques",2,"actif"),
  t("2848","Amortissements des autres matériels",2,"actif"),
  t("29","Dépréciations des immobilisations",2,"actif"),
  t("291","Dépréciations des immobilisations incorporelles",2,"actif"),
  t("2911","Dépréciations des frais de développement",2,"actif"),
  t("2912","Dépréciations des brevets, licences, concessions et droits similaires",2,"actif"),
  t("2913","Dépréciations des logiciels et sites internet",2,"actif"),
  t("2914","Dépréciations des marques",2,"actif"),
  t("2915","Dépréciations du fonds commercial",2,"actif"),
  t("2916","Dépréciations du droit au bail",2,"actif"),
  t("2917","Dépréciations des investissements de création",2,"actif"),
  t("2918","Dépréciations des autres droits et valeurs incorporels",2,"actif"),
  t("2919","Dépréciations des immobilisations incorporelles en cours",2,"actif"),
  t("292","Dépréciations des terrains",2,"actif"),
  t("2921","Dépréciations des terrains agricoles et forestiers",2,"actif"),
  t("2922","Dépréciations des terrains nus",2,"actif"),
  t("2923","Dépréciations des terrains bâtis",2,"actif"),
  t("2924","Dépréciations des travaux de mise en valeur des terrains",2,"actif"),
  t("2925","Dépréciations des terrains de gisement",2,"actif"),
  t("2926","Dépréciations des terrains aménagés",2,"actif"),
  t("2927","Dépréciations des terrains mis en concession",2,"actif"),
  t("2928","Dépréciations des autres terrains",2,"actif"),
  t("2929","Dépréciations des aménagements de terrains en cours",2,"actif"),
  t("293","Dépréciations des bâtiments, installations techniques et agencements",2,"actif"),
  t("2931","Dépréciations des bâtiments industriels, agricoles, administratifs et commerciaux sur sol propre",2,"actif"),
  t("2932","Dépréciations des bâtiments industriels, agricoles, administratifs et commerciaux sur sol d'autrui",2,"actif"),
  t("2933","Dépréciations des ouvrages d'infrastructures",2,"actif"),
  t("2934","Dépréciations des aménagements, agencements et installations techniques",2,"actif"),
  t("2935","Dépréciations des aménagements de bureaux",2,"actif"),
  t("2937","Dépréciations des bâtiments industriels, agricoles et commerciaux mis en concession",2,"actif"),
  t("2938","Dépréciations des autres installations et agencements",2,"actif"),
  t("2939","Dépréciations des bâtiments et installations en cours",2,"actif"),
  t("294","Dépréciations de matériel, du mobilier et de l'actif biologique",2,"actif"),
  t("2941","Dépréciations du matériel et outillage industriel et commercial",2,"actif"),
  t("2942","Dépréciations du matériel et outillage agricole",2,"actif"),
  t("2943","Dépréciations du matériel d'emballage récupérable et identifiable",2,"actif"),
  t("2944","Dépréciations du matériel et mobilier",2,"actif"),
  t("2945","Dépréciations du matériel de transport",2,"actif"),
  t("2946","Dépréciations des actifs biologiques",2,"actif"),
  t("2947","Dépréciations des agencements et aménagements du matériel et des actifs biologiques",2,"actif"),
  t("2948","Dépréciations des autres matériels",2,"actif"),
  t("2949","Dépréciations de matériel en cours",2,"actif"),
  t("295","Dépréciations des avances et acomptes versés sur immobilisations",2,"actif"),
  t("2951","Dépréciations des avances et acomptes versés sur immobilisations incorporelles",2,"actif"),
  t("2952","Dépréciations des avances et acomptes versés sur immobilisations corporelles",2,"actif"),
  t("296","Dépréciations des titres de participation",2,"actif"),
  t("2961","Dépréciations des titres de participation dans des sociétés sous contrôle exclusif",2,"actif"),
  t("2962","Dépréciations des titres de participation dans les sociétés sous contrôle conjoint",2,"actif"),
  t("2963","Dépréciations des titres de participation dans les sociétés conférant une influence notable",2,"actif"),
  t("2965","Dépréciations des participations dans des organismes professionnels",2,"actif"),
  t("2966","Dépréciations des parts dans des GIE",2,"actif"),
  t("2968","Dépréciations des autres titres de participation",2,"actif"),
  t("297","Dépréciations des autres immobilisations financières",2,"actif"),
  t("2971","Dépréciations des prêts et créances",2,"actif"),
  t("2972","Dépréciations des prêts au personnel",2,"actif"),
  t("2973","Dépréciations des créances sur l'État",2,"actif"),
  t("2974","Dépréciations des titres immobilisés",2,"actif"),
  t("2975","Dépréciations des dépôts et cautionnements versés",2,"actif"),
  t("2977","Dépréciations des créances rattachées à des participations et avances à des GIE",2,"actif"),
  t("2978","Dépréciations des créances financières diverses",2,"actif"),
  // ─── CLASSE 3 ───────────────────────────────────────────────
  t("31","Marchandises",3,"actif"),
  t("311","Marchandises A",3,"actif"),
  t("3111","Marchandises A1",3,"actif"),
  t("3112","Marchandises A2",3,"actif"),
  t("312","Marchandises B",3,"actif"),
  t("3121","Marchandises B1",3,"actif"),
  t("3122","Marchandises B2",3,"actif"),
  t("313","Actifs biologiques",3,"actif"),
  t("3131","Animaux",3,"actif"),
  t("3132","Végétaux",3,"actif"),
  t("318","Marchandises hors activités ordinaires (HAO)",3,"actif"),
  t("32","Matières premières et fournitures liées",3,"actif"),
  t("321","Matières A",3,"actif"),
  t("322","Matières B",3,"actif"),
  t("323","Fournitures (A, B)",3,"actif"),
  t("33","Autres approvisionnements",3,"actif"),
  t("331","Matières consommables",3,"actif"),
  t("332","Fournitures d'atelier et d'usine",3,"actif"),
  t("333","Fournitures de magasin",3,"actif"),
  t("334","Fournitures de bureau",3,"actif"),
  t("335","Emballages",3,"actif"),
  t("3351","Emballages perdus",3,"actif"),
  t("3352","Emballages récupérables non identifiables",3,"actif"),
  t("3353","Emballages à usage mixte",3,"actif"),
  t("3358","Autres emballages",3,"actif"),
  t("338","Autres matières",3,"actif"),
  t("34","Produits en cours",3,"actif"),
  t("341","Produits en cours",3,"actif"),
  t("3411","Produits en cours P1",3,"actif"),
  t("3412","Produits en cours P2",3,"actif"),
  t("342","Travaux en cours",3,"actif"),
  t("3421","Travaux en cours T1",3,"actif"),
  t("3422","Travaux en cours T2",3,"actif"),
  t("343","Produits intermédiaires en cours",3,"actif"),
  t("3431","Produits intermédiaires A",3,"actif"),
  t("3432","Produits intermédiaires B",3,"actif"),
  t("344","Produits résiduels en cours",3,"actif"),
  t("3441","Produits résiduels A",3,"actif"),
  t("3442","Produits résiduels B",3,"actif"),
  t("345","Actifs biologiques en cours",3,"actif"),
  t("3451","Animaux en cours",3,"actif"),
  t("3452","Végétaux en cours",3,"actif"),
  t("35","Services en cours",3,"actif"),
  t("351","Études en cours",3,"actif"),
  t("3511","Études en cours E1",3,"actif"),
  t("3512","Études en cours E2",3,"actif"),
  t("352","Prestations de services en cours",3,"actif"),
  t("3521","Prestations de services S1",3,"actif"),
  t("3522","Prestations de services S2",3,"actif"),
  t("36","Produits finis",3,"actif"),
  t("361","Produits finis A",3,"actif"),
  t("362","Produits finis B",3,"actif"),
  t("363","Actifs biologiques produits finis",3,"actif"),
  t("3631","Animaux",3,"actif"),
  t("3632","Végétaux",3,"actif"),
  t("3638","Autres stocks (activités annexes)",3,"actif"),
  t("37","Produits intermédiaires et résiduels",3,"actif"),
  t("371","Produits intermédiaires",3,"actif"),
  t("3711","Produits intermédiaires A",3,"actif"),
  t("3712","Produits intermédiaires B",3,"actif"),
  t("372","Produits résiduels",3,"actif"),
  t("3721","Déchets",3,"actif"),
  t("3722","Rebuts",3,"actif"),
  t("3723","Matières de Récupération",3,"actif"),
  t("373","Actifs biologiques produits intermédiaires",3,"actif"),
  t("3731","Animaux",3,"actif"),
  t("3732","Végétaux",3,"actif"),
  t("3738","Autres stocks (activités annexes)",3,"actif"),
  t("38","Stocks en cours de route, en consignation ou en dépôt",3,"actif"),
  t("381","Marchandises en cours de route",3,"actif"),
  t("382","Matières premières et fournitures liées en cours de route",3,"actif"),
  t("383","Autres approvisionnements en cours de route",3,"actif"),
  t("386","Produits finis en cours de route",3,"actif"),
  t("387","Stock en consignation ou en dépôt",3,"actif"),
  t("3871","Stock en consignation",3,"actif"),
  t("3872","Stock en dépôt",3,"actif"),
  t("388","Stock provenant d'immobilisations mises hors service ou au rebut",3,"actif"),
  t("39","Dépréciations des stocks et encours de production",3,"actif"),
  t("391","Dépréciations des stocks de marchandises",3,"actif"),
  t("392","Dépréciations des stocks de matières premières et fournitures liées",3,"actif"),
  t("393","Dépréciations des stocks d'autres approvisionnements",3,"actif"),
  t("394","Dépréciations des productions en cours",3,"actif"),
  t("395","Dépréciations des services en cours",3,"actif"),
  t("396","Dépréciations des stocks de produits finis",3,"actif"),
  t("397","Dépréciations des stocks de produits intermédiaires et résiduels",3,"actif"),
  t("398","Dépréciations des stocks en cours de route, en consignation ou en dépôt",3,"actif"),
  // ─── CLASSE 4 ───────────────────────────────────────────────
  t("40","Fournisseurs et comptes rattachés",4,"passif"),
  t("401","Fournisseurs, dettes en compte",4,"passif"),
  t("4011","Fournisseurs",4,"passif"),
  t("4012","Fournisseurs groupe",4,"passif"),
  t("4013","Fournisseurs sous-traitants",4,"passif"),
  t("4016","Fournisseurs, réserve de propriété",4,"passif"),
  t("4017","Fournisseur, retenues de garantie",4,"passif"),
  t("402","Fournisseurs, effets à payer",4,"passif"),
  t("4021","Fournisseurs - Effets à payer",4,"passif"),
  t("4022","Fournisseurs - Groupe, effets à payer",4,"passif"),
  t("4023","Fournisseurs - Sous-traitants, effets à payer",4,"passif"),
  t("404","Fournisseurs, acquisitions courantes d'immobilisations",4,"passif"),
  t("4041","Fournisseurs - Dettes en comptes, immobilisations incorporelles",4,"passif"),
  t("4042","Fournisseurs - Dettes en comptes, immobilisations corporelles",4,"passif"),
  t("4046","Fournisseurs - Effets à payer, immobilisations incorporelles",4,"passif"),
  t("4047","Fournisseurs - Effets à payer, immobilisations corporelles",4,"passif"),
  t("408","Fournisseurs, factures non parvenues",4,"passif"),
  t("4081","Fournisseurs factures non parvenues",4,"passif"),
  t("4082","Fournisseurs groupe factures non parvenues",4,"passif"),
  t("4083","Fournisseurs sous-traitants factures non parvenues",4,"passif"),
  t("4086","Fournisseurs, intérêts courus",4,"passif"),
  t("409","Fournisseurs débiteurs",4,"actif"),
  t("4091","Fournisseurs - Avances et acomptes versés",4,"actif"),
  t("4092","Fournisseurs - Groupe avances et acomptes versés",4,"actif"),
  t("4093","Fournisseurs - Sous-traitants avances et acomptes versés",4,"actif"),
  t("4094","Fournisseurs - Créances pour emballages et matériels à rendre",4,"actif"),
  t("4098","Fournisseurs - Rabais, remises, ristournes et autres avoirs à obtenir",4,"actif"),
  t("41","Clients et comptes rattachés",4,"actif"),
  t("411","Clients",4,"actif"),
  t("4111","Clients",4,"actif"),
  t("4112","Clients - groupe",4,"actif"),
  t("4114","Clients, État et Collectivités publiques",4,"actif"),
  t("4115","Clients, organismes internationaux",4,"actif"),
  t("4116","Clients, réserve de propriété",4,"actif"),
  t("4117","Client, retenues de garantie",4,"actif"),
  t("4118","Clients, dégrèvement de taxes sur la valeur ajoutée (TVA)",4,"actif"),
  t("412","Clients, effets à recevoir en portefeuille",4,"actif"),
  t("4121","Clients, effets à recevoir",4,"actif"),
  t("4122","Clients - Groupe, effets à recevoir",4,"actif"),
  t("4124","État et Collectivités publiques, effets à recevoir",4,"actif"),
  t("4125","Organismes Internationaux, effets à recevoir",4,"actif"),
  t("413","Clients, chèques, effets et autres valeurs impayées",4,"actif"),
  t("4131","Clients, chèques impayés",4,"actif"),
  t("4132","Clients, effets impayés",4,"actif"),
  t("4133","Clients, cartes de crédit impayées",4,"actif"),
  t("4138","Clients, autres valeurs impayées",4,"actif"),
  t("414","Créances sur cessions courantes d'immobilisations",4,"actif"),
  t("4141","Créances en compte, immobilisations incorporelles",4,"actif"),
  t("4142","Créances en compte, immobilisations corporelles",4,"actif"),
  t("4146","Effets à recevoir, immobilisations incorporelles",4,"actif"),
  t("4147","Effets à recevoir, immobilisations corporelles",4,"actif"),
  t("415","Clients, effets escomptés non échus",4,"actif"),
  t("416","Créances clients litigieuses ou douteuses",4,"actif"),
  t("4161","Créances litigieuses",4,"actif"),
  t("4162","Créances douteuses",4,"actif"),
  t("418","Clients, produits à recevoir",4,"actif"),
  t("4181","Clients, factures à établir",4,"actif"),
  t("4186","Clients, intérêts courus",4,"actif"),
  t("419","Clients créditeurs",4,"passif"),
  t("4191","Clients, avances et acomptes reçus",4,"passif"),
  t("4192","Clients - groupe, avances et acomptes reçus",4,"passif"),
  t("4194","Clients, dettes pour emballages et matériels consignés",4,"passif"),
  t("4198","Clients, rabais, remises, ristournes et autres avoirs à accorder",4,"passif"),
  t("42","Personnel",4,"passif"),
  t("421","Personnel, avances et acomptes",4,"actif"),
  t("4211","Personnel, avances",4,"actif"),
  t("4212","Personnel, acomptes",4,"actif"),
  t("4213","Frais avancés et fournitures au personnel",4,"actif"),
  t("422","Personnel, rémunérations dues",4,"passif"),
  t("423","Personnel, oppositions, saisies-arrêts",4,"passif"),
  t("4231","Personnel, oppositions",4,"passif"),
  t("4232","Personnel, saisies-arrêts",4,"passif"),
  t("4233","Personnel, avis à tiers détenteur",4,"passif"),
  t("424","Personnel, œuvres sociales internes",4,"passif"),
  t("4241","Assistance médicale",4,"passif"),
  t("4242","Allocations familiales",4,"passif"),
  t("4245","Organismes sociaux rattachés à l'entité",4,"passif"),
  t("4248","Autres œuvres sociales internes",4,"passif"),
  t("425","Représentants du personnel",4,"passif"),
  t("4251","Délégués du personnel",4,"passif"),
  t("4252","Syndicats et Comités d'entreprises, d'Établissement",4,"passif"),
  t("4258","Autres représentants du personnel",4,"passif"),
  t("426","Personnel, participation aux bénéfices et au capital",4,"passif"),
  t("4261","Participation aux bénéfices",4,"passif"),
  t("4264","Participation au capital",4,"passif"),
  t("427","Personnel - dépôts",4,"passif"),
  t("428","Personnel, charges à payer et produits à recevoir",4,"passif"),
  t("4281","Dettes provisionnées pour congés à payer",4,"passif"),
  t("4286","Autres charges à payer",4,"passif"),
  t("4287","Produits à recevoir",4,"actif"),
  t("43","Organismes sociaux",4,"passif"),
  t("431","Sécurité sociale",4,"passif"),
  t("4311","Prestations familiales",4,"passif"),
  t("4312","Accidents de travail",4,"passif"),
  t("4313","Caisse de retraite obligatoire",4,"passif"),
  t("4314","Caisse de retraite facultative",4,"passif"),
  t("4318","Autres cotisations sociales",4,"passif"),
  t("432","Caisses de retraite complémentaire",4,"passif"),
  t("433","Autres organismes sociaux",4,"passif"),
  t("4331","Mutuelle",4,"passif"),
  t("4332","Assurances retraite",4,"passif"),
  t("4333","Assurances et organismes de santé",4,"passif"),
  t("438","Organismes sociaux, charges à payer et produits à recevoir",4,"passif"),
  t("4381","Charges sociales sur gratifications à payer",4,"passif"),
  t("4382","Charges sociales sur congés à payer",4,"passif"),
  t("4386","Autres charges à payer",4,"passif"),
  t("4387","Produits à recevoir",4,"actif"),
  t("44","État et collectivités publiques",4,"autre"),
  t("441","État, impôt sur les bénéfices",4,"passif"),
  t("442","État, autres impôts et taxes",4,"passif"),
  t("4421","Impôts et taxes d'État",4,"passif"),
  t("4422","Impôts et taxes pour les collectivités publiques",4,"passif"),
  t("4423","Impôts et taxes recouvrables sur des obligataires",4,"passif"),
  t("4424","Impôts et taxes recouvrables sur des associés",4,"passif"),
  t("4426","Droits de douane",4,"passif"),
  t("4428","Autres impôts et taxes",4,"passif"),
  t("443","État, TVA facturée",4,"passif"),
  t("4431","TVA facturée sur ventes",4,"passif"),
  t("4432","TVA facturée sur prestations de services",4,"passif"),
  t("4433","TVA facturée sur travaux",4,"passif"),
  t("4434","TVA facturée sur production livrée à soi-même",4,"passif"),
  t("4435","TVA sur factures à établir",4,"passif"),
  t("444","État, TVA due ou crédit de TVA",4,"autre"),
  t("4441","État, TVA due",4,"passif"),
  t("4449","État, crédit de TVA à reporter",4,"actif"),
  t("445","État, TVA récupérable",4,"actif"),
  t("4451","TVA récupérable sur immobilisations",4,"actif"),
  t("4452","TVA récupérable sur achats",4,"actif"),
  t("4453","TVA récupérable sur transport",4,"actif"),
  t("4454","TVA récupérable sur services extérieurs et autres charges",4,"actif"),
  t("4455","TVA récupérable sur factures non parvenues",4,"actif"),
  t("4456","TVA transférée par d'autres entités",4,"actif"),
  t("446","État, autres taxes sur le chiffre d'affaires",4,"passif"),
  t("447","État, impôts retenus à la source",4,"passif"),
  t("4471","Impôt Général sur le revenu",4,"passif"),
  t("4472","Impôts sur salaires",4,"passif"),
  t("4473","Contribution nationale",4,"passif"),
  t("4474","Contribution nationale de solidarité",4,"passif"),
  t("4478","Autres impôts et contributions",4,"passif"),
  t("448","État, charges à payer et produits à recevoir",4,"autre"),
  t("4486","Charges à payer",4,"passif"),
  t("4487","Produits à recevoir",4,"actif"),
  t("449","État, créances et dettes diverses",4,"autre"),
  t("4491","État, obligations cautionnées",4,"passif"),
  t("4492","État, avances et acomptes versés sur impôts",4,"actif"),
  t("4493","État, fonds de dotation à recevoir",4,"actif"),
  t("4494","État, subventions investissement à recevoir",4,"actif"),
  t("4495","État, subventions d'exploitation à recevoir",4,"actif"),
  t("4496","État, subventions d'équilibre à recevoir",4,"actif"),
  t("4497","État, avances sur subventions",4,"actif"),
  t("4499","État, fonds réglementés provisionnés",4,"passif"),
  t("45","Organismes internationaux",4,"autre"),
  t("451","Opérations avec les organismes africains",4,"autre"),
  t("452","Opérations avec les autres organismes internationaux",4,"autre"),
  t("458","Organismes internationaux, fonds de dotation et subventions à recevoir",4,"actif"),
  t("4581","Organismes internationaux, fonds de dotation à recevoir",4,"actif"),
  t("4582","Organismes internationaux, subventions à recevoir",4,"actif"),
  t("46","Apporteurs, associés et groupe",4,"autre"),
  t("461","Apporteurs, opérations sur le capital",4,"autre"),
  t("4611","Apporteurs, apports en nature",4,"autre"),
  t("4612","Apporteurs, apports en numéraire",4,"autre"),
  t("4613","Apporteurs, capital appelé, non versé",4,"actif"),
  t("4614","Apporteurs, compte d'apport, opérations de restructuration (fusion...)",4,"autre"),
  t("4615","Apporteurs, versements reçus sur augmentation de capital",4,"autre"),
  t("4616","Apporteurs, versements anticipés",4,"autre"),
  t("4617","Apporteurs défaillants",4,"autre"),
  t("4618","Apporteurs, titres à échanger",4,"autre"),
  t("4619","Apporteurs, capital à rembourser",4,"passif"),
  t("462","Associés, comptes courants",4,"autre"),
  t("4621","Principal",4,"autre"),
  t("4626","Intérêts courus",4,"autre"),
  t("463","Associés, opérations faites en commun et GIE",4,"autre"),
  t("4631","Opérations courantes",4,"autre"),
  t("4636","Intérêts courus",4,"autre"),
  t("465","Associés, dividendes à payer",4,"passif"),
  t("466","Groupe, comptes courants",4,"autre"),
  t("467","Apporteurs, restant dû sur capital appelé",4,"actif"),
  t("47","Débiteurs et créditeurs divers",4,"autre"),
  t("471","Débiteurs et créditeurs divers",4,"autre"),
  t("4711","Débiteurs divers",4,"actif"),
  t("4712","Créditeurs divers",4,"passif"),
  t("4713","Obligataires",4,"autre"),
  t("4715","Rémunérations d'administrateurs",4,"passif"),
  t("4716","Compte d'affacturage",4,"autre"),
  t("4717","Débiteurs divers - retenues de garantie",4,"actif"),
  t("4718","Apport, compte de fusion et opérations assimilées",4,"autre"),
  t("4719","Bons de souscription d'actions et d'obligations",4,"autre"),
  t("472","Créances et dettes sur titres de placement",4,"autre"),
  t("4721","Créances sur cessions de titres de placement",4,"actif"),
  t("4726","Versements restant à effectuer sur titres de placement non libérés",4,"passif"),
  t("473","Intermédiaires - Opérations faites pour compte de tiers",4,"autre"),
  t("4731","Mandants",4,"autre"),
  t("4732","Mandataires",4,"autre"),
  t("4733","Commettants",4,"autre"),
  t("4734","Commissionnaires",4,"autre"),
  t("4739","État, Collectivités publiques, fonds global d'allocation",4,"autre"),
  t("474","Compte de répartition périodique des charges et des produits",4,"autre"),
  t("4746","Compte de répartition périodique des charges",4,"autre"),
  t("4747","Compte de répartition périodique des produits",4,"autre"),
  t("475","Compte transitoire, ajustement spécial lié à la révision du SYSCOHADA",4,"autre"),
  t("4751","Compte actif",4,"actif"),
  t("4752","Compte passif",4,"passif"),
  t("476","Charges constatées d'avance",4,"actif"),
  t("477","Produits constatés d'avance",4,"passif"),
  t("478","Écarts de conversion - actif",4,"actif"),
  t("4781","Diminution des créances d'exploitation",4,"actif"),
  t("4782","Diminution des créances financières",4,"actif"),
  t("4783","Augmentation des dettes d'exploitation",4,"actif"),
  t("4784","Augmentation des dettes financières",4,"actif"),
  t("4786","Différences d'évaluation sur instruments de trésorerie",4,"actif"),
  t("4788","Différences compensées par couverture de change",4,"actif"),
  t("479","Écarts de conversion - passif",4,"passif"),
  t("4791","Augmentation des créances d'exploitation",4,"passif"),
  t("4792","Augmentation des créances financières",4,"passif"),
  t("4793","Diminution des dettes d'exploitation",4,"passif"),
  t("4794","Diminution des dettes financières",4,"passif"),
  t("4797","Différences d'évaluation sur instruments de trésorerie",4,"passif"),
  t("4798","Différences compensées par couverture de change",4,"passif"),
  t("48","Créances et dettes hors activités ordinaires (HAO)",4,"autre"),
  t("481","Fournisseurs d'investissements",4,"passif"),
  t("4811","Immobilisations incorporelles",4,"passif"),
  t("4812","Immobilisations corporelles",4,"passif"),
  t("4813","Versements restant à effectuer sur titres non libérés",4,"passif"),
  t("4816","Réserve de propriété",4,"passif"),
  t("4817","Retenues de garantie",4,"passif"),
  t("4818","Factures non parvenues",4,"passif"),
  t("482","Fournisseurs d'investissements, effets à payer",4,"passif"),
  t("4821","Immobilisations incorporelles effets",4,"passif"),
  t("4822","Immobilisations corporelles effets",4,"passif"),
  t("484","Autres dettes hors activités ordinaires (HAO)",4,"passif"),
  t("485","Créances sur cessions d'immobilisations",4,"actif"),
  t("4851","En compte, immobilisations incorporelles",4,"actif"),
  t("4852","En compte, immobilisations corporelles",4,"actif"),
  t("4853","Effets à recevoir, immobilisations incorporelles",4,"actif"),
  t("4854","Effets à recevoir, immobilisations corporelles",4,"actif"),
  t("4855","Effets escomptés non échus",4,"actif"),
  t("4857","Retenues de garantie",4,"actif"),
  t("4858","Factures à établir",4,"actif"),
  t("488","Autres créances hors activités ordinaires (HAO)",4,"actif"),
  t("49","Dépréciations et provisions pour risques à court terme (tiers)",4,"actif"),
  t("490","Dépréciations des comptes fournisseurs",4,"actif"),
  t("491","Dépréciations des comptes clients",4,"actif"),
  t("4911","Créances litigieuses",4,"actif"),
  t("4912","Créances douteuses",4,"actif"),
  t("492","Dépréciations des comptes personnel",4,"actif"),
  t("493","Dépréciations des comptes organismes sociaux",4,"actif"),
  t("494","Dépréciations des comptes État et collectivités publiques",4,"actif"),
  t("495","Dépréciations des comptes organismes internationaux",4,"actif"),
  t("496","Dépréciations des comptes apporteurs, associés et groupe",4,"actif"),
  t("4962","Associés, comptes courants",4,"actif"),
  t("4963","Associés, opérations faites en commun",4,"actif"),
  t("4966","Groupe, comptes courants",4,"actif"),
  t("497","Dépréciations des comptes débiteurs divers",4,"actif"),
  t("498","Dépréciations des comptes de créances HAO",4,"actif"),
  t("4985","Créances sur cessions d'immobilisations",4,"actif"),
  t("4986","Créances sur cessions de titres de placement",4,"actif"),
  t("4988","Autres créances HAO",4,"actif"),
  t("499","Provisions pour risques à court terme",4,"passif"),
  t("4991","Sur opérations d'exploitation",4,"passif"),
  t("4997","Sur opérations financières",4,"passif"),
  t("4998","Sur opérations HAO",4,"passif"),
  // ─── CLASSE 5 ───────────────────────────────────────────────
  t("50","Titres de placement",5,"actif"),
  t("501","Titres du trésor et bons de caisse à court terme",5,"actif"),
  t("5011","Titres du Trésor à court terme",5,"actif"),
  t("5012","Titres d'organismes financiers",5,"actif"),
  t("5013","Bons de caisse à court terme",5,"actif"),
  t("5016","Frais d'acquisition des titres de trésor et bons de caisse",5,"actif"),
  t("502","Actions",5,"actif"),
  t("5021","Actions ou parts propres",5,"actif"),
  t("5022","Actions cotées",5,"actif"),
  t("5023","Actions non cotées",5,"actif"),
  t("5024","Actions démembrées (certificats d'investissement, droits de vote)",5,"actif"),
  t("5025","Autres actions",5,"actif"),
  t("5026","Frais d'acquisition des actions",5,"actif"),
  t("503","Obligations",5,"actif"),
  t("5031","Obligations émises par la société et rachetées par elle",5,"actif"),
  t("5032","Obligations cotées",5,"actif"),
  t("5033","Obligations non cotées",5,"actif"),
  t("5035","Autres obligations",5,"actif"),
  t("5036","Frais d'acquisition des obligations",5,"actif"),
  t("504","Bons de souscription",5,"actif"),
  t("5042","Bons de souscription d'actions",5,"actif"),
  t("5043","Bons de souscription d'obligations",5,"actif"),
  t("505","Titres négociables hors région",5,"actif"),
  t("506","Intérêts courus",5,"actif"),
  t("5061","Titres du Trésor et bons de caisse à court terme",5,"actif"),
  t("5062","Actions",5,"actif"),
  t("5063","Obligations",5,"actif"),
  t("508","Autres titres de placement et créances assimilées",5,"actif"),
  t("51","Valeurs à encaisser",5,"actif"),
  t("511","Effets à encaisser",5,"actif"),
  t("512","Effets à l'encaissement",5,"actif"),
  t("513","Chèques à encaisser",5,"actif"),
  t("514","Chèques à l'encaissement",5,"actif"),
  t("515","Cartes de crédit à encaisser",5,"actif"),
  t("518","Autres valeurs à l'encaissement",5,"actif"),
  t("5181","Warrants",5,"actif"),
  t("5182","Billets de fonds",5,"actif"),
  t("5185","Chèques de voyage",5,"actif"),
  t("5186","Coupons échus",5,"actif"),
  t("5187","Intérêts échus des obligations",5,"actif"),
  t("52","Banques",5,"actif"),
  t("521","Banques locales",5,"actif"),
  t("5211","Banques en monnaie nationale",5,"actif"),
  t("5215","Banques en devises",5,"actif"),
  t("522","Banques autres États région",5,"actif"),
  t("523","Banques autres États zone monétaire",5,"actif"),
  t("524","Banques hors zone monétaire",5,"actif"),
  t("525","Banques dépôt à terme",5,"actif"),
  t("526","Banques, intérêts courus",5,"actif"),
  t("5261","Banque, intérêts courus, charges à payer",5,"passif"),
  t("5267","Banque, intérêts courus, produits à recevoir",5,"actif"),
  t("53","Établissements financiers et assimilés",5,"actif"),
  t("531","Chèques postaux",5,"actif"),
  t("532","Trésor",5,"actif"),
  t("533","Sociétés de gestion et d'intermédiation (SGI)",5,"actif"),
  t("536","Établissements financiers, intérêts courus",5,"actif"),
  t("538","Autres organismes financiers",5,"actif"),
  t("54","Instruments de trésorerie",5,"actif"),
  t("541","Options de taux d'intérêt",5,"actif"),
  t("542","Options de taux de change",5,"actif"),
  t("543","Options de taux boursiers",5,"actif"),
  t("544","Instruments de marchés à terme",5,"actif"),
  t("545","Avoirs d'or et autres métaux précieux",5,"actif"),
  t("55","Instruments de monnaie électronique",5,"actif"),
  t("551","Monnaie électronique - carte carburant",5,"actif"),
  t("552","Monnaie électronique - téléphone portable",5,"actif"),
  t("553","Monnaie électronique - carte péage",5,"actif"),
  t("554","Porte-monnaie électronique",5,"actif"),
  t("558","Autres instruments de monnaies électroniques",5,"actif"),
  t("56","Banques, crédits de trésorerie et d'escompte",5,"passif"),
  t("561","Crédits de trésorerie",5,"passif"),
  t("564","Escompte de crédits de campagne",5,"passif"),
  t("565","Escompte de crédits ordinaires",5,"passif"),
  t("566","Banques, crédits de trésorerie, intérêts courus",5,"passif"),
  t("57","Caisse",5,"actif"),
  t("571","Caisse siège social",5,"actif"),
  t("5711","Caisse en monnaie nationale",5,"actif"),
  t("5712","Caisse en devises",5,"actif"),
  t("572","Caisse succursale A",5,"actif"),
  t("5721","En monnaie nationale",5,"actif"),
  t("5722","En devises",5,"actif"),
  t("573","Caisse succursale B",5,"actif"),
  t("5731","En monnaie nationale",5,"actif"),
  t("5732","En devises",5,"actif"),
  t("58","Régies d'avances, accréditifs et virements internes",5,"actif"),
  t("581","Régies d'avance",5,"actif"),
  t("582","Accréditifs",5,"actif"),
  t("585","Virements de fonds",5,"actif"),
  t("588","Autres virements internes",5,"actif"),
  t("59","Dépréciations et provisions pour risque à court terme",5,"actif"),
  t("590","Dépréciations des titres de placement",5,"actif"),
  t("591","Dépréciations des titres et valeurs à encaisser",5,"actif"),
  t("592","Dépréciations des comptes banques",5,"actif"),
  t("593","Dépréciations des comptes établissements financiers et assimilés",5,"actif"),
  t("594","Dépréciations des comptes d'instruments de trésorerie",5,"actif"),
  t("599","Provisions pour risque à court terme à caractère financier",5,"passif"),
  // ─── CLASSE 6 ───────────────────────────────────────────────
  t("60","Achats et variations de stocks",6,"charge"),
  t("601","Achats de marchandises",6,"charge"),
  t("6011","Dans la Région",6,"charge"),
  t("6012","Hors Région",6,"charge"),
  t("6013","Aux entités du groupe dans la Région",6,"charge"),
  t("6014","Aux entités du groupe hors Région",6,"charge"),
  t("6015","Frais sur achats",6,"charge"),
  t("6019","Rabais, remises et ristournes obtenus (non ventilés)",6,"charge"),
  t("602","Achats de matières premières et fournitures liées",6,"charge"),
  t("6021","Dans la Région",6,"charge"),
  t("6022","Hors Région",6,"charge"),
  t("6023","Aux entités du groupe dans la Région",6,"charge"),
  t("6024","Aux entités du groupe hors Région",6,"charge"),
  t("6025","Frais sur achats matières",6,"charge"),
  t("6029","Rabais, remises et ristournes obtenus (non ventilés) matières",6,"charge"),
  t("603","Variations des stocks de biens achetés",6,"charge"),
  t("6031","Variations des stocks de marchandises",6,"charge"),
  t("6032","Variations des stocks de matières premières et fournitures liées",6,"charge"),
  t("6033","Variations des stocks d'autres approvisionnements",6,"charge"),
  t("604","Achats stockés de matières et fournitures consommables",6,"charge"),
  t("6041","Matières consommables",6,"charge"),
  t("6042","Matières combustibles",6,"charge"),
  t("6043","Produits d'entretien",6,"charge"),
  t("6044","Fournitures d'atelier et d'usine",6,"charge"),
  t("6045","Frais sur achat stockés",6,"charge"),
  t("6046","Fournitures de magasin",6,"charge"),
  t("6047","Fournitures de bureau",6,"charge"),
  t("6049","Rabais, remises et ristournes obtenus (non ventilés) stockés",6,"charge"),
  t("605","Autres achats",6,"charge"),
  t("6051","Fournitures non stockables - Eau",6,"charge"),
  t("6052","Fournitures non stockables - Électricité",6,"charge"),
  t("6053","Fournitures non stockables - Autres énergies",6,"charge"),
  t("6054","Fournitures d'entretien non stockables",6,"charge"),
  t("6055","Fournitures de bureau non stockables",6,"charge"),
  t("6056","Achats de petit matériel et outillage",6,"charge"),
  t("6057","Achats d'études et prestations de services",6,"charge"),
  t("6058","Achats de travaux, matériels et équipements",6,"charge"),
  t("6059","Rabais, remises et ristournes obtenus (non ventilés) autres achats",6,"charge"),
  t("608","Achats d'emballages",6,"charge"),
  t("6081","Emballages perdus",6,"charge"),
  t("6082","Emballages récupérables non identifiables",6,"charge"),
  t("6083","Emballages à usage mixte",6,"charge"),
  t("6085","Frais sur achats emballages",6,"charge"),
  t("6089","Rabais, remises et ristournes obtenus (non ventilés) emballages",6,"charge"),
  t("61","Transports",6,"charge"),
  t("612","Transports sur ventes",6,"charge"),
  t("613","Transports pour le compte de tiers",6,"charge"),
  t("614","Transports du personnel",6,"charge"),
  t("616","Transports de plis",6,"charge"),
  t("618","Autres frais de transport",6,"charge"),
  t("6181","Voyages et déplacements",6,"charge"),
  t("6182","Transports entre établissements ou chantiers",6,"charge"),
  t("6183","Transports administratifs",6,"charge"),
  t("62","Services extérieurs",6,"charge"),
  t("621","Sous-traitance générale",6,"charge"),
  t("622","Locations, charges locatives",6,"charge"),
  t("6221","Locations de terrains",6,"charge"),
  t("6222","Locations de bâtiments",6,"charge"),
  t("6223","Locations de matériels et outillages",6,"charge"),
  t("6224","Malis sur emballages",6,"charge"),
  t("6225","Locations d'emballages",6,"charge"),
  t("6226","Fermages et loyers du foncier",6,"charge"),
  t("6228","Locations et charges locatives diverses",6,"charge"),
  t("623","Redevances de location acquisition",6,"charge"),
  t("6232","Crédit-bail immobilier",6,"charge"),
  t("6233","Crédit-bail mobilier",6,"charge"),
  t("6234","Location-vente",6,"charge"),
  t("6238","Autres contrats de location acquisition",6,"charge"),
  t("624","Entretien, réparations, remise en état et maintenance",6,"charge"),
  t("6241","Entretien et réparations des biens immobiliers",6,"charge"),
  t("6242","Entretien et réparations des biens mobiliers",6,"charge"),
  t("6243","Maintenance",6,"charge"),
  t("6244","Charges de démantèlement et remise en état",6,"charge"),
  t("6248","Autres entretiens et réparations",6,"charge"),
  t("625","Primes d'assurance",6,"charge"),
  t("6251","Assurances multirisques",6,"charge"),
  t("6252","Assurances matériel de transport",6,"charge"),
  t("6253","Assurances risques d'exploitation",6,"charge"),
  t("6254","Assurances responsabilité du producteur",6,"charge"),
  t("6255","Assurances insolvabilité clients",6,"charge"),
  t("6257","Assurances transport sur ventes",6,"charge"),
  t("6258","Autres primes d'assurances",6,"charge"),
  t("626","Études, recherches et documentation",6,"charge"),
  t("6261","Études et recherches",6,"charge"),
  t("6265","Documentation générale",6,"charge"),
  t("6266","Documentation technique",6,"charge"),
  t("627","Publicité, publications, relations publiques",6,"charge"),
  t("6271","Annonces, insertions",6,"charge"),
  t("6272","Catalogues, imprimés publicitaires",6,"charge"),
  t("6273","Échantillons",6,"charge"),
  t("6274","Foires et expositions",6,"charge"),
  t("6275","Publications",6,"charge"),
  t("6276","Cadeaux à la clientèle",6,"charge"),
  t("6277","Frais de colloques, séminaires, conférences",6,"charge"),
  t("6278","Autres charges de publicité et relations publiques",6,"charge"),
  t("628","Frais de télécommunications",6,"charge"),
  t("6281","Frais de téléphone",6,"charge"),
  t("6282","Frais de télex",6,"charge"),
  t("6283","Frais de télécopie",6,"charge"),
  t("6288","Autres frais de télécommunications",6,"charge"),
  t("63","Autres services extérieurs",6,"charge"),
  t("631","Frais bancaires",6,"charge"),
  t("6311","Frais sur titres (vente, garde)",6,"charge"),
  t("6312","Frais sur effets",6,"charge"),
  t("6313","Location de coffres",6,"charge"),
  t("6314","Commissions d'affacturage",6,"charge"),
  t("6315","Commissions sur cartes de crédit",6,"charge"),
  t("6316","Frais d'émission d'emprunts",6,"charge"),
  t("6317","Frais sur instruments monnaie électronique",6,"charge"),
  t("6318","Autres frais bancaires",6,"charge"),
  t("632","Rémunérations d'intermédiaires et de conseils",6,"charge"),
  t("6322","Commissions et courtages sur ventes",6,"charge"),
  t("6324","Honoraires des professions réglementées",6,"charge"),
  t("6325","Frais d'actes et de contentieux",6,"charge"),
  t("6326","Rémunérations d'affacturage",6,"charge"),
  t("6327","Rémunérations des autres prestataires de services",6,"charge"),
  t("6328","Divers frais",6,"charge"),
  t("633","Frais de formation du personnel",6,"charge"),
  t("634","Redevances pour brevets, licences, logiciels, concessions et droits similaires",6,"charge"),
  t("6342","Redevances pour brevets, licences",6,"charge"),
  t("6343","Redevances pour logiciels",6,"charge"),
  t("6344","Redevances pour marques",6,"charge"),
  t("6345","Redevances pour sites internet",6,"charge"),
  t("6346","Redevances pour concessions, droits et valeurs similaires",6,"charge"),
  t("635","Cotisations",6,"charge"),
  t("6351","Cotisations",6,"charge"),
  t("6358","Concours divers",6,"charge"),
  t("637","Rémunérations de personnel extérieur à l'entité",6,"charge"),
  t("6371","Personnel intérimaire",6,"charge"),
  t("6372","Personnel détaché ou prêté à l'entité",6,"charge"),
  t("638","Autres charges externes",6,"charge"),
  t("6381","Frais de recrutement du personnel",6,"charge"),
  t("6382","Frais de déménagement",6,"charge"),
  t("6383","Réceptions",6,"charge"),
  t("6384","Missions",6,"charge"),
  t("6385","Charges de copropriété",6,"charge"),
  t("64","Impôts et taxes",6,"charge"),
  t("641","Impôts et taxes directs",6,"charge"),
  t("6411","Impôts fonciers et taxes annexes",6,"charge"),
  t("6412","Patentes, licences et taxes annexes",6,"charge"),
  t("6413","Taxes sur appointements et salaires",6,"charge"),
  t("6414","Taxes d'apprentissage",6,"charge"),
  t("6415","Formation professionnelle continue",6,"charge"),
  t("6418","Autres impôts et taxes directs",6,"charge"),
  t("645","Impôts et taxes indirects",6,"charge"),
  t("646","Droits d'enregistrement",6,"charge"),
  t("6461","Droits de mutation",6,"charge"),
  t("6462","Droits de timbre",6,"charge"),
  t("6463","Taxes sur les véhicules de société",6,"charge"),
  t("6464","Vignettes",6,"charge"),
  t("6468","Autres droits",6,"charge"),
  t("647","Pénalités, amendes fiscales",6,"charge"),
  t("6471","Pénalités d'assiette, impôts directs",6,"charge"),
  t("6472","Pénalités d'assiette, impôts indirects",6,"charge"),
  t("6473","Pénalités de recouvrement, impôts directs",6,"charge"),
  t("6474","Pénalités de recouvrement, impôts indirects",6,"charge"),
  t("6478","Autres pénalités et amendes fiscales",6,"charge"),
  t("648","Autres impôts et taxes",6,"charge"),
  t("65","Autres charges",6,"charge"),
  t("651","Pertes sur créances clients et autres débiteurs",6,"charge"),
  t("6511","Clients",6,"charge"),
  t("6515","Autres débiteurs",6,"charge"),
  t("652","Quote-part de résultat sur opérations faites en commun",6,"charge"),
  t("6521","Quote-part transférée de bénéfices (comptabilité du gérant)",6,"charge"),
  t("6525","Pertes imputées par transfert (comptabilité des associés non gérants)",6,"charge"),
  t("654","Valeurs comptables des cessions courantes d'immobilisations",6,"charge"),
  t("6541","Immobilisations incorporelles",6,"charge"),
  t("6542","Immobilisations corporelles",6,"charge"),
  t("656","Perte de change sur créances et dettes commerciale",6,"charge"),
  t("657","Pénalités et amendes pénales",6,"charge"),
  t("658","Charges diverses",6,"charge"),
  t("6581","Indemnités de fonction et autres rémunérations d'administrateurs",6,"charge"),
  t("6582","Dons",6,"charge"),
  t("6583","Mécénat",6,"charge"),
  t("6588","Autres charges diverses",6,"charge"),
  t("659","Charges pour dépréciations et provisions pour risques à court terme d'exploitation",6,"charge"),
  t("6591","Sur risques à court terme",6,"charge"),
  t("6593","Sur stocks",6,"charge"),
  t("6594","Sur créances",6,"charge"),
  t("6598","Autres charges pour dépréciations et provisions pour risques à court terme",6,"charge"),
  t("66","Charges de personnel",6,"charge"),
  t("661","Rémunérations directes versées au personnel national",6,"charge"),
  t("6611","Appointements salaires et commissions",6,"charge"),
  t("6612","Primes et gratifications",6,"charge"),
  t("6613","Congés payés",6,"charge"),
  t("6614","Indemnités de préavis, de licenciement et de recherche d'embauche",6,"charge"),
  t("6615","Indemnités de maladie versées aux travailleurs",6,"charge"),
  t("6616","Supplément familial",6,"charge"),
  t("6617","Avantages en nature",6,"charge"),
  t("6618","Autres rémunérations directes",6,"charge"),
  t("662","Rémunérations directes versées au personnel non national",6,"charge"),
  t("6621","Appointements salaires et commissions non national",6,"charge"),
  t("6622","Primes et gratifications non national",6,"charge"),
  t("6623","Congés payés non national",6,"charge"),
  t("6624","Indemnités de préavis non national",6,"charge"),
  t("6625","Indemnités de maladie non national",6,"charge"),
  t("6626","Supplément familial non national",6,"charge"),
  t("6627","Avantages en nature non national",6,"charge"),
  t("6628","Autres rémunérations directes non national",6,"charge"),
  t("663","Indemnités forfaitaires versées au personnel",6,"charge"),
  t("6631","Indemnités de logement",6,"charge"),
  t("6632","Indemnités de représentation",6,"charge"),
  t("6633","Indemnités d'expatriation",6,"charge"),
  t("6634","Indemnités de transport",6,"charge"),
  t("6638","Autres indemnités et avantages divers",6,"charge"),
  t("664","Charges sociales",6,"charge"),
  t("6641","Charges sociales sur rémunération du personnel national",6,"charge"),
  t("6642","Charges sociales sur rémunération du personnel non national",6,"charge"),
  t("666","Rémunérations et charges sociales de l'exploitant individuel",6,"charge"),
  t("6661","Rémunération du travail de l'exploitant",6,"charge"),
  t("6662","Charges sociales exploitant",6,"charge"),
  t("667","Rémunération transférée de personnel extérieur",6,"charge"),
  t("6671","Personnel intérimaire transféré",6,"charge"),
  t("6672","Personnel détaché ou prêté à l'entité transféré",6,"charge"),
  t("668","Autres charges sociales",6,"charge"),
  t("6681","Versements aux syndicats et comités d'entreprise",6,"charge"),
  t("6682","Versements aux comités d'hygiène et de sécurité",6,"charge"),
  t("6683","Versements et contributions aux autres œuvres sociales",6,"charge"),
  t("6684","Médecine du travail et pharmacie",6,"charge"),
  t("6685","Assurances et organismes de santé",6,"charge"),
  t("6686","Assurances retraite et fonds de pension",6,"charge"),
  t("6687","Majorations et pénalités sociales",6,"charge"),
  t("6688","Charges sociales diverses",6,"charge"),
  t("67","Frais financiers et charges assimilées",6,"charge"),
  t("671","Intérêts des emprunts",6,"charge"),
  t("6711","Emprunts obligataires",6,"charge"),
  t("6712","Emprunts auprès des établissements de crédit",6,"charge"),
  t("6713","Dettes liées à des participations",6,"charge"),
  t("6714","Primes de remboursement des obligations",6,"charge"),
  t("672","Intérêts dans loyers de location acquisition",6,"charge"),
  t("6722","Intérêts dans loyers de location acquisition / crédit-bail immobilier",6,"charge"),
  t("6723","Intérêts dans loyers de location acquisition / crédit-bail mobilier",6,"charge"),
  t("6724","Intérêts dans loyers de location acquisition / location-vente",6,"charge"),
  t("6728","Intérêts dans loyers des autres locations acquisition",6,"charge"),
  t("673","Escomptes accordés",6,"charge"),
  t("674","Autres intérêts",6,"charge"),
  t("6741","Avances reçues et dépôts créditeurs",6,"charge"),
  t("6742","Comptes courants bloqués",6,"charge"),
  t("6743","Intérêts sur obligations cautionnées",6,"charge"),
  t("6744","Intérêts sur dettes commerciales",6,"charge"),
  t("6745","Intérêts bancaires et sur opérations de financement (escompte...)",6,"charge"),
  t("6748","Intérêts sur dettes diverses",6,"charge"),
  t("675","Escomptes des effets de commerce",6,"charge"),
  t("676","Pertes de change financières",6,"charge"),
  t("677","Pertes sur titres de placement",6,"charge"),
  t("6771","Pertes sur cessions de titres de placement",6,"charge"),
  t("6772","Mali provenant d'attribution gratuite d'actions au personnel",6,"charge"),
  t("678","Pertes et charges sur risques financiers",6,"charge"),
  t("6781","Sur rentes viagères",6,"charge"),
  t("6782","Sur opérations financières",6,"charge"),
  t("6784","Sur instruments de trésorerie",6,"charge"),
  t("679","Charges pour dépréciations et provisions pour risques à court terme financières",6,"charge"),
  t("6791","Sur risques financiers",6,"charge"),
  t("6795","Sur titres de placement",6,"charge"),
  t("6798","Autres charges pour dépréciations et provisions pour risques à court terme financières",6,"charge"),
  t("68","Dotations aux amortissements",6,"charge"),
  t("681","Dotations aux amortissements d'exploitation",6,"charge"),
  t("6812","Dotations aux amortissements des immobilisations incorporelles",6,"charge"),
  t("6813","Dotations aux amortissements des immobilisations corporelles",6,"charge"),
  t("69","Dotations aux provisions et aux dépréciations",6,"charge"),
  t("691","Dotations aux provisions et aux dépréciations d'exploitation",6,"charge"),
  t("6911","Dotations aux provisions pour risques et charges",6,"charge"),
  t("6913","Dotations aux dépréciations des immobilisations incorporelles",6,"charge"),
  t("6914","Dotations aux dépréciations des immobilisations corporelles",6,"charge"),
  t("697","Dotations aux provisions et aux dépréciations financières",6,"charge"),
  t("6971","Dotations aux provisions pour risques et charges financières",6,"charge"),
  t("6972","Dotations aux dépréciations des immobilisations financières",6,"charge"),
  // ─── CLASSE 7 ───────────────────────────────────────────────
  t("70","Ventes",7,"produit"),
  t("701","Ventes de marchandises",7,"produit"),
  t("7011","Dans la Région",7,"produit"),
  t("7012","Hors Région",7,"produit"),
  t("7013","Aux entités du groupe dans la Région",7,"produit"),
  t("7014","Aux entités du groupe hors Région",7,"produit"),
  t("7015","Sur internet",7,"produit"),
  t("7019","Rabais, remises, ristournes accordés (non ventilés)",7,"produit"),
  t("702","Ventes de produits finis",7,"produit"),
  t("7021","Dans la Région produits finis",7,"produit"),
  t("7022","Hors Région produits finis",7,"produit"),
  t("7023","Aux entités du groupe dans la Région produits finis",7,"produit"),
  t("7024","Aux entités du groupe hors Région produits finis",7,"produit"),
  t("7025","Sur internet produits finis",7,"produit"),
  t("7029","Rabais, remises, ristournes accordés produits finis (non ventilés)",7,"produit"),
  t("703","Ventes de produits intermédiaires",7,"produit"),
  t("7031","Dans la Région produits intermédiaires",7,"produit"),
  t("7032","Hors Région produits intermédiaires",7,"produit"),
  t("7033","Aux entités du groupe dans la Région produits intermédiaires",7,"produit"),
  t("7034","Aux entités du groupe hors Région produits intermédiaires",7,"produit"),
  t("7035","Sur internet produits intermédiaires",7,"produit"),
  t("7039","Rabais, remises, ristournes accordés produits intermédiaires",7,"produit"),
  t("704","Ventes de produits résiduels",7,"produit"),
  t("7041","Dans la Région produits résiduels",7,"produit"),
  t("7042","Hors Région produits résiduels",7,"produit"),
  t("7043","Aux entités du groupe dans la Région produits résiduels",7,"produit"),
  t("7044","Aux entités du groupe hors Région produits résiduels",7,"produit"),
  t("7045","Sur internet produits résiduels",7,"produit"),
  t("7049","Rabais, remises, ristournes accordés produits résiduels",7,"produit"),
  t("705","Travaux facturés",7,"produit"),
  t("7051","Dans la Région travaux",7,"produit"),
  t("7052","Hors Région travaux",7,"produit"),
  t("7053","Aux entités du groupe dans la Région travaux",7,"produit"),
  t("7054","Aux entités du groupe hors Région travaux",7,"produit"),
  t("7055","Sur internet travaux",7,"produit"),
  t("7059","Rabais, remises, ristournes accordés travaux",7,"produit"),
  t("706","Services vendus",7,"produit"),
  t("7061","Dans la Région services",7,"produit"),
  t("7062","Hors Région services",7,"produit"),
  t("7063","Aux entités du groupe dans la Région services",7,"produit"),
  t("7064","Aux entités du groupe hors Région services",7,"produit"),
  t("7065","Sur internet services",7,"produit"),
  t("7069","Rabais, remises, ristournes accordés services",7,"produit"),
  t("707","Produits accessoires",7,"produit"),
  t("7071","Ports, emballages perdus et autres frais facturés",7,"produit"),
  t("7072","Commissions et courtages",7,"produit"),
  t("7073","Locations",7,"produit"),
  t("7074","Bonis sur reprises et cessions d'emballages",7,"produit"),
  t("7075","Mise à disposition de personnel",7,"produit"),
  t("7076","Redevances pour brevets, logiciels, marques et droits similaires",7,"produit"),
  t("7077","Services exploités dans l'intérêt du personnel",7,"produit"),
  t("7078","Autres produits accessoires",7,"produit"),
  t("71","Subventions d'exploitation",7,"produit"),
  t("711","Sur produits à l'exportation",7,"produit"),
  t("712","Sur produits à l'importation",7,"produit"),
  t("713","Sur produits de péréquation",7,"produit"),
  t("714","Indemnités et subventions d'exploitation (entité agricole)",7,"produit"),
  t("718","Autres subventions d'exploitation",7,"produit"),
  t("7181","Versées par l'État et les collectivités publiques",7,"produit"),
  t("7182","Versées par les organismes internationaux",7,"produit"),
  t("7183","Versées par des tiers",7,"produit"),
  t("72","Production immobilisée",7,"produit"),
  t("721","Immobilisations incorporelles",7,"produit"),
  t("722","Immobilisations corporelles",7,"produit"),
  t("7221","Immobilisations corporelles (hors actifs biologiques)",7,"produit"),
  t("7222","Immobilisations corporelles (actifs biologiques)",7,"produit"),
  t("724","Production auto-consommée",7,"produit"),
  t("726","Immobilisations financières",7,"produit"),
  t("73","Variations des stocks de biens et de services produits",7,"produit"),
  t("734","Variations des stocks de produits en cours",7,"produit"),
  t("7341","Produits en cours",7,"produit"),
  t("7342","Travaux en cours",7,"produit"),
  t("735","Variations des en-cours de services",7,"produit"),
  t("7351","Études en cours",7,"produit"),
  t("7352","Prestations de services en cours",7,"produit"),
  t("736","Variations des stocks de produits finis",7,"produit"),
  t("737","Variations des stocks de produits intermédiaires et résiduels",7,"produit"),
  t("7371","Produits intermédiaires",7,"produit"),
  t("7372","Produits résiduels",7,"produit"),
  t("75","Autres produits",7,"produit"),
  t("751","Profits sur créances clients et autres débiteurs",7,"produit"),
  t("752","Quote-part de résultat sur opérations faites en commun",7,"produit"),
  t("7521","Quote-part transférée de pertes (comptabilité du gérant)",7,"produit"),
  t("7525","Bénéfices attribués par transfert (comptabilité des associés non gérants)",7,"produit"),
  t("754","Produits des cessions courantes d'immobilisations",7,"produit"),
  t("7541","Immobilisations incorporelles",7,"produit"),
  t("7542","Immobilisations corporelles",7,"produit"),
  t("756","Gains de change sur créances et dettes commerciales",7,"produit"),
  t("758","Produits divers",7,"produit"),
  t("7581","Indemnités de fonction et autres rémunérations d'administrateurs",7,"produit"),
  t("7582","Indemnités d'assurances reçues",7,"produit"),
  t("7588","Autres produits divers",7,"produit"),
  t("759","Reprises de charges pour dépréciations et provisions d'exploitation",7,"produit"),
  t("7591","Sur risques à court terme",7,"produit"),
  t("7593","Sur stocks",7,"produit"),
  t("7594","Sur créances",7,"produit"),
  t("7598","Sur autres charges pour dépréciations et provisions pour risques à court terme d'exploitation",7,"produit"),
  t("77","Revenus financiers et produits assimilés",7,"produit"),
  t("771","Intérêts de prêts et créances diverses",7,"produit"),
  t("7712","Intérêts de prêts",7,"produit"),
  t("7713","Intérêts sur créances diverses",7,"produit"),
  t("772","Revenus de participations et autres titres immobilisés",7,"produit"),
  t("7721","Revenus des titres de participation",7,"produit"),
  t("7722","Revenus autres titres immobilisés",7,"produit"),
  t("773","Escomptes obtenus",7,"produit"),
  t("774","Revenus de placement",7,"produit"),
  t("7745","Revenus des obligations",7,"produit"),
  t("7746","Revenus des titres de placement",7,"produit"),
  t("775","Intérêts dans loyers de location acquisition",7,"produit"),
  t("776","Gains de change financiers",7,"produit"),
  t("777","Gains sur cessions de titres de placement",7,"produit"),
  t("778","Gains sur risques financiers",7,"produit"),
  t("7781","Sur rentes viagères",7,"produit"),
  t("7782","Sur opérations financières",7,"produit"),
  t("7784","Sur instruments de trésorerie",7,"produit"),
  t("779","Reprises de charges pour dépréciations et provisions à court terme financières",7,"produit"),
  t("7791","Sur risques financiers",7,"produit"),
  t("7795","Sur titres de placement",7,"produit"),
  t("7798","Sur autres charges pour dépréciations et provisions pour risques à court terme financières",7,"produit"),
  t("78","Transferts de charges",7,"produit"),
  t("781","Transferts de charges d'exploitation",7,"produit"),
  t("787","Transferts de charges financières",7,"produit"),
  t("79","Reprises de provisions, de dépréciations et autres",7,"produit"),
  t("791","Reprises de provisions et dépréciations d'exploitation",7,"produit"),
  t("7911","Pour risques et charges",7,"produit"),
  t("7913","Des immobilisations incorporelles",7,"produit"),
  t("7914","Des immobilisations corporelles",7,"produit"),
  t("797","Reprises de provisions et dépréciations financières",7,"produit"),
  t("7971","Pour risques et charges financières",7,"produit"),
  t("7972","Des immobilisations financières",7,"produit"),
  t("798","Reprises d'amortissements",7,"produit"),
  t("799","Reprises de subventions d'investissement",7,"produit"),
  // ─── CLASSE 8 ───────────────────────────────────────────────
  t("81","Valeurs comptables des cessions d'immobilisations",8,"charge"),
  t("811","Immobilisations incorporelles",8,"charge"),
  t("812","Immobilisations corporelles",8,"charge"),
  t("816","Immobilisations financières",8,"charge"),
  t("82","Produits des cessions d'immobilisations",8,"produit"),
  t("821","Immobilisations incorporelles",8,"produit"),
  t("822","Immobilisations corporelles",8,"produit"),
  t("826","Immobilisations financières",8,"produit"),
  t("83","Charges hors activités ordinaires",8,"charge"),
  t("831","Charges HAO constatées",8,"charge"),
  t("833","Charges liées aux opérations de restructuration",8,"charge"),
  t("834","Pertes sur créances HAO",8,"charge"),
  t("835","Dons et libéralités accordés",8,"charge"),
  t("836","Abandons de créances consentis",8,"charge"),
  t("837","Charges liées aux opérations de liquidation",8,"charge"),
  t("839","Charges pour dépréciations et provisions pour risques à court terme HAO",8,"charge"),
  t("84","Produits hors activités ordinaires",8,"produit"),
  t("841","Produits HAO constatés",8,"produit"),
  t("843","Produits liés aux opérations de restructuration",8,"produit"),
  t("844","Indemnités et subventions HAO (entité agricole)",8,"produit"),
  t("845","Dons et libéralités obtenus",8,"produit"),
  t("846","Abandons de créances obtenus",8,"produit"),
  t("847","Produits liés aux opérations de liquidation",8,"produit"),
  t("848","Transferts de charges HAO",8,"produit"),
  t("849","Reprises de charges pour dépréciations et provisions pour risques à court terme HAO",8,"produit"),
  t("85","Dotations hors activités ordinaires",8,"charge"),
  t("851","Dotations aux provisions réglementées",8,"charge"),
  t("852","Dotations aux amortissements HAO",8,"charge"),
  t("853","Dotations aux dépréciations HAO",8,"charge"),
  t("854","Dotations aux provisions pour risques et charges HAO",8,"charge"),
  t("858","Autres dotations HAO",8,"charge"),
  t("86","Reprises de charges, provisions et dépréciations HAO",8,"produit"),
  t("861","Reprises de provisions réglementées",8,"produit"),
  t("862","Reprises d'amortissements HAO",8,"produit"),
  t("863","Reprises de dépréciations HAO",8,"produit"),
  t("864","Reprises de provisions pour risques et charges HAO",8,"produit"),
  t("868","Autres reprises HAO",8,"produit"),
  t("87","Participation des travailleurs",8,"charge"),
  t("871","Participation légale aux bénéfices",8,"charge"),
  t("874","Participation contractuelle aux bénéfices",8,"charge"),
  t("878","Autres participations",8,"charge"),
  t("88","Subventions d'équilibre",8,"produit"),
  t("881","État",8,"produit"),
  t("884","Collectivités publiques",8,"produit"),
  t("886","Groupe",8,"produit"),
  t("888","Autres",8,"produit"),
  t("89","Impôts sur le résultat",8,"charge"),
  t("891","Impôts sur les bénéfices de l'exercice",8,"charge"),
  t("8911","Activités exercées dans l'État",8,"charge"),
  t("8912","Activités exercées dans les autres États de la Région",8,"charge"),
  t("8913","Activités exercées hors Région",8,"charge"),
  t("892","Rappel d'impôts sur résultats antérieurs",8,"charge"),
  t("895","Impôt minimum forfaitaire IMF",8,"charge"),
  t("899","Dégrèvements et annulations d'impôts sur résultats antérieurs",8,"charge"),
  t("8991","Dégrèvements",8,"charge"),
  t("8994","Annulations pour pertes rétroactives",8,"charge"),
  // ─── CLASSE 9 ───────────────────────────────────────────────
  t("90","Engagements obtenus et engagements accordés",9,"autre"),
  t("91","Engagements obtenus",9,"autre"),
  t("911","Avals, cautions, garanties reçus",9,"autre"),
  t("912","Crédits documentaires reçus",9,"autre"),
  t("913","Effets admis à l'escompte et non encore échus",9,"autre"),
  t("914","Engagements de financement reçus",9,"autre"),
  t("916","Autres engagements obtenus",9,"autre"),
  t("92","Engagements accordés",9,"autre"),
  t("921","Avals, cautions, garanties donnés",9,"autre"),
  t("922","Crédits documentaires ouverts",9,"autre"),
  t("923","Effets escomptés non échus",9,"autre"),
  t("924","Engagements de financement accordés",9,"autre"),
  t("926","Autres engagements accordés",9,"autre"),
  t("93","Comptes de contrepartie des engagements hors bilan",9,"autre"),
  t("94","Comptes analytiques de charges",9,"autre"),
  t("95","Comptes analytiques de produits",9,"autre"),
  t("96","Comptes de stocks analytiques",9,"autre"),
  t("97","Comptes de résultats analytiques",9,"autre"),
  t("98","Comptes de sections homogènes analytiques",9,"autre"),
  t("99","Comptes de liaison analytique et réfléchis",9,"autre"),
]

export default PLAN_COMPTABLE_OHADA
