// Chapitre 11 du module UE2, Droit des sociétés : contenu pur.
// La mise en forme appartient au moteur components/chapitre/ChapitreManuscrit.tsx.
//
// Réécriture approfondie (septembre 2026). Sources lues pendant la rédaction :
// - AUSCGIE révisé du 30 janvier 2014, texte intégral des art. 854 à 868
//   (société en participation, société créée de fait, société de fait),
//   ainsi que les art. 4, 54, 114, 115, 188, 253, 270, 271 et 290 (skill
//   auscgie-acte-uniforme) ;
// - loi n° 23/053 du 30 novembre 2023, art. 3 et 4 (champ de l'IS : sociétés
//   de fait et associations momentanées par l'activité, sociétés en
//   participation sur option), d'après le skill fiscalite-rdc ;
// - AUDCG du 15 décembre 2010, art. 7 (conjoint du commerçant).
import type { Chapitre } from '@/lib/chapitre-types'

const QCM: Chapitre['qcm'] = [
  {
    id: 'ch11-q1', question: "Qu'est-ce qu'une société en participation ?",
    options: [
      { id: 'a', texte: "Une société dont les associés participent tous à la gestion" },
      { id: 'b', texte: "Une société que les associés conviennent de ne pas immatriculer, sans personnalité morale ni publicité" },
      { id: 'c', texte: "Une société cotée en bourse" },
      { id: 'd', texte: "Une filiale commune de deux sociétés" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 854 AUSCGIE',
    explication: "« La société en participation est celle dans laquelle les associés conviennent qu'elle n'est pas immatriculée au registre du commerce et du crédit mobilier. Elle n'a pas la personnalité morale et n'est pas soumise à publicité » (art. 854 al. 1). L'absence d'immatriculation est ici voulue.",
  },
  {
    id: 'ch11-q2', question: "Comment prouve-t-on l'existence d'une société en participation ?",
    options: [
      { id: 'a', texte: "Uniquement par acte notarié" },
      { id: 'b', texte: "Par tous moyens" },
      { id: 'c', texte: "Par un extrait du RCCM" },
      { id: 'd', texte: "Par une déclaration fiscale" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 854 al. 2 AUSCGIE',
    explication: "« L'existence de la société en participation peut être prouvée par tous moyens » (art. 854 al. 2) : contrat écrit, correspondances, comptes communs, témoignages. Un écrit reste vivement recommandé pour organiser les rapports entre associés.",
  },
  {
    id: 'ch11-q3', question: "Quelle liberté les associés d'une société en participation ont-ils ?",
    options: [
      { id: 'a', texte: "Aucune, tout est fixé par la loi" },
      { id: 'b', texte: "Ils fixent librement l'objet, la durée, le fonctionnement, les droits des associés et la fin, sous réserve des règles impératives communes aux sociétés, hors celles relatives à la personnalité morale" },
      { id: 'c', texte: "Ils peuvent déroger à toutes les règles de l'Acte uniforme" },
      { id: 'd', texte: "Ils doivent adopter les statuts types d'une SARL" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 855 AUSCGIE',
    explication: "Les associés conviennent librement de l'objet, de la durée, du fonctionnement, des droits des associés et de la fin de la société, « sous réserve de ne pas déroger aux règles impératives des dispositions communes aux sociétés, exception faite de celles qui sont relatives à la personnalité morale » (art. 855).",
  },
  {
    id: 'ch11-q4', question: "À défaut d'organisation conventionnelle, quelles règles régissent les rapports entre associés d'une société en participation ?",
    options: [
      { id: 'a', texte: "Celles de la SARL" },
      { id: 'b', texte: "Celles de la SNC" },
      { id: 'c', texte: "Celles du GIE" },
      { id: 'd', texte: "Celles de l'association" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 856 AUSCGIE',
    explication: "« À moins qu'une organisation différente n'ait été prévue, les rapports entre associés sont régis par les dispositions applicables aux sociétés en nom collectif » (art. 856) : gérance, décisions à l'unanimité à défaut de clause, etc.",
  },
  {
    id: 'ch11-q5', question: "Un associé met son camion à la disposition de la société en participation. Qui en est propriétaire ?",
    options: [
      { id: 'a', texte: "La société en participation" },
      { id: 'b', texte: "L'associé qui l'a mis à disposition" },
      { id: 'c', texte: "Tous les associés en indivision, automatiquement" },
      { id: 'd', texte: "Le gérant" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 857 AUSCGIE',
    explication: "Les biens nécessaires à l'activité sont mis à la disposition du gérant, mais « chaque associé reste propriétaire des biens qu'il met à la disposition de la société » (art. 857). La société, dépourvue de personnalité morale, ne peut être propriétaire.",
  },
  {
    id: 'ch11-q6', question: "Les associés achètent ensemble, avec des fonds indivis, un entrepôt pour l'activité commune. Quel est son statut ?",
    options: [
      { id: 'a', texte: "Il appartient à la société" },
      { id: 'b', texte: "Il est réputé indivis entre les associés" },
      { id: 'c', texte: "Il appartient au gérant" },
      { id: 'd', texte: "Il appartient à l'associé le plus âgé" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 859 AUSCGIE',
    explication: "« Sont réputés indivis entre les associés les biens acquis par emploi ou par remploi de deniers indivis pendant la durée de la société », ainsi que ceux déjà indivis ou que les associés ont convenu de mettre en indivision (art. 859).",
  },
  {
    id: 'ch11-q7', question: "Un associé peut-il demander le partage des biens indivis pendant la vie de la société en participation ?",
    options: [
      { id: 'a', texte: "Oui, à tout moment" },
      { id: 'b', texte: "Non, sauf clause contraire, tant que la société n'est pas dissoute" },
      { id: 'c', texte: "Oui, avec l'accord du juge" },
      { id: 'd', texte: "Oui, après un an" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 860 AUSCGIE',
    explication: "« Sauf clause contraire des statuts, aucun associé ne peut demander le partage des biens indivis tant que la société n'est pas dissoute » (art. 860). La règle préserve l'outil commun pendant la durée de la collaboration.",
  },
  {
    id: 'ch11-q8', question: "Les associés peuvent-ils convenir que l'un d'eux est, à l'égard des tiers, propriétaire des biens acquis pour l'objet social ?",
    options: [
      { id: 'a', texte: "Non" },
      { id: 'b', texte: "Oui" },
      { id: 'c', texte: "Seulement pour les immeubles" },
      { id: 'd', texte: "Seulement avec l'accord des créanciers" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 858 AUSCGIE',
    explication: "Les associés peuvent convenir de mettre certains biens en indivision, ou « que l'un des associés est, à l'égard des tiers, propriétaire de tout ou partie des biens qu'il acquiert en vue de la réalisation de l'objet social » (art. 858). C'est souvent le « gérant » ou « chef de file » de la participation.",
  },
  {
    id: 'ch11-q9', question: "En principe, qui est engagé envers le tiers qui contracte avec un associé d'une société en participation ?",
    options: [
      { id: 'a', texte: "La société" },
      { id: 'b', texte: "Seul l'associé qui a contracté en son nom personnel" },
      { id: 'c', texte: "Tous les associés solidairement" },
      { id: 'd', texte: "Le gérant seulement" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 861 al. 1 AUSCGIE',
    explication: "« Chaque associé contracte en son nom personnel et est seul engagé à l'égard des tiers » (art. 861 al. 1). La société en participation est en principe occulte : le tiers ne connaît que son cocontractant.",
  },
  {
    id: 'ch11-q10', question: "Deux associés se présentent expressément comme associés d'une société en participation devant un fournisseur. Quelle conséquence ?",
    options: [
      { id: 'a', texte: "Chacun reste seul engagé pour ses propres contrats" },
      { id: 'b', texte: "Chacun de ceux qui ont agi est tenu des engagements des autres, indéfiniment et solidairement" },
      { id: 'c', texte: "La société acquiert la personnalité morale" },
      { id: 'd', texte: "Le contrat est nul" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 861 al. 2 et 3 AUSCGIE',
    explication: "« Si les associés agissent expressément en leur qualité d'associé auprès des tiers, chacun de ceux qui ont agi est tenu par les engagements des autres. Les obligations souscrites dans ces conditions les engagent indéfiniment et solidairement » (art. 861 al. 2 et 3).",
  },
  {
    id: 'ch11-q11', question: "Un associé qui n'a pas contracté peut-il être engagé envers le tiers ?",
    options: [
      { id: 'a', texte: "Non, jamais" },
      { id: 'b', texte: "Oui, si par son immixtion il a laissé croire au cocontractant qu'il s'engageait et que l'engagement a tourné à son profit" },
      { id: 'c', texte: "Oui, toujours" },
      { id: 'd', texte: "Seulement s'il est gérant" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 861 al. 4 AUSCGIE',
    explication: "L'associé est tenu indéfiniment et solidairement lorsque, « par son immixtion, [il] a laissé croire au cocontractant qu'il entendait s'engager à son égard et dont il est prouvé que l'engagement a tourné à son profit » (art. 861 al. 4). Les deux conditions sont cumulatives.",
  },
  {
    id: 'ch11-q12', question: "Par quels événements la société en participation est-elle dissoute ?",
    options: [
      { id: 'a', texte: "Par ceux qui mettent fin à la SARL" },
      { id: 'b', texte: "Par les mêmes événements que la SNC, sauf clause de continuation" },
      { id: 'c', texte: "Uniquement par décision judiciaire" },
      { id: 'd', texte: "Elle ne peut pas être dissoute" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 862 AUSCGIE',
    explication: "« La société en participation est dissoute par les mêmes événements qui mettent fin à la société en nom collectif », les associés pouvant convenir que la société continue malgré ces événements (art. 862). Le décès d'un associé, par exemple, y met fin sauf clause contraire (art. 290).",
  },
  {
    id: 'ch11-q13', question: "Comment un associé peut-il mettre fin à une société en participation à durée indéterminée ?",
    options: [
      { id: 'a', texte: "Il ne le peut pas" },
      { id: 'b', texte: "Par une notification à tous les associés, de bonne foi et non faite à contretemps" },
      { id: 'c', texte: "Par une assignation en justice" },
      { id: 'd', texte: "Par une publication au journal officiel" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 863 AUSCGIE',
    explication: "La dissolution d'une société en participation à durée indéterminée « peut résulter à tout moment d'une notification […] adressée par l'un d'eux à tous les associés, pourvu que cette notification soit de bonne foi et non faite à contretemps » (art. 863). On ne peut quitter la veille de la livraison d'un marché commun.",
  },
  {
    id: 'ch11-q14', question: "Une société régulièrement constituée par écrit mais que les associés n'ont pas voulu immatriculer est :",
    options: [
      { id: 'a', texte: "Une société créée de fait" },
      { id: 'b', texte: "Une société en participation" },
      { id: 'c', texte: "Une SNC" },
      { id: 'd', texte: "Nulle" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 114 AUSCGIE',
    explication: "« Par exception […], les associés peuvent convenir que la société n'est pas immatriculée. La société est dénommée alors “société en participation”. Elle n'a pas la personnalité juridique » (art. 114). C'est l'accord des associés sur la non-immatriculation qui caractérise la participation.",
  },
  {
    id: 'ch11-q15', question: "Le contrat de société n'a pas été établi par écrit et la société ne peut donc être immatriculée. Quel régime s'applique ?",
    options: [
      { id: 'a', texte: "Celui de la SARL" },
      { id: 'b', texte: "Celui de la société créée de fait et de la société de fait (art. 864 et s.)" },
      { id: 'c', texte: "Celui du GIE" },
      { id: 'd', texte: "Aucun, la société n'existe pas" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 115 AUSCGIE',
    explication: "Si le contrat de société n'est pas établi par écrit et que, de ce fait, la société ne peut être immatriculée, « une telle société n'a pas la personnalité juridique. Elle est régie par les dispositions des articles 864 et suivants » (art. 115).",
  },
  {
    id: 'ch11-q16', question: "Quand y a-t-il société créée de fait ?",
    options: [
      { id: 'a', texte: "Lorsque des personnes ont constitué une SARL non immatriculée" },
      { id: 'b', texte: "Lorsque deux ou plusieurs personnes se comportent comme des associés sans avoir constitué entre elles l'une des sociétés reconnues par l'Acte uniforme" },
      { id: 'c', texte: "Lorsque la société est annulée" },
      { id: 'd', texte: "Lorsque le gérant n'est pas associé" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 864 AUSCGIE',
    explication: "« Il y a société créée de fait lorsque deux (2) ou plusieurs personnes physiques ou morales se comportent comme des associés sans avoir constitué entre elles l'une des sociétés reconnues par le présent Acte uniforme » (art. 864). Les intéressés n'ont souvent même pas conscience d'être associés.",
  },
  {
    id: 'ch11-q17', question: "Quand y a-t-il société de fait ?",
    options: [
      { id: 'a', texte: "Lorsque des personnes se comportent comme des associés sans rien constituer" },
      { id: 'b', texte: "Lorsque des personnes ont constitué une société reconnue comportant un vice de formation non régularisé, ou une société non reconnue par l'Acte uniforme" },
      { id: 'c', texte: "Lorsque la société est en liquidation" },
      { id: 'd', texte: "Lorsque la société a un associé unique" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 865 AUSCGIE',
    explication: "Il y a société de fait lorsque deux ou plusieurs personnes « ont constitué entre elles une société reconnue par le présent Acte uniforme mais qui comporte un vice de formation non régularisé ou ont constitué entre elles une société non reconnue par le présent Acte uniforme » (art. 865). Ici, il y a eu volonté de créer une société, mais la constitution est défaillante.",
  },
  {
    id: 'ch11-q18', question: "Qui peut demander au juge de reconnaître une société créée de fait ?",
    options: [
      { id: 'a', texte: "Seulement les associés" },
      { id: 'b', texte: "Tout intéressé, à charge d'établir l'identité ou la dénomination des personnes concernées" },
      { id: 'c', texte: "Seulement le ministère public" },
      { id: 'd', texte: "Seulement le fisc" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 866 AUSCGIE',
    explication: "« Tout intéressé peut demander à la juridiction compétente la reconnaissance de la société créée de fait entre deux (2) ou plusieurs personnes dont il lui appartient d'apporter l'identité ou la dénomination sociale » (art. 866) : un associé qui veut sa part, un créancier qui veut poursuivre tous les associés, les héritiers d'un associé décédé.",
  },
  {
    id: 'ch11-q19', question: "Comment se prouve l'existence d'une société créée de fait ou d'une société de fait ?",
    options: [
      { id: 'a', texte: "Par un écrit signé de tous" },
      { id: 'b', texte: "Par tout moyen" },
      { id: 'c', texte: "Par une inscription au RCCM" },
      { id: 'd', texte: "Par un acte notarié" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 867 AUSCGIE',
    explication: "« L'existence d'une société créée de fait ou d'une société de fait est prouvée par tout moyen » (art. 867) : comptes bancaires communs, factures au nom des deux intéressés, témoignages, partage régulier des bénéfices.",
  },
  {
    id: 'ch11-q20', question: "Quelles règles s'appliquent aux associés d'une société créée de fait reconnue par le juge ?",
    options: [
      { id: 'a', texte: "Celles de la SARL" },
      { id: 'b', texte: "Celles de la société en nom collectif" },
      { id: 'c', texte: "Celles de la SA" },
      { id: 'd', texte: "Celles de l'indivision" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 868 AUSCGIE',
    explication: "« Lorsque l'existence d'une société créée de fait ou d'une société de fait est reconnue par le juge, les règles de la société en nom collectif sont applicables aux associés » (art. 868) : ils répondent notamment indéfiniment et solidairement des dettes sociales (art. 270).",
  },
  {
    id: 'ch11-q21', question: "Quels éléments caractérisent la volonté de se comporter comme des associés ?",
    options: [
      { id: 'a', texte: "La simple cohabitation" },
      { id: 'b', texte: "Des apports, la participation aux bénéfices et aux pertes et l'intention de collaborer sur un pied d'égalité" },
      { id: 'c', texte: "Le fait d'être parents" },
      { id: 'd', texte: "La signature d'un bail commun" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 4 et 864 AUSCGIE',
    explication: "Se comporter comme des associés (art. 864), c'est réunir les éléments du contrat de société : affecter des biens ou son industrie à une activité commune, dans le but de partager le bénéfice ou de profiter de l'économie qui peut en résulter, et contribuer aux pertes (art. 4). S'y ajoute la volonté de collaborer à l'entreprise commune, que le juge déduit des faits.",
  },
  {
    id: 'ch11-q22', question: "Deux sœurs exploitent ensemble depuis dix ans une boutique à Kinshasa, avec une caisse commune, partagent les bénéfices et achètent ensemble le stock, sans jamais avoir rédigé de statuts. Qu'en est-il ?",
    options: [
      { id: 'a', texte: "Il n'y a aucune société" },
      { id: 'b', texte: "Une société créée de fait peut être reconnue, soumise aux règles de la SNC" },
      { id: 'c', texte: "Une SARL de plein droit" },
      { id: 'd', texte: "Un GIE" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 864, 867 et 868 AUSCGIE',
    explication: "Les deux sœurs se comportent comme des associées sans avoir constitué une société reconnue : c'est une société créée de fait (art. 864), dont l'existence se prouve par tout moyen (art. 867) et dont la reconnaissance entraîne l'application des règles de la SNC (art. 868).",
  },
  {
    id: 'ch11-q23', question: "Trois amis ont signé les statuts d'une SARL mais n'ont jamais déposé le capital ni fait immatriculer la société, tout en exploitant l'activité. Quelle qualification ?",
    options: [
      { id: 'a', texte: "Une SARL régulière" },
      { id: 'b', texte: "Une société de fait, pour vice de formation non régularisé" },
      { id: 'c', texte: "Une société en participation" },
      { id: 'd', texte: "Aucune société" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 865 AUSCGIE',
    explication: "Ils ont voulu constituer une société reconnue (une SARL), mais la constitution comporte un vice de formation non régularisé : c'est une société de fait (art. 865). Ce n'est pas une société en participation, qui suppose un accord des associés pour ne pas immatriculer la société (art. 114, 854).",
  },
  {
    id: 'ch11-q24', question: "Le créancier d'une société créée de fait peut-il poursuivre chacun des associés pour la totalité de sa créance ?",
    options: [
      { id: 'a', texte: "Non, seulement l'associé qui a contracté" },
      { id: 'b', texte: "Oui, une fois la société reconnue, les associés sont tenus comme des associés de SNC, indéfiniment et solidairement" },
      { id: 'c', texte: "Non, seulement pour leur part" },
      { id: 'd', texte: "Seulement s'ils sont commerçants" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 868 et 270 AUSCGIE',
    explication: "La reconnaissance judiciaire entraîne l'application des règles de la SNC (art. 868), dont les associés « répondent indéfiniment et solidairement des dettes sociales » (art. 270). C'est souvent l'intérêt principal pour le créancier qui demande la reconnaissance.",
  },
  {
    id: 'ch11-q25', question: "Une SARL annulée pour défaut de signature d'un associé, après trois ans d'activité, est traitée comment pour le passé ?",
    options: [
      { id: 'a', texte: "Comme si rien n'avait existé" },
      { id: 'b', texte: "La nullité joue sans rétroactivité : la société a existé en fait et doit être liquidée" },
      { id: 'c', texte: "Elle devient une société en participation" },
      { id: 'd', texte: "Elle devient un GIE" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 253 et 865 AUSCGIE',
    explication: "La nullité de la société « met fin, sans rétroactivité, à l'exécution du contrat » et entraîne sa dissolution et sa liquidation (art. 253). Pour la période antérieure, la société a fonctionné comme une société de fait (art. 865), et ses rapports passés sont liquidés comme ceux d'une société.",
  },
  {
    id: 'ch11-q26', question: "En RDC, comment la société en participation est-elle traitée au regard de l'IS ?",
    options: [
      { id: 'a', texte: "Elle est soumise à l'IS de plein droit" },
      { id: 'b', texte: "Elle n'est soumise à l'IS que sur option, irrévocable" },
      { id: 'c', texte: "Elle est exonérée d'office" },
      { id: 'd', texte: "Elle paie un impôt forfaitaire" },
    ],
    reponseCorrecte: 'b', articleRef: 'Loi n° 23/053, art. 4',
    explication: "Les sociétés en nom collectif, en commandite simple et en participation ne sont soumises à l'IS que sur option irrévocable, levée en assemblée et notifiée dans les trois mois du début de l'exercice (loi n° 23/053, art. 4). À défaut, les bénéfices sont imposés entre les mains des associés.",
  },
  {
    id: 'ch11-q27', question: "Et les sociétés de fait et créées de fait ?",
    options: [
      { id: 'a', texte: "Elles échappent à l'impôt faute d'immatriculation" },
      { id: 'b', texte: "Elles entrent dans le champ de l'IS en raison de leur activité" },
      { id: 'c', texte: "Elles sont imposées à la TVA seulement" },
      { id: 'd', texte: "Elles ne peuvent être imposées qu'après reconnaissance judiciaire" },
    ],
    reponseCorrecte: 'b', articleRef: 'Loi n° 23/053 (champ de l\'IS)',
    explication: "La loi n° 23/053 range les sociétés de fait et créées de fait, ainsi que les associations momentanées, parmi les entités soumises à l'IS en raison de leur activité. L'absence d'immatriculation n'est donc pas un moyen d'échapper à l'impôt.",
  },
  {
    id: 'ch11-q28', question: "Quelle forme conviendrait à trois entreprises de BTP qui s'associent pour réaliser un seul chantier routier en ne voulant pas créer de personne morale ?",
    options: [
      { id: 'a', texte: "Une SA" },
      { id: 'b', texte: "Une société en participation, ou une association momentanée organisée par contrat" },
      { id: 'c', texte: "Une SNC obligatoirement" },
      { id: 'd', texte: "Un GIE obligatoirement" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 854 et 855 AUSCGIE',
    explication: "La société en participation, sans personnalité ni publicité, dont les associés organisent librement l'objet, la durée et le fonctionnement (art. 854, 855), est l'outil adapté aux opérations ponctuelles comme un chantier. Le GIE, qui a la personnalité morale, serait plus lourd et suppose une activité auxiliaire.",
  },
  {
    id: 'ch11-q29', question: "Les associés d'une société en participation peuvent-ils écarter les règles impératives communes à toutes les sociétés ?",
    options: [
      { id: 'a', texte: "Oui, toutes" },
      { id: 'b', texte: "Non, sauf celles relatives à la personnalité morale" },
      { id: 'c', texte: "Oui, avec l'accord du juge" },
      { id: 'd', texte: "Oui, s'ils sont moins de cinq" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 855 AUSCGIE',
    explication: "Leur liberté s'exerce « sous réserve de ne pas déroger aux règles impératives des dispositions communes aux sociétés, exception faite de celles qui sont relatives à la personnalité morale » (art. 855). La prohibition des clauses léonines (art. 54), par exemple, s'applique.",
  },
  {
    id: 'ch11-q30', question: "Quelle différence essentielle entre la société en participation et la société créée de fait ?",
    options: [
      { id: 'a', texte: "Aucune" },
      { id: 'b', texte: "Dans la première, l'absence de personnalité est voulue et organisée ; dans la seconde, les intéressés se comportent comme des associés sans avoir constitué de société" },
      { id: 'c', texte: "La première est immatriculée" },
      { id: 'd', texte: "La seconde a la personnalité morale" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 854 et 864 AUSCGIE',
    explication: "Les deux n'ont pas de personnalité morale, mais la société en participation résulte d'un choix des associés de ne pas immatriculer (art. 854), alors que la société créée de fait naît d'un comportement d'associés sans constitution d'une société reconnue (art. 864). La première est régie d'abord par la convention des associés (art. 855), la seconde par les règles de la SNC une fois reconnue (art. 868).",
  },
]
const SECTIONS: Chapitre['sections'] = [
  {
    numero: '11.1',
    titre: "Les sociétés sans personnalité morale : une vue d'ensemble",
    navLabel: '11.1 Vue d\'ensemble',
    blocs: [
      { type: 'paragraphe', texte: "Tout au long de ce module, la société a été présentée comme une personne morale, née de son immatriculation au RCCM, dotée d'un patrimoine propre, d'organes et d'un nom. Mais le contrat de société peut exister sans que cette personne morale apparaisse. L'Acte uniforme connaît trois situations de ce type, qui ont en commun l'absence de personnalité juridique et se distinguent par leur origine : la **société en participation**, dont les associés ont **voulu** qu'elle ne soit pas immatriculée ; la **société créée de fait**, où des personnes se **comportent** comme des associés sans avoir constitué de société ; la **société de fait**, où les intéressés ont voulu constituer une société mais dont la **constitution a échoué** en raison d'un vice non régularisé ou parce qu'ils ont choisi une forme que l'Acte uniforme ne reconnaît pas." },
      { type: 'paragraphe', texte: "Ces situations sont loin d'être marginales en RDC. Une part considérable de l'activité économique se déroule dans l'informel : commerces tenus en famille, ateliers exploités par des frères, transporteurs qui mettent en commun leurs véhicules, associations de fait entre commerçants pour importer des marchandises. Dans le secteur formel, les entreprises utilisent aussi des structures sans personnalité morale pour des opérations ponctuelles : consortiums pour répondre à un appel d'offres, groupements d'entreprises pour un chantier, partenariats miniers organisés par contrat. Le droit doit dire, dans chacun de ces cas, qui est propriétaire des biens, qui répond des dettes, comment se partagent les bénéfices et comment se termine la collaboration. C'est l'objet des art. 854 à 868." },
      { type: 'filet', titre: "Articles 114 et 115 AUSCGIE", texte: "« Par exception aux dispositions qui précèdent, les associés peuvent convenir que la société n'est pas immatriculée. La société est dénommée alors « société en participation ». Elle n'a pas la personnalité juridique. […] » — « Si, contrairement aux dispositions du présent Acte uniforme, le contrat de société ou, le cas échéant, l'acte unilatéral de volonté n'est pas établi par écrit et que, de ce fait, la société ne peut être immatriculée, une telle société n'a pas la personnalité juridique. Elle est régie par les dispositions des articles 864 et suivants ci-après. »" },
      { type: 'carte', titre: "Trois sociétés sans personnalité morale", tableau: { entetes: ['Critère', 'Société en participation', 'Société créée de fait', 'Société de fait'], lignes: [
        ["Origine", "Accord des associés pour ne pas immatriculer", "Comportement d'associés sans constitution de société", "Constitution voulue mais viciée, ou forme non reconnue"],
        ["Textes", "Art. 114, 854 à 863", "Art. 864, 866 à 868", "Art. 115, 865 à 868"],
        ["Preuve", "Par tous moyens (art. 854)", "Par tout moyen (art. 867)", "Par tout moyen (art. 867)"],
        ["Régime entre associés", "Convention, à défaut règles de la SNC (art. 855, 856)", "Règles de la SNC après reconnaissance (art. 868)", "Règles de la SNC après reconnaissance (art. 868)"],
        ["Rapports avec les tiers", "Chaque associé est seul engagé, sauf action en qualité d'associé ou immixtion (art. 861)", "Associés tenus comme en SNC : indéfiniment et solidairement", "Associés tenus comme en SNC : indéfiniment et solidairement"],
        ["IS en RDC", "Sur option irrévocable (loi n° 23/053, art. 4)", "En raison de l'activité", "En raison de l'activité"],
      ] } },
      { type: 'paragraphe', texte: "Pourquoi le droit reconnaît-il des sociétés qui n'ont pas accompli les formalités de constitution ? Parce que le contrat de société existe indépendamment de la personne morale. Lorsque des personnes mettent en commun des biens et leur travail pour partager des bénéfices, elles créent entre elles des droits et des obligations réciproques, et elles traitent avec des tiers qui ont besoin de savoir à qui s'adresser. Si le droit ignorait ces situations, l'associé qui a apporté des fonds à un partenaire indélicat n'aurait aucun recours, les héritiers d'un associé décédé seraient privés de leur part, et les créanciers ne pourraient poursuivre que la personne qui a signé. L'Acte uniforme adopte donc une position équilibrée : il reconnaît l'existence de ces sociétés et organise leurs rapports, mais il ne leur accorde pas les avantages de la personnalité morale et de la responsabilité limitée, qui restent réservés aux sociétés régulièrement constituées et immatriculées." },
      { type: 'controle', question: QCM[13] },
      { type: 'controle', question: QCM[14] },
    ],
  },
  {
    numero: '11.2',
    titre: "La société en participation : notion, formation et usages",
    navLabel: '11.2 Société en participation',
    blocs: [
      { type: 'filet', titre: "Article 854 AUSCGIE", texte: "« La société en participation est celle dans laquelle les associés conviennent qu'elle n'est pas immatriculée au registre du commerce et du crédit mobilier. Elle n'a pas la personnalité morale et n'est pas soumise à publicité. L'existence de la société en participation peut être prouvée par tous moyens. »" },
      { type: 'paragraphe', texte: "La société en participation est une **véritable société** au sens de l'art. 4 : des personnes conviennent d'affecter des biens ou leur industrie à une activité commune, pour en partager le bénéfice ou profiter de l'économie qui en résulte, et s'engagent à contribuer aux pertes. Ce qui la distingue est le **choix délibéré de ne pas l'immatriculer**. Ce choix a trois conséquences : la société n'a **pas de personnalité morale**, donc pas de patrimoine propre, pas de dénomination opposable, pas de capacité d'ester en justice ; elle n'est **soumise à aucune publicité**, ce qui lui permet de rester discrète, voire occulte ; son existence se **prouve par tous moyens**, puisqu'aucun registre ne l'atteste." },
      { type: 'paragraphe', texte: "La société en participation est une structure d'une grande **souplesse**. « Les associés conviennent librement de l'objet, de la durée, des conditions du fonctionnement, des droits des associés, de la fin de la société en participation sous réserve de ne pas déroger aux règles impératives des dispositions communes aux sociétés, exception faite de celles qui sont relatives à la personnalité morale » (art. 855). Les associés peuvent donc organiser la gestion, la répartition des résultats et la sortie comme ils l'entendent, à condition de respecter les règles fondamentales du contrat de société, comme la prohibition des clauses léonines (art. 54). Un **écrit**, sans être obligatoire, est vivement recommandé : il fixe la contribution de chacun, les pouvoirs du gérant, la clé de répartition des résultats et les conditions de retrait, et il sert de preuve en cas de litige." },
      { type: 'paragraphe', texte: "Ses **usages** sont nombreux. Les entreprises l'utilisent pour des **opérations ponctuelles** : plusieurs entreprises de BTP répondant ensemble à un appel d'offres public et réalisant un chantier, deux importateurs partageant un conteneur de marchandises, un investisseur finançant discrètement l'activité d'un commerçant en échange d'une part des bénéfices. Elle est aussi utilisée pour des **partenariats durables** où les parties ne souhaitent pas créer de personne morale, par exemple lorsque chacune veut rester propriétaire des biens qu'elle apporte, ou pour préserver la confidentialité de la collaboration. Dans les grands projets, elle prend souvent la forme d'un contrat de consortium ou d'association momentanée, qui organise la répartition des travaux, des risques et des résultats entre les membres." },
      { type: 'paragraphe', texte: "Il ne faut pas confondre la société en participation avec d'autres figures. La **société en formation**, qui a vocation à être immatriculée et dont les actes sont repris par la société une fois immatriculée (chapitre 1), n'est pas une société en participation : l'absence d'immatriculation n'y est que provisoire. La **société de fait**, dont l'absence d'immatriculation résulte d'un vice, n'est pas non plus une participation : dans la participation, l'absence d'immatriculation est **voulue** et convenue. Enfin, le **GIE** (chapitre 6) a la personnalité morale et suppose une activité auxiliaire de celle des membres, alors que la société en participation n'a pas de personnalité et peut avoir n'importe quel objet licite." },
      { type: 'paragraphe', texte: "Le contrat de société en participation, lorsqu'il est écrit, doit être rédigé avec le même soin que des statuts. Il identifie les associés et précise l'objet de la collaboration, sa durée ou l'opération à laquelle elle est attachée. Il décrit les apports de chacun et leur statut : biens restant la propriété de l'apporteur et simplement mis à disposition (art. 857), biens mis en indivision, ou biens dont l'un des associés sera propriétaire à l'égard des tiers (art. 858). Il désigne le ou les gérants et fixe leurs pouvoirs, les décisions réservées à l'ensemble des associés et les majorités applicables, faute de quoi les règles de la SNC s'appliquent (art. 856). Il fixe la clé de répartition des résultats et la contribution aux pertes, dans le respect de la prohibition des clauses léonines (art. 54). Il organise la tenue des comptes de l'opération, l'information des associés, les conditions d'entrée et de retrait, la continuation en cas de décès ou de défaillance d'un associé (art. 862), et les modalités de liquidation. Un tel contrat évite la plupart des litiges." },
      { type: 'controle', question: QCM[0] },
      { type: 'controle', question: QCM[1] },
      { type: 'controle', question: QCM[2] },
      { type: 'controle', question: QCM[27] },
      { type: 'controle', question: QCM[28] },
    ],
  },
  {
    numero: '11.3',
    titre: "Les rapports entre associés de la société en participation",
    navLabel: '11.3 Rapports entre associés',
    blocs: [
      { type: 'paragraphe', texte: "« À moins qu'une organisation différente n'ait été prévue, les rapports entre associés sont régis par les dispositions applicables aux sociétés en nom collectif » (art. 856). Ce renvoi supplétif au régime de la SNC, étudié au chapitre 3, a des conséquences importantes lorsque les associés n'ont rien prévu : à défaut de clause, tous les associés sont gérants (art. 276) ; les décisions excédant les pouvoirs des gérants sont prises à l'unanimité (art. 283) ; la cession de la qualité d'associé exige l'accord de tous (art. 274) ; les résultats se répartissent à proportion des apports (art. 54). Un contrat bien rédigé permet d'écarter ces règles, par exemple en désignant un gérant unique, en fixant une clé de répartition des résultats différente ou en organisant le retrait d'un associé." },
      { type: 'paragraphe', texte: "La question des **biens** est la plus délicate, puisque la société n'a pas de patrimoine. Le principe est que « les biens nécessaires à l'activité sociale sont mis à la disposition du gérant de la société », mais que « chaque associé reste propriétaire des biens qu'il met à la disposition de la société » (art. 857). L'associé qui apporte un camion à une participation en reste propriétaire ; à la fin de la société, il le reprend. Ses créanciers personnels peuvent d'ailleurs le saisir, puisqu'il fait toujours partie de son patrimoine : c'est une fragilité de la participation, que les associés doivent mesurer." },
      { type: 'paragraphe', texte: "Les associés peuvent toutefois organiser autrement la propriété des biens. Ils peuvent convenir de mettre certains biens en **indivision**, ou décider que l'un des associés, souvent le gérant, est, **à l'égard des tiers, propriétaire** de tout ou partie des biens qu'il acquiert pour la réalisation de l'objet social (art. 858). Sont en outre **réputés indivis** les biens acquis avec des deniers indivis pendant la durée de la société, ceux qui étaient indivis avant d'être mis à disposition, et ceux que les associés ont convenu de mettre en indivision (art. 859). Pour protéger l'activité commune, aucun associé ne peut demander le **partage** des biens indivis tant que la société n'est pas dissoute, sauf clause contraire (art. 860)." },
      { type: 'carte', titre: "Exemple : la participation MATADI IMPORT", texte: "Trois commerçants de Matadi, A, B et C, conviennent par écrit d'importer ensemble des matériaux de construction, sans créer de société. A apporte son entrepôt, B un camion, C 50 000 000 FC de trésorerie. A est désigné gérant et achète les marchandises en son nom. Les bénéfices sont partagés 40 % A, 30 % B, 30 % C.", liste: [
        "A et B restent propriétaires de l'entrepôt et du camion, mis à disposition du gérant (art. 857).",
        "Les marchandises achetées avec les 50 000 000 FC mis en commun sont réputées indivises (art. 859), sauf convention désignant A comme propriétaire à l'égard des tiers (art. 858).",
        "Aucun ne peut exiger le partage des marchandises indivises avant la dissolution, sauf clause contraire (art. 860).",
        "Les rapports internes (gestion, décisions, répartition) suivent le contrat et, pour ce qu'il ne règle pas, les règles de la SNC (art. 855, 856).",
      ] },
      { type: 'paragraphe', texte: "Le **gérant** de la participation joue un rôle central. C'est lui qui détient les biens mis à disposition (art. 857), qui contracte avec les tiers et qui, en l'absence de personnalité morale, s'engage personnellement envers eux (art. 861 al. 1). Il doit donc tenir une comptabilité distincte de l'opération commune, permettant de retracer les apports, les dépenses, les recettes et le résultat à partager. À la fin de chaque période convenue, il rend compte aux autres associés et leur verse leur quote-part des bénéfices, ou leur demande leur contribution aux pertes. Dans ses propres comptes, chaque associé enregistre sa quote-part du résultat de l'opération commune. Ces comptes de l'opération sont aussi la meilleure preuve de l'existence et du contenu de la société en cas de litige, puisque la participation n'est inscrite dans aucun registre." },
      { type: 'controle', question: QCM[3] },
      { type: 'controle', question: QCM[4] },
      { type: 'paragraphe', texte: "Un exemple chiffré illustre la répartition des résultats. Reprenons la participation MATADI IMPORT. Au terme de l'opération, les marchandises ont été vendues 180 000 000 FC ; elles avaient coûté 120 000 000 FC, et les frais de transport, de dédouanement et de stockage se sont élevés à 20 000 000 FC. Le bénéfice de l'opération est donc de 40 000 000 FC. Selon la clé convenue, A reçoit 16 000 000 FC (40 %), B et C 12 000 000 FC chacun (30 %). C récupère en outre sa mise de 50 000 000 FC, qui avait été mise en commun pour l'achat des marchandises et se retrouve dans le produit des ventes ; A et B reprennent l'entrepôt et le camion qu'ils avaient seulement mis à disposition. Si l'opération avait dégagé une perte de 10 000 000 FC, chacun l'aurait supportée selon la même clé, sauf clause différente. Le gérant A, qui a contracté avec les fournisseurs, reste seul tenu envers eux, mais peut se faire rembourser par B et C leur part des dettes de l'opération." },
      { type: 'controle', question: QCM[5] },
      { type: 'controle', question: QCM[6] },
      { type: 'controle', question: QCM[7] },
    ],
  },
  {
    numero: '11.4',
    titre: "Les rapports de la société en participation avec les tiers",
    navLabel: '11.4 Rapports avec les tiers',
    blocs: [
      { type: 'filet', titre: "Article 861 AUSCGIE", texte: "« Chaque associé contracte en son nom personnel et est seul engagé à l'égard des tiers. Toutefois, si les associés agissent expressément en leur qualité d'associé auprès des tiers, chacun de ceux qui ont agi est tenu par les engagements des autres. Les obligations souscrites dans ces conditions les engagent indéfiniment et solidairement. Il en est de même de l'associé qui, par son immixtion, a laissé croire au cocontractant qu'il entendait s'engager à son égard et dont il est prouvé que l'engagement a tourné à son profit. »" },
      { type: 'paragraphe', texte: "Le **principe** est celui de la **relativité** : chaque associé contracte en son nom personnel et est seul engagé envers les tiers (art. 861 al. 1). Le fournisseur qui a vendu des marchandises au gérant d'une participation n'a d'action que contre lui ; il ignore généralement l'existence de la société, et il ne peut pas se retourner contre les autres associés. C'est la logique de la société **occulte** : la participation n'existe qu'entre ses membres. Dans leurs rapports internes, en revanche, l'associé qui a contracté pour les besoins de l'activité commune pourra répartir la charge entre tous, selon le contrat ou les règles de la SNC." },
      { type: 'paragraphe', texte: "Deux **exceptions** renforcent la protection des tiers. La première concerne la société **ostensible** : si les associés agissent expressément en leur qualité d'associés auprès des tiers, chacun de ceux qui ont agi est tenu des engagements des autres, et les obligations ainsi souscrites les engagent **indéfiniment et solidairement** (art. 861 al. 2 et 3). Les entreprises qui se présentent ensemble à un maître d'ouvrage comme membres d'un consortium, en signant ensemble l'offre, s'exposent ainsi à répondre chacune de la totalité des engagements. La seconde concerne l'**immixtion** : l'associé qui, par son comportement, a laissé croire au cocontractant qu'il s'engageait, est tenu de la même manière s'il est prouvé que l'engagement **a tourné à son profit** (art. 861 al. 4). Les deux conditions sont cumulatives : l'apparence créée et le profit retiré." },
      { type: 'paragraphe', texte: "Ces règles ont des conséquences pratiques importantes pour les **consortiums** et **associations momentanées** fréquents dans les marchés publics et les grands projets en RDC. Lorsque les membres signent ensemble le contrat avec le maître d'ouvrage en leur qualité de membres du groupement, ils répondent solidairement de son exécution envers lui, quelle que soit la répartition des travaux convenue entre eux. Il est donc essentiel de rédiger soigneusement l'accord de consortium : répartition des tâches, contributions, garanties croisées, recours entre membres en cas de défaillance de l'un d'eux. L'expert-comptable intervient pour organiser la comptabilité de l'opération commune, déterminer la part de résultat revenant à chaque membre et l'enregistrer dans ses propres comptes." },
      { type: 'paragraphe', texte: "On distingue ainsi traditionnellement la société en participation **occulte**, dont l'existence n'est pas révélée aux tiers et qui fonctionne selon le principe de l'art. 861 al. 1, et la société en participation **ostensible**, dont les associés se présentent comme tels aux tiers et qui fonctionne, envers eux, comme une SNC : chaque associé qui a agi en cette qualité est tenu indéfiniment et solidairement des engagements des autres. Le choix entre ces deux modes de fonctionnement n'est pas neutre. L'occultation protège les associés non contractants, mais elle prive la collaboration de la confiance que les tiers accorderaient à un groupement plus solide ; l'ostensibilité rassure les partenaires, par exemple un maître d'ouvrage qui veut pouvoir s'adresser à chacun des membres du consortium, mais expose chaque associé à la totalité des engagements. Il appartient aux associés de choisir en connaissance de cause et d'organiser en conséquence leurs garanties réciproques." },
      { type: 'controle', question: QCM[8] },
      { type: 'paragraphe', texte: "L'**immixtion** mérite un exemple. Dans une participation occulte entre un commerçant et un investisseur, l'investisseur prend l'habitude d'accompagner le commerçant chez un grossiste, participe aux négociations, choisit les marchandises et se présente comme « le partenaire » du commerçant. Le grossiste accorde un crédit important, convaincu que l'investisseur, réputé fortuné, garantit l'opération. Si le commerçant ne paie pas, le grossiste peut poursuivre l'investisseur pour la totalité de la dette, à condition de prouver deux choses : que l'investisseur, par son comportement, lui a laissé croire qu'il entendait s'engager, et que l'engagement a tourné à son profit, par exemple parce que les marchandises ainsi acquises ont servi l'activité commune dont il partage les bénéfices (art. 861 al. 4). L'investisseur qui veut rester à l'abri doit donc s'abstenir de toute intervention dans les relations avec les tiers." },
      { type: 'controle', question: QCM[9] },
      { type: 'controle', question: QCM[10] },
    ],
  },
  {
    numero: '11.5',
    titre: "La fin de la société en participation",
    navLabel: '11.5 Fin de la participation',
    blocs: [
      { type: 'paragraphe', texte: "« La société en participation est dissoute par les mêmes événements qui mettent fin à la société en nom collectif », mais les associés peuvent convenir, dans les statuts ou un acte ultérieur, que la société continue malgré ces événements (art. 862). Elle prend donc fin notamment par l'arrivée du terme, la réalisation de l'objet (l'achèvement du chantier, la vente du dernier lot de marchandises), la décision des associés, et, comme la SNC, par le décès, l'incapacité, la faillite ou l'interdiction d'un associé, sauf clause de continuation (art. 290). Une clause de continuation est donc indispensable si les partenaires veulent que la collaboration survive au décès de l'un d'eux." },
      { type: 'paragraphe', texte: "Lorsque la société est à **durée indéterminée**, chaque associé peut y mettre fin à tout moment par une **notification** adressée à tous les associés, par lettre au porteur ou recommandée, « pourvu que cette notification soit de bonne foi et non faite à contretemps » (art. 863). La règle traduit l'idée qu'on ne peut être lié perpétuellement, mais elle est encadrée : l'associé qui se retire de mauvaise foi, par exemple pour s'approprier une opportunité commune, ou à contretemps, par exemple à la veille de la livraison d'un marché, engage sa responsabilité envers ses coassociés." },
      { type: 'paragraphe', texte: "La dissolution ouvre une phase de **liquidation** des rapports entre associés : chaque associé reprend les biens dont il était resté propriétaire (art. 857) ; les biens indivis sont partagés, ce qui devient possible puisque la société est dissoute (art. 860) ; les comptes entre associés sont établis, en tenant compte des apports, des dépenses engagées par chacun et de la clé de répartition des résultats ; les dettes contractées par un associé pour l'activité commune sont réparties entre tous selon le contrat. Faute de personnalité morale, il n'y a pas de liquidateur au sens des art. 203 et suivants, mais rien n'empêche les associés d'en désigner un par convention." },
      { type: 'paragraphe', texte: "Sur le plan **fiscal**, la société en participation n'est en principe pas imposée en tant que telle en RDC : la loi n° 23/053 la range parmi les sociétés qui ne sont soumises à l'IS que **sur option**, option irrévocable, levée en assemblée et notifiée dans les trois mois du début de l'exercice fiscal (art. 4). À défaut d'option, chaque associé est imposé sur sa part de résultat selon son propre régime (IS pour une société, IRPP pour une personne physique). La loi range en revanche les **associations momentanées** parmi les entités soumises à l'IS en raison de leur activité. Le choix de la structure et, le cas échéant, l'exercice de l'option doivent donc être examinés avec l'expert-comptable dès la conclusion de l'accord." },
      { type: 'controle', question: QCM[11] },
      { type: 'paragraphe', texte: "Un exemple de liquidation d'une participation. Deux transporteurs ont exploité ensemble pendant trois ans une ligne de bus entre Kinshasa et Matadi, dans le cadre d'une société en participation : chacun apportait deux véhicules, dont il restait propriétaire, et les recettes, diminuées des frais communs (carburant, chauffeurs, péages), étaient partagées par moitié. Un fonds de réserve commun, alimenté par une partie des recettes, avait servi à acheter un garage, réputé indivis entre eux (art. 859). L'un des transporteurs notifie, de bonne foi et hors de toute période critique, sa volonté de mettre fin à la société à durée indéterminée (art. 863). La liquidation consiste alors à arrêter les comptes de la période, à répartir le dernier résultat, à permettre à chacun de reprendre ses véhicules (art. 857), et à partager le garage indivis, désormais possible puisque la société est dissoute (art. 860), en nature ou par la vente et le partage du prix. Les dettes encore dues aux fournisseurs, contractées par l'un ou l'autre, sont réparties entre eux selon leur accord." },
      { type: 'controle', question: QCM[12] },
      { type: 'controle', question: QCM[25] },
    ],
  },
  {
    numero: '11.6',
    titre: "La société créée de fait : se comporter comme des associés",
    navLabel: '11.6 Société créée de fait',
    blocs: [
      { type: 'filet', titre: "Article 864 AUSCGIE", texte: "« Il y a société créée de fait lorsque deux (2) ou plusieurs personnes physiques ou morales se comportent comme des associés sans avoir constitué entre elles l'une des sociétés reconnues par le présent Acte uniforme. »" },
      { type: 'paragraphe', texte: "La société créée de fait naît des **comportements**, non d'un acte juridique. Des personnes exploitent ensemble une activité, mettent en commun des moyens, partagent les résultats, sans jamais avoir rédigé de statuts ni songé à constituer une société. Souvent, elles n'ont même pas conscience d'être associées : c'est le juge qui, à l'occasion d'un litige, constatera que leur collaboration réunissait en fait tous les éléments d'un contrat de société. La situation est fréquente entre membres d'une même famille, entre concubins exploitant ensemble un commerce, entre amis qui ont lancé une activité sans formaliser leurs relations." },
      { type: 'paragraphe', texte: "Pour que la société créée de fait soit reconnue, il faut établir que les intéressés se sont comportés « comme des associés », c'est-à-dire que leur relation présente les éléments du contrat de société définis par l'art. 4 : des **apports**, en argent, en biens ou en industrie, affectés à une activité commune ; la **vocation aux bénéfices et aux pertes**, chacun ayant vocation à partager le bénéfice ou à profiter de l'économie qui peut en résulter, et à contribuer aux pertes ; et la **volonté de collaborer** sur un pied d'égalité à l'entreprise commune, que l'on appelle traditionnellement l'*affectio societatis*. Ce dernier élément permet de distinguer la société créée de fait d'autres relations : un salarié collabore à l'entreprise, mais sous l'autorité de l'employeur et sans participer aux pertes ; un prêteur apporte des fonds, mais sans participer à la gestion ni aux pertes ; un conjoint aide son époux commerçant, mais n'est pas nécessairement son associé." },
      { type: 'paragraphe', texte: "La preuve est libre : « l'existence d'une société créée de fait ou d'une société de fait est prouvée par tout moyen » (art. 867). Les indices habituels sont l'existence d'un compte bancaire commun alimenté par les deux intéressés, la signature conjointe de contrats ou de factures, l'achat en commun des biens d'exploitation, le partage régulier des bénéfices, la participation de chacun à la gestion et aux décisions, la contribution de chacun aux dettes de l'exploitation. Aucun de ces indices ne suffit seul ; c'est leur réunion qui emporte la conviction du juge. Il faut aussi établir l'identité ou la dénomination des personnes concernées (art. 866)." },
      { type: 'paragraphe', texte: "La frontière entre société créée de fait et d'autres relations est souvent délicate. Prenons l'exemple d'un commerçant dont le neveu travaille au magasin depuis des années. Si le neveu perçoit un salaire, obéit aux instructions de son oncle et ne supporte jamais les pertes, c'est un salarié, et non un associé. Si, au contraire, il a apporté une partie des fonds, participe aux décisions d'achat et de prix, partage les bénéfices et contribue aux pertes lorsque l'activité est déficitaire, une société créée de fait peut être reconnue. De même, une personne qui a prêté de l'argent à un commerçant contre un intérêt fixe est un prêteur ; si elle reçoit une part des bénéfices et supporte les pertes, elle peut être associée. Enfin, deux personnes propriétaires ensemble d'un immeuble qu'elles louent sont des coïndivisaires, non des associés, tant qu'elles se bornent à gérer leur bien commun sans exploiter une activité économique. Le juge s'attache toujours à la réalité des comportements, non aux mots employés par les parties." },
      { type: 'controle', question: QCM[15] },
      { type: 'paragraphe', texte: "La situation des **époux** qui exploitent ensemble un commerce mérite une attention particulière. L'AUDCG pose en principe que « le conjoint du commerçant n'a la qualité de commerçant que s'il accomplit les actes visés aux articles 3 et 4 ci-dessus, à titre de profession et séparément de ceux de l'autre conjoint » (art. 7 AUDCG). Le conjoint qui aide son époux dans son commerce n'est donc pas, par ce seul fait, commerçant ni associé. Mais si les deux époux ont réuni des apports, participent ensemble aux décisions et partagent les résultats comme de véritables partenaires, une société créée de fait peut être reconnue entre eux, avec les conséquences de l'art. 868. La question se pose souvent au moment d'une séparation ou d'un décès, lorsque l'un des époux, ou ses héritiers, réclame sa part d'une entreprise immatriculée au seul nom de l'autre. Les règles du régime matrimonial, qui relèvent du droit de la famille congolais, interfèrent alors avec celles du droit des sociétés, et l'analyse doit être menée avec prudence." },
      { type: 'controle', question: QCM[20] },
      { type: 'controle', question: QCM[21] },
    ],
  },
  {
    numero: '11.7',
    titre: "La société de fait : une constitution qui a échoué",
    navLabel: '11.7 Société de fait',
    blocs: [
      { type: 'filet', titre: "Article 865 AUSCGIE", texte: "« Lorsque deux (2) ou plusieurs personnes physiques ou morales ont constitué entre elles une société reconnue par le présent Acte uniforme mais qui comporte un vice de formation non régularisé ou ont constitué entre elles une société non reconnue par le présent Acte uniforme, il y a société de fait. »" },
      { type: 'paragraphe', texte: "La société de fait se distingue de la société créée de fait par l'**intention** des intéressés : ils ont **voulu** constituer une société, mais leur tentative a échoué. Deux hypothèses sont visées. La première est celle d'une société d'une forme reconnue (SARL, SA, SNC) dont la constitution comporte un **vice de formation non régularisé** : statuts non signés par tous les associés, capital non libéré ou non déposé, défaut d'immatriculation, contrat non écrit empêchant l'immatriculation (art. 115). La seconde est celle d'une société d'une **forme non reconnue** par l'Acte uniforme, par exemple une forme empruntée à un droit étranger ou une ancienne forme du droit congolais que les associés auraient continué d'utiliser sans la mettre en harmonie." },
      { type: 'paragraphe', texte: "La société de fait se rattache aussi à la théorie des **nullités**, étudiée au chapitre 10. Lorsqu'une société immatriculée est annulée, la nullité « met fin, sans rétroactivité, à l'exécution du contrat » (art. 253) : pour la période antérieure, la société a fonctionné, elle a conclu des contrats, employé des salariés, réalisé des bénéfices ou des pertes. On ne peut effacer cette réalité ; on la traite comme celle d'une société de fait, dont les rapports doivent être liquidés. De même, lorsqu'une société, à la suite de sa transformation, n'a plus l'une des formes prévues par l'Acte uniforme, celui-ci prévoit qu'elle « perd la personnalité juridique si elle exerce une activité commerciale » (art. 188), ce qui la fait basculer dans la catégorie des sociétés de fait." },
      { type: 'paragraphe', texte: "La distinction entre société de fait et société **en participation** est essentielle. Toutes deux sont des sociétés non immatriculées et sans personnalité morale ; mais la société en participation résulte d'un **choix** des associés de ne pas immatriculer, organisé par leur convention (art. 114, 854, 855), alors que la société de fait résulte d'un **échec**. Des associés qui ont signé les statuts d'une SARL avec l'intention de l'immatriculer, mais ne l'ont jamais fait, ne forment pas une société en participation : ils forment une société de fait. La différence se répercute sur le régime : le contrat des associés d'une participation est respecté, alors que les associés d'une société de fait sont soumis, une fois la société reconnue, aux règles de la SNC." },
      { type: 'paragraphe', texte: "L'intérêt pratique de la qualification de société de fait apparaît dans les situations de nullité et de constitution inachevée, fréquentes dans les petites entreprises. Imaginons des associés qui ont rédigé des statuts de SARL, loué un local, acheté du matériel et commencé à travailler en attendant l'immatriculation, qui n'est jamais intervenue faute de dépôt du capital. Pendant cette période, la société en formation n'existe pas juridiquement comme personne morale ; les actes accomplis en son nom engagent ceux qui les ont passés (chapitre 1). Si la situation se prolonge, les associés forment une société de fait, soumise aux règles de la SNC une fois reconnue. Chacun d'eux peut alors être poursuivi pour la totalité des dettes de l'activité. La leçon est simple : la constitution d'une société ne doit pas rester inachevée, et l'activité ne devrait commencer qu'une fois l'immatriculation obtenue, ou, à défaut, avec la conscience claire des risques encourus pendant la période intermédiaire." },
      { type: 'controle', question: QCM[16] },
      { type: 'controle', question: QCM[22] },
      { type: 'controle', question: QCM[24] },
    ],
  },
  {
    numero: '11.8',
    titre: "La reconnaissance judiciaire et le régime applicable",
    navLabel: '11.8 Régime',
    blocs: [
      { type: 'paragraphe', texte: "La société créée de fait ou de fait n'existe juridiquement qu'à partir du moment où son existence est **établie**, généralement par le juge. « Tout intéressé peut demander à la juridiction compétente la reconnaissance de la société créée de fait entre deux (2) ou plusieurs personnes dont il lui appartient d'apporter l'identité ou la dénomination sociale » (art. 866). Les demandeurs sont variés : un **associé** qui veut obtenir sa part des bénéfices ou de l'actif lors de la rupture de la collaboration ; les **héritiers** d'un associé décédé, qui revendiquent la part de leur auteur dans une entreprise exploitée à deux ; un **créancier** qui veut pouvoir poursuivre non seulement la personne avec qui il a contracté, mais aussi son associé de fait ; l'**administration fiscale**, qui peut avoir intérêt à qualifier une activité commune." },
      { type: 'filet', titre: "Article 868 AUSCGIE", texte: "« Lorsque l'existence d'une société créée de fait ou d'une société de fait est reconnue par le juge, les règles de la société en nom collectif sont applicables aux associés. »" },
      { type: 'paragraphe', texte: "Le régime applicable est celui de la **SNC** (art. 868), étudié au chapitre 3. Deux conséquences sont particulièrement importantes. **Envers les tiers**, les associés « répondent indéfiniment et solidairement des dettes sociales » (art. 270) : le créancier peut poursuivre chacun d'eux pour la totalité de sa créance, après avoir mis en demeure la société selon les règles de la SNC (art. 271). C'est souvent ce qui motive la demande de reconnaissance par un créancier. **Entre associés**, les règles de la SNC organisent la répartition des bénéfices et des pertes à proportion des apports (art. 54), les décisions collectives et, surtout, la **liquidation** : à la fin de la collaboration, les apports sont repris, les dettes réglées, et le solde partagé." },
      { type: 'paragraphe', texte: "Le renvoi aux règles de la SNC est sévère pour les associés, qui se trouvent exposés à une responsabilité indéfinie qu'ils n'avaient pas choisie. Il se justifie par la **protection des tiers** et par une logique d'incitation : les associés qui veulent limiter leur responsabilité doivent constituer régulièrement une SARL, une SA ou une SAS et l'immatriculer. Il faut d'ailleurs rappeler que, dans la SNC, tous les associés ont la qualité de commerçant (art. 270) : la reconnaissance d'une société créée de fait entre des personnes qui exercent une activité commerciale peut donc emporter des conséquences au regard du statut de commerçant, notamment en matière d'incompatibilités (chapitre 3) et de procédures collectives." },
      { type: 'carte', titre: "Méthode : qualifier une collaboration non formalisée", liste: [
        "Y a-t-il eu un acte constitutif d'une société reconnue ? Si oui et qu'il est vicié ou non immatriculé contre la volonté des associés : société de fait (art. 865, 115).",
        "Les associés ont-ils convenu de ne pas immatriculer leur société ? Si oui : société en participation (art. 114, 854), régie d'abord par leur convention (art. 855).",
        "À défaut d'acte : les intéressés se sont-ils comportés comme des associés (apports, participation aux bénéfices et aux pertes, volonté de collaborer) ? Si oui : société créée de fait (art. 864).",
        "Sinon : simple relation de travail, de prêt, d'indivision ou d'entraide familiale, sans société.",
        "Conséquence d'une reconnaissance : règles de la SNC, responsabilité indéfinie et solidaire envers les tiers (art. 868, 270).",
      ] },
      { type: 'paragraphe', texte: "La reconnaissance d'une société créée de fait intervient souvent au moment de sa **fin**. Lorsque deux partenaires se séparent, l'un d'eux demande au juge de constater qu'ils étaient associés, afin d'obtenir la liquidation de la société et sa part de l'actif ; le juge constate alors à la fois l'existence de la société et sa dissolution, et ordonne sa liquidation selon les règles de la SNC. Cette liquidation suppose de reconstituer, souvent sur de nombreuses années, les apports de chacun, les bénéfices réalisés et répartis, les biens acquis et les dettes contractées. En l'absence de comptabilité, la tâche est difficile : l'expert désigné doit s'appuyer sur les relevés bancaires, les factures, les déclarations fiscales éventuelles et les témoignages. Plus la collaboration a été informelle, plus la liquidation est coûteuse et incertaine : c'est une raison supplémentaire de formaliser dès le départ les relations entre partenaires." },
      { type: 'controle', question: QCM[17] },
      { type: 'controle', question: QCM[18] },
      { type: 'controle', question: QCM[19] },
      { type: 'controle', question: QCM[23] },
    ],
  },
  {
    numero: '11.9',
    titre: "Les sociétés de fait dans l'économie congolaise",
    navLabel: '11.9 Réalités congolaises',
    blocs: [
      { type: 'paragraphe', texte: "L'économie congolaise comporte une part importante d'activités exercées sans structure juridique formalisée. Beaucoup de petites entreprises sont exploitées par plusieurs membres d'une famille, par des associés qui se font confiance et ne voient pas l'intérêt de payer les frais de constitution et d'immatriculation, ou par des commerçants qui craignent les obligations comptables, fiscales et sociales liées à la formalisation. Tant que tout va bien, cette situation ne pose pas de difficulté apparente. Mais elle se révèle dangereuse à trois moments : lorsqu'un conflit survient entre les partenaires, lorsque l'un d'eux décède, et lorsque l'activité s'endette au-delà de ce qu'elle peut rembourser." },
      { type: 'paragraphe', texte: "Au moment du **conflit**, celui qui a apporté des fonds ou son travail sans titre juridique se trouve démuni : il doit prouver l'existence de la société pour obtenir sa part, ce qui suppose de réunir des indices (comptes communs, témoignages, factures) et d'engager une procédure. Au moment du **décès**, les héritiers de l'associé de fait doivent faire reconnaître les droits de leur auteur dans une entreprise qui, juridiquement, peut apparaître comme la propriété de l'associé survivant ; à l'inverse, la SNC prenant fin par le décès d'un associé sauf clause de continuation (art. 290), la reconnaissance peut conduire à la liquidation de l'activité. Au moment de l'**endettement**, les créanciers peuvent obtenir la reconnaissance de la société pour poursuivre tous les associés sur l'ensemble de leurs biens personnels, indéfiniment et solidairement." },
      { type: 'paragraphe', texte: "Sur le plan **fiscal**, l'absence de formalisation ne met pas l'activité hors du champ de l'impôt. La loi n° 23/053 range les **sociétés de fait et créées de fait** parmi les entités soumises à l'IS en raison de leur activité. L'administration peut donc, lors d'un contrôle, qualifier une collaboration de société de fait et l'imposer comme telle, avec les pénalités prévues pour défaut de déclaration. La formalisation de l'activité, par la constitution d'une SARL, d'une SARLU ou d'une SAS, est donc généralement de l'intérêt même des entrepreneurs : elle limite leur responsabilité, clarifie leurs droits respectifs, facilite l'accès au crédit et aux marchés publics, et leur permet de maîtriser leur situation fiscale. Les réformes du guichet unique de création d'entreprise et la liberté du capital de la SARL en RDC, étudiées aux chapitres 1 et 5, vont dans ce sens." },
      { type: 'paragraphe', texte: "L'expert-comptable joue ici un rôle de premier plan. Lorsqu'il est consulté par un entrepreneur qui travaille avec un parent ou un ami, il doit identifier le risque de société créée de fait, expliquer ses conséquences et proposer une formalisation adaptée : constitution d'une société en bonne et due forme, rédaction d'un pacte d'associés, ou, si les partenaires tiennent à rester sans personne morale, rédaction d'un contrat de société en participation qui organise précisément les apports, la gestion, le partage des résultats, la propriété des biens et la sortie. Lorsqu'il est désigné comme expert dans un litige, il reconstitue les flux financiers et les apports de chacun, afin de permettre au juge de déterminer la part revenant à chaque associé." },
      { type: 'paragraphe', texte: "La formalisation est aujourd'hui plus accessible qu'autrefois. La RDC a créé un guichet unique de création d'entreprise, qui centralise les formalités d'immatriculation, et a supprimé le capital minimum de la SARL, désormais librement fixé en tenant compte de l'objet social (chapitres 1 et 5). La SARL unipersonnelle et la SAS unipersonnelle permettent à un entrepreneur seul de séparer son patrimoine personnel de son activité. Pour des partenaires qui veulent travailler ensemble, la SARL offre un cadre simple, avec une responsabilité limitée et des règles de gouvernance éprouvées ; la SAS offre une grande liberté d'organisation. Ces outils ne suppriment pas les coûts de la formalisation (comptabilité, déclarations fiscales et sociales, dépôt des comptes), mais ils apportent une sécurité juridique que la société de fait ne donnera jamais. Le rôle de l'expert-comptable est d'en présenter honnêtement les avantages et les contraintes, et d'accompagner l'entrepreneur dans le choix." },
      { type: 'controle', question: QCM[26] },
    ],
  },
  {
    numero: '11.10',
    titre: "Synthèse : la société, de la forme au fait",
    navLabel: '11.10 Synthèse',
    blocs: [
      { type: 'paragraphe', texte: "Ce dernier chapitre montre que le droit des sociétés ne s'arrête pas aux formes immatriculées. Là où des personnes mettent en commun des moyens pour partager les résultats d'une activité, il y a société, avec ou sans personnalité morale. L'Acte uniforme en tire trois régimes : la **société en participation**, forme volontaire et souple, qui repose sur la convention des associés et protège le secret de la collaboration, mais expose l'associé qui se présente comme tel ou s'immisce à une responsabilité indéfinie et solidaire ; la **société créée de fait**, qui saisit des comportements d'associés dans une situation non formalisée ; la **société de fait**, qui recueille les sociétés dont la constitution a échoué. Dans ces deux derniers cas, une fois l'existence de la société reconnue, les règles de la SNC s'appliquent." },
      { type: 'paragraphe', texte: "Ces trois figures éclairent en retour l'ensemble du module. Elles rappellent que la **personnalité morale**, étudiée au chapitre 1, est un avantage que la loi accorde aux associés en contrepartie du respect des formalités de constitution, d'immatriculation et de publicité. Elles montrent que la **responsabilité limitée** des SARL, SA et SAS n'est pas un droit naturel, mais le bénéfice d'une forme régulièrement constituée. Et elles soulignent le rôle des professionnels du chiffre et du droit, qui accompagnent les entrepreneurs dans le choix et le respect de la forme la plus adaptée, depuis la constitution jusqu'à la dissolution." },
      { type: 'carte', titre: "Le module UE2 en une page", tableau: { entetes: ['Chapitre', 'Thème', 'Textes principaux'], lignes: [
        ["1", "Notion, constitution et naissance de la société", "Art. 1 à 120-5"],
        ["2", "Vie financière : comptes, résultat, dividendes, appel public à l'épargne", "Art. 137 à 149, 263 à 269-7, 81 à 96-1"],
        ["3", "Sociétés de personnes : SNC et SCS", "Art. 270 à 308"],
        ["4", "Sociétés par actions : SA et SAS", "Art. 385 à 515, 694 à 743, 853-1 à 853-23"],
        ["5", "SARL", "Art. 309 à 384"],
        ["6", "GIE", "Art. 869 à 885"],
        ["7", "Dirigeants sociaux : pouvoirs et responsabilités", "Art. 121 à 124, 159 à 172, 886 à 905 ; AUPCAP"],
        ["8", "Associés, assemblées et capital", "Art. 51 à 66, 125 à 136, 516 à 640"],
        ["9", "Transformations, restructurations, groupes, difficultés", "Art. 150 à 199, 671 à 693-1 ; AUPCAP"],
        ["10", "Dissolution, liquidation et nullités", "Art. 200 à 256"],
        ["11", "Société en participation et société de fait", "Art. 854 à 868"],
      ] } },
      { type: 'paragraphe', texte: "Pour l'examen, une méthode simple permet d'aborder toute situation de collaboration non formalisée. Il faut d'abord rechercher s'il existe un acte de société et, dans l'affirmative, s'il a été immatriculé, et pourquoi il ne l'a pas été : par choix (participation) ou par défaillance (société de fait). À défaut d'acte, il faut rechercher les éléments du contrat de société dans les comportements (société créée de fait). Il faut ensuite distinguer les **rapports entre associés** (convention, à défaut règles de la SNC) et les **rapports avec les tiers** (principe de l'engagement personnel dans la participation, sauf ostensibilité ou immixtion ; responsabilité indéfinie et solidaire dans la société créée de fait ou de fait reconnue). Il faut enfin traiter la **fin** de la collaboration (causes de dissolution de la SNC, notification pour la participation à durée indéterminée, liquidation des rapports) et, le cas échéant, ses **conséquences fiscales**. Cette démarche en quatre temps, qualification, rapports internes, rapports externes, fin, s'applique à la plupart des cas pratiques du chapitre." },
      { type: 'controle', question: QCM[29] },
    ],
  },
]

const CAS: Chapitre['casPratiques'] = [
  {
    id: 'cas1',
    titre: 'Le consortium routier du Kasaï',
    contexte: "Trois entreprises de BTP, deux SARL congolaises et une SA étrangère, s'associent pour construire une route de 80 km dans le Kasaï. Elles ne veulent pas créer de société commune et signent entre elles un accord répartissant les tronçons, les coûts et les résultats. L'offre et le marché sont signés par les trois entreprises « en qualité de membres du groupement ». L'une des SARL fait faillite en cours de chantier.",
    questions: [
      { num: 1, enonce: "Quelle est la nature juridique du groupement ?", correction: "C'est une société en participation : les trois entreprises ont convenu de mettre en commun des moyens pour réaliser une opération et en partager les résultats, sans immatriculer de société (art. 854). Elle n'a pas la personnalité morale ; son existence se prouve par tous moyens, en l'occurrence par l'accord écrit ; les parties en ont librement fixé l'objet, la durée et le fonctionnement (art. 855)." },
      { num: 2, enonce: "Le maître d'ouvrage peut-il exiger des deux autres entreprises l'exécution du tronçon de la SARL défaillante ?", correction: "Oui. Les membres ont agi « expressément en leur qualité d'associé » auprès du maître d'ouvrage en signant le marché comme membres du groupement : chacun est tenu par les engagements des autres, et les obligations ainsi souscrites les engagent indéfiniment et solidairement (art. 861 al. 2 et 3). La répartition des tronçons convenue entre elles n'est pas opposable au maître d'ouvrage." },
      { num: 3, enonce: "Comment les deux entreprises restantes peuvent-elles se protéger à l'avenir ?", correction: "Par un accord de consortium détaillé : garanties croisées ou garanties bancaires de bonne exécution fournies par chaque membre, clause de substitution en cas de défaillance, répartition du surcoût et recours contre le membre défaillant, clause de continuation du groupement malgré la faillite d'un membre, puisque la société en participation prend fin par les mêmes événements que la SNC, sauf clause contraire (art. 862 et 290). Sur le plan fiscal, elles vérifieront le régime applicable : option pour l'IS de la société en participation (loi n° 23/053, art. 4) ou traitement comme association momentanée." },
    ],
  },
  {
    id: 'cas2',
    titre: "L'investisseur discret de la boutique de M. MUKENDI",
    contexte: "M. TSHILOMBO a remis 30 000 000 FC à M. MUKENDI, commerçant à Mbuji-Mayi, pour développer son magasin de pièces détachées. Un écrit prévoit qu'il recevra 40 % des bénéfices et supportera 40 % des pertes, que M. MUKENDI gère seul le commerce, et que la collaboration n'est pas révélée aux fournisseurs. Un fournisseur impayé découvre l'accord et veut poursuivre M. TSHILOMBO.",
    questions: [
      { num: 1, enonce: "Quelle est la nature de l'accord ?", correction: "C'est une société en participation : les deux hommes affectent des moyens (fonds, travail et fonds de commerce) à une activité commune pour en partager les bénéfices et les pertes (art. 4), et ont convenu de ne pas immatriculer de société ni de révéler leur collaboration (art. 854). Ce n'est pas un prêt, puisque M. TSHILOMBO participe aux pertes." },
      { num: 2, enonce: "Le fournisseur peut-il poursuivre M. TSHILOMBO ?", correction: "En principe non. « Chaque associé contracte en son nom personnel et est seul engagé à l'égard des tiers » (art. 861 al. 1) : seul M. MUKENDI, qui a passé les commandes, est tenu envers le fournisseur. Il en irait autrement si M. TSHILOMBO s'était présenté au fournisseur comme associé (art. 861 al. 2), ou si, par son immixtion, il avait laissé croire qu'il s'engageait et que l'engagement avait tourné à son profit (art. 861 al. 4)." },
      { num: 3, enonce: "Dans leurs rapports internes, comment la perte se répartit-elle ?", correction: "Selon leur accord : M. TSHILOMBO supporte 40 % des pertes, M. MUKENDI 60 %. Si M. MUKENDI paie le fournisseur, il peut demander à M. TSHILOMBO sa contribution selon cette clé. La répartition est licite, car aucun des deux n'est exclu totalement des bénéfices ni des pertes (art. 54). Pour ce que l'accord ne prévoit pas, les règles de la SNC s'appliquent (art. 856)." },
    ],
  },
  {
    id: 'cas3',
    titre: "Le commerce des époux NGALULA",
    contexte: "Pendant quinze ans, M. et Mme NGALULA ont exploité ensemble un commerce de tissus au marché central de Kinshasa. Le registre de commerce est au seul nom de M. NGALULA, mais Mme NGALULA a apporté les fonds initiaux provenant de sa propre famille, tient la caisse, négocie avec les fournisseurs à Kinshasa et en Chine, et les bénéfices servent aux deux. Au moment de leur séparation, M. NGALULA soutient que le commerce est à lui seul.",
    questions: [
      { num: 1, enonce: "Mme NGALULA peut-elle invoquer une société créée de fait ?", correction: "Oui, à condition d'en prouver les éléments. Il y a société créée de fait lorsque deux personnes se comportent comme des associés sans avoir constitué de société (art. 864). Elle doit établir des apports (les fonds initiaux, son travail), une participation aux bénéfices et aux pertes, et une volonté de collaborer sur un pied d'égalité, qui dépasse la simple entraide conjugale. La preuve est libre (art. 867) : témoignages de fournisseurs, correspondances, relevés bancaires, rôle dans les négociations." },
      { num: 2, enonce: "Qui peut demander cette reconnaissance, et devant qui ?", correction: "« Tout intéressé » peut demander à la juridiction compétente la reconnaissance de la société créée de fait, à charge d'établir l'identité des personnes concernées (art. 866). Mme NGALULA a intérêt à agir pour obtenir sa part du fonds de commerce et des bénéfices. Le juge apprécie souverainement si les éléments réunis caractérisent une société et non une simple collaboration familiale." },
      { num: 3, enonce: "Quelles sont les conséquences si la société est reconnue ?", correction: "Les règles de la SNC s'appliquent (art. 868). Entre les époux, la société doit être liquidée : reprise des apports, paiement des dettes, partage du solde selon leurs droits, à proportion des apports à défaut d'autre preuve (art. 54). Envers les tiers, les deux époux répondent indéfiniment et solidairement des dettes du commerce (art. 270). Pour l'avenir, s'ils voulaient poursuivre ensemble, la constitution d'une SARL leur permettrait de limiter leur responsabilité et de clarifier leurs droits." },
    ],
  },
  {
    id: 'cas4',
    titre: "La SARL jamais immatriculée de Kisangani",
    contexte: "Quatre amis ont signé en 2023 les statuts d'une SARL de transport fluvial à Kisangani, mais n'ont jamais déposé le capital ni fait immatriculer la société. Ils ont pourtant acheté deux baleinières, embauché des équipages et transporté des marchandises pendant trois ans, en utilisant une dénomination commerciale. Un chargeur dont la cargaison a été perdue réclame 60 000 000 FC d'indemnité.",
    questions: [
      { num: 1, enonce: "Quelle est la qualification de ce groupement ?", correction: "Les amis ont constitué une société reconnue (une SARL) mais sa constitution comporte un vice de formation non régularisé : capital non libéré ni déposé, absence d'immatriculation. Il y a société de fait (art. 865). Ce n'est pas une société en participation, car ils n'ont pas convenu de ne pas immatriculer la société (art. 114, 854) : ils avaient l'intention de créer une SARL." },
      { num: 2, enonce: "Les associés bénéficient-ils de la responsabilité limitée de la SARL ?", correction: "Non. Faute d'immatriculation, la société n'a pas la personnalité morale, et la responsabilité limitée de la SARL (art. 309) ne s'applique pas. Une fois l'existence de la société de fait reconnue, les règles de la SNC s'appliquent aux associés (art. 868) : ils répondent indéfiniment et solidairement des dettes sociales (art. 270). Le chargeur peut donc poursuivre chacun des quatre amis pour la totalité de son indemnité, après mise en demeure selon les règles de la SNC." },
      { num: 3, enonce: "Quelles conséquences fiscales et quels conseils ?", correction: "Sur le plan fiscal, les sociétés de fait entrent dans le champ de l'IS en raison de leur activité (loi n° 23/053) : l'administration peut les imposer, avec les pénalités de défaut de déclaration. Pour l'avenir, les associés doivent régulariser : libérer et déposer le capital, faire immatriculer une SARL au guichet unique, ce qui leur apportera la personnalité morale et la limitation de leur responsabilité pour les dettes nées après l'immatriculation ; les dettes antérieures, nées pendant la période de fait, restent à leur charge personnelle." },
    ],
  },
  {
    id: 'cas5',
    titre: "Les frères KABAMBA et le décès de l'aîné",
    contexte: "Les trois frères KABAMBA exploitent ensemble, sans statuts, une scierie dans le Tshopo depuis douze ans : chacun a apporté des machines, ils partagent les bénéfices à parts égales et prennent ensemble les décisions importantes. L'aîné décède. Ses enfants réclament un tiers de la scierie ; les deux frères survivants soutiennent que la scierie appartient à celui dont le nom figure sur les factures, le cadet.",
    questions: [
      { num: 1, enonce: "Les héritiers peuvent-ils faire reconnaître une société créée de fait ?", correction: "Oui. Les trois frères se sont comportés comme des associés : apports de machines, partage égal des bénéfices, décisions communes (art. 864). Tout intéressé, y compris les héritiers d'un associé, peut demander au juge la reconnaissance de la société créée de fait (art. 866), et la preuve se fait par tout moyen (art. 867) : témoignages des employés et des clients, achats de machines, partage des bénéfices." },
      { num: 2, enonce: "Quel est l'effet du décès de l'aîné sur la société ?", correction: "Une fois la société reconnue, les règles de la SNC s'appliquent (art. 868). Or la SNC prend fin par le décès d'un associé, sauf clause de continuation (art. 290). En l'absence de statuts, aucune clause de continuation n'existe : la société est dissoute et doit être liquidée, à moins que tous les intéressés ne s'accordent sur une autre solution, par exemple le rachat de la part des héritiers par les frères survivants." },
      { num: 3, enonce: "Comment la part des héritiers est-elle déterminée ?", correction: "Par la liquidation des rapports sociaux : inventaire de l'actif (machines, stocks, créances, fonds), paiement des dettes, reprise des apports, puis partage du solde selon les droits de chacun, ici à parts égales, conformément à la pratique constante des frères. Les héritiers de l'aîné ont droit à un tiers du solde. Un expert, souvent un expert-comptable, peut être désigné pour reconstituer les comptes de la société de fait et évaluer les biens." },
    ],
  },
  {
    id: 'cas6',
    titre: "Choisir entre GIE, société en participation et SARL",
    contexte: "Quatre cabinets médicaux de Lubumbashi veulent acquérir ensemble un appareil d'IRM coûteux, partager son utilisation et ses frais, et éventuellement accueillir d'autres cabinets. Un premier conseil leur propose une société en participation, un second un GIE, un troisième une SARL commune.",
    questions: [
      { num: 1, enonce: "Quels sont les avantages et inconvénients de la société en participation ?", correction: "Elle est souple et discrète : pas d'immatriculation, organisation libre (art. 854, 855). Mais elle n'a pas de personnalité morale : l'IRM serait la propriété d'un cabinet ou en indivision entre eux (art. 857 à 859), ce qui complique le financement bancaire, l'entrée de nouveaux membres et la gestion ; et les cabinets qui s'engagent ensemble envers les fournisseurs en qualité d'associés répondent indéfiniment et solidairement (art. 861)." },
      { num: 2, enonce: "Et le GIE ?", correction: "Le GIE a la personnalité morale dès son immatriculation (art. 872), peut être propriétaire de l'IRM, emprunter et employer des techniciens. Son objet, l'exploitation d'un équipement au service de l'activité médicale des membres, est auxiliaire (art. 869), et les professions libérales réglementées peuvent en être membres (art. 871). Il peut être constitué sans capital. En revanche, les membres répondent indéfiniment et solidairement des dettes du groupement (art. 873), sauf convention contraire avec chaque créancier." },
      { num: 3, enonce: "Et la SARL ?", correction: "La SARL limite la responsabilité des associés à leurs apports (art. 309) et a un capital librement fixé en RDC. Mais elle vise en principe à réaliser et partager des bénéfices, alors que les cabinets veulent partager des coûts ; elle est soumise à l'IS de plein droit (loi n° 23/053, art. 3), et son fonctionnement est plus formaliste. Le GIE paraît ici le mieux adapté à l'objectif, sous réserve de mesurer la responsabilité solidaire des membres et de vérifier les règles déontologiques de l'ordre des médecins ; la SARL serait préférable si les cabinets voulaient avant tout limiter leur risque." },
    ],
  },
]

export const chapitre: Chapitre = {
  ue: 'ue2',
  numero: 11,
  id: 'ue2-chapitre-11',
  titre: 'La société en participation et la société de fait',
  sousTitre: "AUSCGIE révisé, art. 114, 115 et 854 à 868 · loi n° 23/053, art. 3 et 4",
  infoBulle: "Les sociétés sans personnalité morale : la société en participation (notion, rapports entre associés, biens, rapports avec les tiers, fin, fiscalité), la société créée de fait et la société de fait (notions, preuve, reconnaissance judiciaire, application des règles de la SNC), leur place dans l'économie congolaise et une synthèse du module.",
  loiRef: 'Art. 114, 115, 854-868 AUSCGIE · loi n° 23/053, art. 3 et 4',
  moduleLabel: 'UE 2 · Droit des sociétés',
  retourRoute: '/ue2-droit-societes',
  coursId: 'ue2-droit-societes',
  objectifs: [
    "Distinguer la société en participation, la société créée de fait et la société de fait (art. 114, 115, 854, 864, 865)",
    "Organiser une société en participation et en mesurer la liberté conventionnelle (art. 854, 855)",
    "Déterminer le régime des biens et des rapports entre associés d'une participation (art. 856 à 860)",
    "Appliquer les règles d'engagement des associés envers les tiers (art. 861)",
    "Identifier les causes de fin de la participation et son régime fiscal en RDC (art. 862, 863 ; loi n° 23/053, art. 4)",
    "Caractériser une société créée de fait ou une société de fait et en apporter la preuve (art. 4, 864 à 867)",
    "Tirer les conséquences de la reconnaissance judiciaire : application des règles de la SNC (art. 868, 270)",
    "Conseiller des entrepreneurs non formalisés sur les risques et les voies de régularisation",
  ],
  sections: SECTIONS,
  aRetenir: [
    "Trois sociétés n'ont pas la personnalité morale : la société en participation, que les associés ont choisi de ne pas immatriculer (art. 114, 854) ; la société créée de fait, née du comportement d'associés sans constitution de société (art. 864) ; la société de fait, dont la constitution a échoué ou dont la forme n'est pas reconnue (art. 115, 865).",
    "La société en participation n'est ni immatriculée ni publiée, et se prouve par tous moyens (art. 854) ; les associés en fixent librement l'objet, la durée, le fonctionnement et la fin, dans le respect des règles impératives communes aux sociétés hors personnalité morale (art. 855).",
    "À défaut d'organisation différente, les rapports entre associés d'une participation suivent les règles de la SNC (art. 856) ; chaque associé reste propriétaire des biens qu'il met à disposition (art. 857) ; les associés peuvent organiser une indivision ou désigner l'un d'eux propriétaire à l'égard des tiers (art. 858) ; les biens acquis avec des deniers indivis sont indivis et ne peuvent être partagés avant la dissolution sauf clause contraire (art. 859, 860).",
    "Chaque associé d'une participation contracte en son nom et est seul engagé envers les tiers ; mais ceux qui agissent expressément en qualité d'associés, ou l'associé dont l'immixtion a créé une apparence et qui en a profité, sont tenus indéfiniment et solidairement (art. 861).",
    "La participation prend fin par les événements qui mettent fin à la SNC, sauf clause de continuation (art. 862) ; à durée indéterminée, par une notification de bonne foi et non à contretemps (art. 863). En RDC, elle n'est soumise à l'IS que sur option irrévocable (loi n° 23/053, art. 4).",
    "La société créée de fait suppose des personnes qui se comportent comme des associés : apports, vocation aux bénéfices et aux pertes, volonté de collaborer (art. 4, 864) ; la société de fait, une constitution viciée non régularisée ou une forme non reconnue (art. 865) ; la nullité d'une société laisse subsister pour le passé une société de fait (art. 253).",
    "Tout intéressé peut demander la reconnaissance d'une société créée de fait (art. 866) ; la preuve est libre (art. 867) ; une fois l'existence reconnue, les règles de la SNC s'appliquent, et les associés répondent indéfiniment et solidairement des dettes (art. 868, 270).",
    "Une société non immatriculée par négligence n'est pas une société en participation mais une société de fait : ses associés ne bénéficient pas de la responsabilité limitée de la forme qu'ils avaient choisie.",
    "En RDC, les sociétés de fait et créées de fait, comme les associations momentanées, entrent dans le champ de l'IS en raison de leur activité (loi n° 23/053) : l'absence de formalisation ne soustrait pas l'activité à l'impôt.",
    "Conflit, décès et endettement révèlent les risques des collaborations non formalisées ; l'expert-comptable doit identifier ces situations et proposer une formalisation adaptée : SARL, SAS, GIE ou contrat de société en participation détaillé.",
  ],
  references: [
    { genre: 'texte', intitule: "Acte uniforme révisé relatif au droit des sociétés commerciales et du groupement d'intérêt économique (AUSCGIE)", precision: "30 janvier 2014 ; art. 4, 54, 114, 115, 188, 253, 270, 271, 274, 276, 283, 290, 309 et 854 à 873" },
    { genre: 'texte', intitule: "Acte uniforme révisé portant sur le droit commercial général (AUDCG)", precision: "15 décembre 2010 ; art. 7" },
    { genre: 'texte', intitule: "Loi n° 23/053 du 30 novembre 2023 relative à l'impôt sur les sociétés et à l'impôt sur le revenu des personnes physiques", precision: "art. 3 et 4 (champ d'application de l'IS)" },
    { genre: 'ouvrage', auteur: "Pougoué P.-G., Anoukaha F. et Nguebou Toukam J.", titre: "Le droit des sociétés commerciales et du groupement d'intérêt économique OHADA", editeur: "Presses universitaires d'Afrique", lieu: "Yaoundé", annee: "1998" },
    { genre: 'ouvrage', auteur: "Anoukaha F., Cissé A., Diouf N., Nguebou Toukam J., Pougoué P.-G. et Samb M.", titre: "OHADA. Sociétés commerciales et GIE", editeur: "Bruylant, coll. Droit uniforme africain", lieu: "Bruxelles", annee: "2002" },
    { genre: 'ouvrage', auteur: "Pougoué P.-G. (dir.)", titre: "Encyclopédie du droit OHADA", editeur: "Lamy", lieu: "Paris", annee: "2011" },
    { genre: 'ouvrage', auteur: "Diouf N., Masamba Makela R., Pougoué P.-G. et Sawadogo F. M. (coord.)", titre: "Code vert OHADA 2025. Traité et actes uniformes commentés et annotés", editeur: "Juriscope", lieu: "Poitiers", annee: "2025" },
    { genre: 'ouvrage', auteur: "Masamba R.", titre: "L'OHADA en RDC. Manuel de vulgarisation", editeur: "congolegal.cd", lieu: "s.l.", annee: "2012" },
  ],
  qcm: QCM,
  casPratiques: CAS,
  sources: "Sources : AUSCGIE révisé du 30 janvier 2014, art. 114, 115 et 854 à 868 · Loi n° 23/053 du 30 novembre 2023 (IS et IRPP).",
}

export default chapitre
