// Chapitre 10 du module UE2, Droit des sociétés : contenu pur.
// La mise en forme appartient au moteur components/chapitre/ChapitreManuscrit.tsx.
//
// Réécriture approfondie (septembre 2026). Les infractions pénales générales
// des dirigeants sont désormais traitées au chapitre 7 ; ce chapitre ne
// reprend que celles qui concernent la dissolution et la liquidation.
// Sources lues pendant la rédaction :
// - AUSCGIE révisé du 30 janvier 2014, texte intégral des art. 200 à 256
//   (dissolution, liquidation, nullités), art. 901 à 904 (infractions) et
//   908 à 914 (mise en harmonie), skill auscgie-acte-uniforme ;
// - loi n° 004/2003 du 13 mars 2003 portant réforme des procédures
//   fiscales, art. 16 et 80, d'après le skill fiscalite-rdc.
import type { Chapitre } from '@/lib/chapitre-types'

const QCM: Chapitre['qcm'] = [
  {
    id: 'ch10-q1', question: "Parmi ces événements, lequel n'est pas une cause de dissolution prévue par l'art. 200 ?",
    options: [
      { id: 'a', texte: "L'expiration de la durée de la société" },
      { id: 'b', texte: "La réalisation ou l'extinction de l'objet" },
      { id: 'c', texte: "Un exercice déficitaire" },
      { id: 'd', texte: "Un jugement ordonnant la liquidation des biens" },
    ],
    reponseCorrecte: 'c', articleRef: 'Art. 200 AUSCGIE',
    explication: "La société prend fin par l'expiration de sa durée, la réalisation ou l'extinction de son objet, l'annulation du contrat, la décision des associés, la dissolution judiciaire pour justes motifs, un jugement de liquidation des biens, ou toute autre cause statutaire (art. 200). Une simple perte ne dissout pas la société ; la perte de la moitié du capital oblige seulement à consulter les associés (art. 371, 664).",
  },
  {
    id: 'ch10-q2', question: "À quelles conditions les associés peuvent-ils dissoudre la société par anticipation ?",
    options: [
      { id: 'a', texte: "À la majorité simple" },
      { id: 'b', texte: "Aux conditions prévues pour modifier les statuts" },
      { id: 'c', texte: "À l'unanimité dans tous les cas" },
      { id: 'd', texte: "Avec l'accord du juge" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 200, 4° AUSCGIE',
    explication: "La société prend fin « par décision des associés aux conditions prévues pour modifier les statuts » (art. 200, 4°) : trois quarts du capital dans la SARL, deux tiers des voix en AGE dans la SA.",
  },
  {
    id: 'ch10-q3', question: "Un associé peut-il demander au juge la dissolution anticipée de la société ?",
    options: [
      { id: 'a', texte: "Non, jamais" },
      { id: 'b', texte: "Oui, pour justes motifs, notamment l'inexécution de ses obligations par un associé ou une mésentente empêchant le fonctionnement normal" },
      { id: 'c', texte: "Oui, s'il détient la majorité" },
      { id: 'd', texte: "Oui, dès qu'il est en désaccord avec la gestion" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 200, 5° AUSCGIE',
    explication: "La dissolution anticipée peut être prononcée par le juge « à la demande d'un associé pour justes motifs, notamment en cas d'inexécution de ses obligations par un associé ou de mésentente entre associés empêchant le fonctionnement normal de la société » (art. 200, 5°). Un simple désaccord ne suffit pas.",
  },
  {
    id: 'ch10-q4', question: "À partir de quand la dissolution est-elle opposable aux tiers ?",
    options: [
      { id: 'a', texte: "Dès la décision des associés" },
      { id: 'b', texte: "À compter de sa publication par avis dans un journal d'annonces légales" },
      { id: 'c', texte: "Après la clôture de la liquidation" },
      { id: 'd', texte: "Trois mois après la décision" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 201 et 202 AUSCGIE',
    explication: "« La dissolution de la société n'a d'effet à l'égard des tiers qu'à compter de sa publication par avis inséré dans un journal habilité à recevoir les annonces légales » (art. 201). Elle est aussi publiée par dépôt des actes au registre et modification de l'inscription au RCCM (art. 202).",
  },
  {
    id: 'ch10-q5', question: "Que devient la personnalité morale de la société dissoute ?",
    options: [
      { id: 'a', texte: "Elle disparaît immédiatement" },
      { id: 'b', texte: "Elle subsiste pour les besoins de la liquidation, jusqu'à la publication de sa clôture" },
      { id: 'c', texte: "Elle subsiste trois ans" },
      { id: 'd', texte: "Elle est transférée au liquidateur" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 201 et 205 AUSCGIE',
    explication: "« La personnalité morale de la société subsiste pour les besoins de la liquidation et jusqu'à la publication de la clôture de celle-ci » (art. 205). La société peut donc encore vendre ses biens, recouvrer ses créances, payer ses dettes et ester en justice.",
  },
  {
    id: 'ch10-q6', question: "Une SARL dont toutes les parts appartiennent à une société mère est dissoute. Faut-il la liquider ?",
    options: [
      { id: 'a', texte: "Oui, toujours" },
      { id: 'b', texte: "Non : son patrimoine est transmis universellement à l'associé unique, après un délai d'opposition de trente jours ouvert aux créanciers" },
      { id: 'c', texte: "Non, elle est simplement radiée" },
      { id: 'd', texte: "Oui, sauf accord du fisc" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 201 al. 4 et 5 AUSCGIE',
    explication: "La dissolution d'une société dont tous les titres sont détenus par un seul associé entraîne la transmission universelle du patrimoine à cet associé, sans liquidation ; les créanciers peuvent former opposition dans les trente jours de la publication. Cette règle ne s'applique pas lorsque l'associé unique est une personne physique : la dissolution entraîne alors la liquidation (art. 201).",
  },
  {
    id: 'ch10-q7', question: "Quelle mention doit figurer sur les factures d'une société dissoute ?",
    options: [
      { id: 'a', texte: "« Société dissoute »" },
      { id: 'b', texte: "« Société en liquidation » et le nom du ou des liquidateurs" },
      { id: 'c', texte: "Aucune mention particulière" },
      { id: 'd', texte: "Le montant du boni de liquidation" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 204 AUSCGIE',
    explication: "La société est en liquidation dès sa dissolution ; « la mention “société en liquidation” ainsi que le nom du ou des liquidateurs doivent figurer sur tous les actes et documents émanant de la société et destinés aux tiers » (art. 204).",
  },
  {
    id: 'ch10-q8', question: "Comment les associés d'une SARL nomment-ils le liquidateur ?",
    options: [
      { id: 'a', texte: "À l'unanimité" },
      { id: 'b', texte: "À la majorité en capital des associés" },
      { id: 'c', texte: "Aux trois quarts du capital" },
      { id: 'd', texte: "Le gérant devient liquidateur de plein droit" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 206 AUSCGIE',
    explication: "Le liquidateur est nommé à l'unanimité dans la SNC, à l'unanimité des commandités et à la majorité en capital des commanditaires dans la SCS, « à la majorité en capital des associés » dans la SARL, et aux conditions de l'AGE dans les sociétés par actions (art. 206).",
  },
  {
    id: 'ch10-q9', question: "Une personne morale peut-elle être liquidateur ?",
    options: [
      { id: 'a', texte: "Non" },
      { id: 'b', texte: "Oui ; le liquidateur peut être un associé ou un tiers, personne physique ou morale" },
      { id: 'c', texte: "Seulement une banque" },
      { id: 'd', texte: "Seulement si le juge l'autorise" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 207 AUSCGIE',
    explication: "« Le liquidateur peut être choisi parmi les associés ou les tiers. Il peut être une personne morale » (art. 207). Un cabinet d'expertise comptable constitué en société peut donc être nommé liquidateur.",
  },
  {
    id: 'ch10-q10', question: "Le liquidateur peut-il acheter pour lui-même un camion de la société en liquidation ?",
    options: [
      { id: 'a', texte: "Oui, au prix du marché" },
      { id: 'b', texte: "Non, la cession d'actif au liquidateur, à ses employés ou à leurs proches est interdite" },
      { id: 'c', texte: "Oui, avec l'accord du juge" },
      { id: 'd', texte: "Oui, avec l'accord de la majorité des associés" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 214 et 215-1 AUSCGIE',
    explication: "« La cession de tout ou partie de l'actif de la société en liquidation au liquidateur, à ses employés ou à leurs conjoints, ascendants ou descendants, est interdite » (art. 214), à peine de nullité (art. 215-1). Aucune autorisation ne peut lever cette interdiction.",
  },
  {
    id: 'ch10-q11', question: "L'ancien gérant veut racheter le stock de la société en liquidation. Est-ce possible ?",
    options: [
      { id: 'a', texte: "Non, jamais" },
      { id: 'b', texte: "Oui, avec le consentement unanime des associés ou, à défaut, l'autorisation du juge, liquidateur et commissaire aux comptes entendus" },
      { id: 'c', texte: "Oui, librement" },
      { id: 'd', texte: "Oui, s'il paie comptant" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 213 AUSCGIE',
    explication: "Sauf consentement unanime des associés, la cession d'actif à un ancien associé en nom, commandité, gérant, administrateur, directeur général, autre dirigeant ou commissaire aux comptes « ne peut avoir lieu qu'avec l'autorisation de la juridiction compétente, le liquidateur et le commissaire aux comptes entendus » (art. 213).",
  },
  {
    id: 'ch10-q12', question: "Dans quel délai la clôture de la liquidation doit-elle intervenir ?",
    options: [
      { id: 'a', texte: "Un an" },
      { id: 'b', texte: "Trois ans à compter de la dissolution ; à défaut, le ministère public ou tout intéressé peut saisir le juge" },
      { id: 'c', texte: "Cinq ans" },
      { id: 'd', texte: "Aucun délai" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 216 AUSCGIE',
    explication: "« La clôture de la liquidation doit intervenir dans un délai de trois (3) ans à compter de la dissolution de la société. » À défaut, le ministère public ou tout intéressé peut saisir la juridiction du siège pour qu'il soit procédé à la liquidation ou à son achèvement (art. 216).",
  },
  {
    id: 'ch10-q13', question: "Sur quoi statue l'assemblée de clôture de la liquidation ?",
    options: [
      { id: 'a', texte: "Sur la nomination d'un nouveau gérant" },
      { id: 'b', texte: "Sur les comptes définitifs, le quitus du liquidateur, la décharge de son mandat et la constatation de la clôture" },
      { id: 'c', texte: "Sur la distribution d'un dividende" },
      { id: 'd', texte: "Sur la dissolution" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 217 AUSCGIE',
    explication: "« Les associés sont convoqués en fin de liquidation pour statuer sur les comptes définitifs, sur le quitus de la gestion du liquidateur et la décharge de son mandat et pour constater la clôture de la liquidation » ; à défaut, tout associé peut obtenir la désignation d'un mandataire ad hoc pour les convoquer (art. 217).",
  },
  {
    id: 'ch10-q14', question: "Dans quel délai le liquidateur doit-il demander la radiation de la société ?",
    options: [
      { id: 'a', texte: "Huit jours" },
      { id: 'b', texte: "Un mois à compter de la publication de la clôture" },
      { id: 'c', texte: "Six mois" },
      { id: 'd', texte: "Un an" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 219 et 220 AUSCGIE',
    explication: "Les comptes définitifs sont déposés au RCCM avec la décision de l'assemblée ou du juge (art. 219) ; sur justification de ces formalités, le liquidateur demande la radiation « dans le délai d'un (1) mois à compter de la publication de la clôture de la liquidation » (art. 220).",
  },
  {
    id: 'ch10-q15', question: "Dans quel délai se prescrit l'action contre les associés non liquidateurs après la dissolution ?",
    options: [
      { id: 'a', texte: "Trois ans" },
      { id: 'b', texte: "Cinq ans à compter de la publication de la dissolution au RCCM" },
      { id: 'c', texte: "Dix ans" },
      { id: 'd', texte: "Un an" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 222 AUSCGIE',
    explication: "« Toute action contre les associés non liquidateurs ou leur(s) conjoint(s) survivant(s), héritiers ou ayants-cause, se prescrit par cinq (5) ans à compter de la publication de la dissolution de la société au registre du commerce et du crédit mobilier » (art. 222). L'action contre le liquidateur se prescrit, elle, par trois ans (art. 221).",
  },
  {
    id: 'ch10-q16', question: "Qui peut demander au juge d'ordonner une liquidation selon le régime des art. 224 à 241 ?",
    options: [
      { id: 'a', texte: "Le seul ministère public" },
      { id: 'b', texte: "La majorité des associés d'une SNC, des associés représentant le dixième du capital dans les autres sociétés, des créanciers sociaux ou le représentant de la masse des obligataires" },
      { id: 'c', texte: "Le liquidateur" },
      { id: 'd', texte: "Tout salarié" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 223 AUSCGIE',
    explication: "Le régime particulier s'applique à la liquidation amiable à défaut de clauses, ou sur décision du juge statuant à bref délai à la demande, justifiant d'un intérêt légitime, de la majorité des associés d'une SNC, d'associés représentant le dixième du capital dans les autres sociétés, de créanciers sociaux ou du représentant de la masse des obligataires (art. 223).",
  },
  {
    id: 'ch10-q17', question: "Quelle est la durée maximale du mandat d'un liquidateur désigné par le juge ?",
    options: [
      { id: 'a', texte: "Un an" },
      { id: 'b', texte: "Trois ans, renouvelables par décision de justice" },
      { id: 'c', texte: "Cinq ans" },
      { id: 'd', texte: "Sans limite" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 227 AUSCGIE',
    explication: "« La durée du mandat du liquidateur ne peut excéder trois (3) ans, renouvelables, par décision de justice, à la requête du liquidateur », qui doit expliquer pourquoi la liquidation n'a pu être clôturée (art. 227).",
  },
  {
    id: 'ch10-q18', question: "Dans quel délai le liquidateur désigné selon le régime particulier doit-il faire rapport aux associés ?",
    options: [
      { id: 'a', texte: "Un mois" },
      { id: 'b', texte: "Six mois de sa nomination, prorogeables à douze mois par le juge" },
      { id: 'c', texte: "Deux ans" },
      { id: 'd', texte: "À la clôture seulement" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 228 AUSCGIE',
    explication: "« Dans les six (6) mois de sa nomination, le liquidateur convoque l'assemblée des associés à laquelle il fait rapport sur la situation des actifs et du passif », sur la poursuite des opérations et leur délai ; ce délai peut être porté à douze mois par décision de justice (art. 228).",
  },
  {
    id: 'ch10-q19', question: "Le liquidateur peut-il engager de nouvelles affaires ?",
    options: [
      { id: 'a', texte: "Oui, librement" },
      { id: 'b', texte: "Seulement s'il y a été autorisé par décision de justice, pour les besoins de la liquidation" },
      { id: 'c', texte: "Non, jamais" },
      { id: 'd', texte: "Oui, avec l'accord d'un créancier" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 230 et 231 AUSCGIE',
    explication: "Le liquidateur a les pouvoirs les plus étendus pour réaliser l'actif, les restrictions statutaires étant inopposables aux tiers (art. 230) ; il paie les créanciers et répartit le solde, mais « ne peut continuer les affaires en cours ou en engager de nouvelles, pour les besoins de la liquidation, que s'il y a été autorisé par décision de justice » (art. 231).",
  },
  {
    id: 'ch10-q20', question: "À défaut de clause statutaire, comment le boni de liquidation est-il partagé ?",
    options: [
      { id: 'a', texte: "À parts égales" },
      { id: 'b', texte: "Après remboursement du nominal, dans les mêmes proportions que la participation au capital" },
      { id: 'c', texte: "Au profit du gérant" },
      { id: 'd', texte: "Il est versé au Trésor" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 237 AUSCGIE',
    explication: "« Sauf clause contraire des statuts, le partage des capitaux propres subsistant après remboursement du nominal des actions ou des parts sociales est effectué entre les associés dans les mêmes proportions que leur participation au capital social » (art. 237).",
  },
  {
    id: 'ch10-q21', question: "Que deviennent les sommes non réclamées par des créanciers ou des associés un an après la clôture ?",
    options: [
      { id: 'a', texte: "Elles reviennent au liquidateur" },
      { id: 'b', texte: "Elles sont déposées sur un compte séquestre ouvert auprès du Trésor public" },
      { id: 'c', texte: "Elles sont réparties entre les autres associés" },
      { id: 'd', texte: "Elles sont perdues" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 239 et 240 AUSCGIE',
    explication: "Les sommes affectées aux répartitions sont déposées dans les quinze jours sur un compte bancaire au nom de la société en liquidation (art. 239) ; celles qui n'ont pu être versées sont déposées, un an après la clôture, sur un compte séquestre auprès du Trésor public (art. 240).",
  },
  {
    id: 'ch10-q22', question: "Quelle obligation fiscale pèse sur une société en liquidation en RDC ?",
    options: [
      { id: 'a', texte: "Aucune, puisqu'elle cesse son activité" },
      { id: 'b', texte: "Déposer sa déclaration dans le mois de la dissolution ou de la cessation, et, en tout cas, avant que le dirigeant ne quitte la RDC ; le liquidateur qui n'avise pas l'administration est solidaire des impôts" },
      { id: 'c', texte: "Payer une taxe de radiation forfaitaire" },
      { id: 'd', texte: "Obtenir une autorisation du ministre des Finances" },
    ],
    reponseCorrecte: 'b', articleRef: 'Loi n° 004/2003, art. 16 et 80',
    explication: "En cas de dissolution, de liquidation ou de cessation d'affaires, la déclaration est remise dans le mois et, en tout cas, avant que le dirigeant ne quitte la RDC (art. 16 de la loi n° 004/2003) ; le liquidateur qui n'avise pas l'administration est tenu au paiement des impôts dus solidairement avec la société (art. 80).",
  },
  {
    id: 'ch10-q23', question: "Sur quel fondement la nullité d'une société peut-elle être prononcée ?",
    options: [
      { id: 'a', texte: "Pour toute irrégularité" },
      { id: 'b', texte: "Seulement sur une disposition expresse de l'Acte uniforme ou, sous réserve de restrictions, sur les textes régissant la nullité des contrats" },
      { id: 'c', texte: "Sur simple demande d'un créancier" },
      { id: 'd', texte: "Pour défaut de rentabilité" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 242 AUSCGIE',
    explication: "« La nullité d'une société ne peut résulter que d'une disposition du présent Acte uniforme la prévoyant expressément ou, sous réserve des dispositions de l'alinéa suivant, des textes régissant la nullité des contrats » (art. 242 al. 1). Le législateur limite les nullités pour protéger la sécurité juridique.",
  },
  {
    id: 'ch10-q24', question: "Une SA peut-elle être annulée pour vice du consentement d'un seul actionnaire fondateur ?",
    options: [
      { id: 'a', texte: "Oui" },
      { id: 'b', texte: "Non ; dans les SARL et sociétés par actions, ni le vice du consentement ni l'incapacité d'un associé n'entraînent la nullité, sauf s'ils atteignent tous les fondateurs" },
      { id: 'c', texte: "Oui, si l'actionnaire est majoritaire" },
      { id: 'd', texte: "Oui, dans les trois mois" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 242 al. 3 AUSCGIE',
    explication: "« Dans les sociétés à responsabilité limitée et dans les sociétés par actions, la nullité de la société ne peut résulter ni d'un vice de consentement ni de l'incapacité d'un associé à moins que celle-ci n'atteigne tous les associés fondateurs » (art. 242 al. 3).",
  },
  {
    id: 'ch10-q25', question: "La cause de nullité a disparu avant que le juge statue en première instance. Que se passe-t-il ?",
    options: [
      { id: 'a', texte: "La nullité est quand même prononcée" },
      { id: 'b', texte: "L'action en nullité est éteinte, sauf si la nullité est fondée sur l'illicéité de l'objet social" },
      { id: 'c', texte: "Le juge renvoie en appel" },
      { id: 'd', texte: "La société est dissoute" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 246 AUSCGIE',
    explication: "« L'action en nullité est éteinte lorsque la cause de nullité a cessé d'exister le jour où la juridiction compétente statue sur le fond en première instance, sauf si cette nullité est fondée sur le caractère illicite de l'objet social » (art. 246). Le juge peut d'ailleurs fixer un délai pour régulariser et ne peut prononcer la nullité moins de deux mois après l'assignation (art. 247).",
  },
  {
    id: 'ch10-q26', question: "Dans quel délai se prescrit l'action en nullité d'une fusion ?",
    options: [
      { id: 'a', texte: "Trois ans" },
      { id: 'b', texte: "Six mois à compter de la dernière inscription au RCCM rendue nécessaire par l'opération" },
      { id: 'c', texte: "Un an" },
      { id: 'd', texte: "Dix ans" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 251 AUSCGIE',
    explication: "Les actions en nullité de la société et de ses actes se prescrivent par trois ans ; « toutefois, l'action en nullité d'une fusion ou d'une scission se prescrit par six (6) mois à compter de la date de la dernière inscription au registre du commerce et du crédit mobilier rendue nécessaire par l'opération » (art. 251).",
  },
  {
    id: 'ch10-q27', question: "Quel est l'effet de la nullité de la société ?",
    options: [
      { id: 'a', texte: "Elle efface rétroactivement tous les actes accomplis" },
      { id: 'b', texte: "Elle met fin, sans rétroactivité, à l'exécution du contrat, et entraîne dissolution et liquidation" },
      { id: 'c', texte: "Elle transforme la société en SNC" },
      { id: 'd', texte: "Elle n'a aucun effet envers les associés" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 253 AUSCGIE',
    explication: "« Lorsque la nullité de la société est prononcée, elle met fin, sans rétroactivité, à l'exécution du contrat. Il est procédé à sa dissolution et, pour ce qui concerne les sociétés pluripersonnelles, à leur liquidation » (art. 253). C'est la théorie de la société de fait pour le passé.",
  },
  {
    id: 'ch10-q28', question: "Les associés peuvent-ils opposer la nullité de la société à un fournisseur de bonne foi ?",
    options: [
      { id: 'a', texte: "Oui, toujours" },
      { id: 'b', texte: "Non, sauf nullité pour vice du consentement ou incapacité, opposable par l'incapable ou la personne dont le consentement a été vicié" },
      { id: 'c', texte: "Oui, si la nullité est publiée" },
      { id: 'd', texte: "Seulement dans la SNC" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 255 AUSCGIE',
    explication: "« Ni la société, ni les associés ne peuvent se prévaloir d'une nullité à l'égard des tiers de bonne foi. » Toutefois, la nullité pour vice du consentement ou incapacité est opposable même aux tiers de bonne foi par l'incapable, son représentant légal ou la personne dont le consentement a été vicié (art. 255).",
  },
  {
    id: 'ch10-q29', question: "Les formalités de publicité d'une SNC n'ont pas été accomplies. Quelle sanction ?",
    options: [
      { id: 'a', texte: "Aucune" },
      { id: 'b', texte: "La nullité est encourue, sans que les associés puissent l'opposer aux tiers ; le juge peut ne pas la prononcer en l'absence de fraude" },
      { id: 'c', texte: "Une amende fiscale" },
      { id: 'd', texte: "La transformation en SARL" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 245 AUSCGIE',
    explication: "Dans les SNC et SCS, la publicité est requise à peine de nullité de la société ou de l'acte, « sans que les associés et la société puissent se prévaloir, à l'égard des tiers, de cette cause de nullité » ; le juge a la faculté de ne pas prononcer la nullité si aucune fraude n'est constatée (art. 245).",
  },
  {
    id: 'ch10-q30', question: "Le liquidateur n'a pas publié sa nomination dans le mois ni convoqué les associés en fin de liquidation. Commet-il une infraction ?",
    options: [
      { id: 'a', texte: "Non, ce sont de simples formalités" },
      { id: 'b', texte: "Oui, s'il a agi sciemment, l'AUSCGIE incrimine ces omissions" },
      { id: 'c', texte: "Seulement en cas de liquidation judiciaire" },
      { id: 'd', texte: "Seulement s'il est associé" },
    ],
    reponseCorrecte: 'b', articleRef: 'Art. 902 AUSCGIE',
    explication: "Encourt une sanction pénale le liquidateur qui, sciemment, n'a pas publié dans le mois l'acte le nommant et déposé les décisions de dissolution, n'a pas convoqué les associés en fin de liquidation pour statuer sur les comptes définitifs et la clôture, ou n'a pas déposé ses comptes définitifs dans le cas de l'art. 219 (art. 902). Les peines relèvent du droit national (chapitre 7).",
  },
]
const SECTIONS: Chapitre['sections'] = [
  {
    numero: '10.1',
    titre: "Les causes de dissolution",
    navLabel: '10.1 Causes de dissolution',
    blocs: [
      { type: 'paragraphe', texte: "Toute société est appelée à disparaître un jour. La fin de la société se déroule en deux temps que l'on confond souvent : la **dissolution**, qui met fin à la vie active de la société et en fixe la cause, et la **liquidation**, qui consiste à réaliser l'actif, payer le passif et partager le solde entre les associés. Entre les deux, la société survit, mais seulement pour les besoins de sa liquidation. Ce chapitre étudie successivement les causes de dissolution, ses effets, le liquidateur, les opérations de liquidation, puis les nullités, qui constituent une cause particulière de disparition de la société ou de ses actes." },
      { type: 'filet', titre: "Article 200 AUSCGIE", texte: "« La société prend fin : 1°) par l'expiration du temps pour lequel elle a été constituée ; 2°) par la réalisation ou l'extinction de son objet ; 3°) par l'annulation du contrat de société ; 4°) par décision des associés aux conditions prévues pour modifier les statuts ; 5°) par la dissolution anticipée prononcée par la juridiction compétente, à la demande d'un associé pour justes motifs, notamment en cas d'inexécution de ses obligations par un associé ou de mésentente entre associés empêchant le fonctionnement normal de la société ; 6°) par l'effet d'un jugement ordonnant la liquidation des biens de la société ; 7°) pour toute autre cause prévue par les statuts. »" },
      { type: 'paragraphe', texte: "Les causes de l'art. 200 se classent en trois groupes. Les causes **de plein droit** jouent automatiquement : l'**expiration de la durée** statutaire, qui ne peut dépasser le terme fixé dans les statuts sauf prorogation décidée avant son échéance (chapitre 1), et la **réalisation ou l'extinction de l'objet**, par exemple l'achèvement du chantier pour lequel une société a été constituée ou le retrait définitif du permis minier qui constituait son unique objet. Les causes **volontaires** résultent d'une décision des associés prise aux conditions de modification des statuts, ou d'une clause statutaire (décès d'un associé dans une société de personnes, par exemple). Les causes **judiciaires** sont la dissolution pour justes motifs, l'annulation de la société et le jugement de liquidation des biens rendu dans le cadre d'une procédure collective." },
      { type: 'paragraphe', texte: "À ces causes générales s'ajoutent des **causes propres** à certaines formes ou situations, étudiées dans les chapitres précédents : le décès, la faillite ou l'incapacité d'un associé de SNC, sauf clause de continuation (art. 290) ; la réunion de tous les titres d'une société qui ne peut être unipersonnelle, si elle n'est pas régularisée dans l'année (art. 60) ; la réduction du capital en dessous du minimum légal sans régularisation (art. 66, 368 et 369) ; la perte de plus de la moitié du capital, qui oblige à consulter les associés sur la dissolution et, à défaut de reconstitution dans les deux ans, permet à tout intéressé de demander la dissolution judiciaire (art. 371 à 373 pour la SARL, 664 et 665 pour la SA) ; ou, pour le GIE, le décès ou la défaillance d'un membre (art. 883 et 884). Enfin, lors de l'entrée en vigueur de l'Acte uniforme révisé, les SA et SARL qui n'avaient pas porté leur capital au minimum légal dans le délai de deux ans de mise en harmonie devaient se dissoudre ou se transformer, faute de quoi elles étaient dissoutes de plein droit (art. 908 et 914)." },
      { type: 'carte', titre: "Les causes de dissolution en un tableau", tableau: { entetes: ['Nature', 'Cause', 'Textes'], lignes: [
        ["De plein droit", "Expiration de la durée ; réalisation ou extinction de l'objet", "Art. 200, 1° et 2°"],
        ["Volontaire", "Décision des associés aux conditions de modification des statuts ; cause statutaire", "Art. 200, 4° et 7°"],
        ["Judiciaire", "Justes motifs ; nullité ; liquidation des biens", "Art. 200, 3°, 5° et 6°"],
        ["Propre à la forme", "Décès ou faillite d'un associé de SNC ; réunion des titres ; capital sous le minimum ; perte de la moitié du capital non régularisée", "Art. 290, 60, 66, 371 à 373, 664, 665"],
      ] } },
      { type: 'paragraphe', texte: "Pour l'expert-comptable, la dissolution est un moment charnière. Dès qu'elle est décidée, la convention de continuité d'exploitation, qui fonde l'évaluation des actifs à leur coût historique, n'est plus applicable : les actifs doivent être appréciés à leur valeur de réalisation, et les passifs liés à l'arrêt de l'activité (indemnités de fin de contrat des salariés, pénalités de rupture de contrats, frais de liquidation) doivent être provisionnés. Il faut aussi arrêter une situation comptable à la date de la dissolution, qui servira de point de départ aux comptes de liquidation, et informer le client des conséquences fiscales et sociales de la décision. Enfin, il convient de vérifier que la décision a été prise par l'organe compétent, à la bonne majorité, et qu'elle a été régulièrement publiée : une dissolution irrégulière exposerait les associés et le liquidateur à des contestations. La dissolution n'est donc jamais une simple formalité ; elle ouvre une phase de la vie sociale qui exige autant de rigueur que l'exploitation elle-même." },
      { type: 'controle', question: QCM[0] },
      { type: 'controle', question: QCM[1] },
    ],
  },
  {
    numero: '10.2',
    titre: "La dissolution judiciaire pour justes motifs",
    navLabel: '10.2 Justes motifs',
    blocs: [
      { type: 'paragraphe', texte: "La dissolution pour justes motifs est la soupape de sécurité du droit des sociétés. Elle permet à un associé de sortir d'une société qui ne fonctionne plus, lorsque toutes les autres voies ont échoué. Le texte cite deux exemples : « l'inexécution de ses obligations par un associé », par exemple l'associé qui n'a jamais libéré son apport ou qui exerce une activité concurrente en violation des statuts, et la « mésentente entre associés empêchant le fonctionnement normal de la société » (art. 200, 5°). L'adverbe « notamment » montre que la liste n'est pas limitative." },
      { type: 'paragraphe', texte: "La **mésentente** est la cause la plus fréquemment invoquée. Pour justifier la dissolution, elle doit présenter une double caractéristique : être grave et durable, et surtout **paralyser le fonctionnement** de la société. Deux associés à parts égales qui ne peuvent plus adopter aucune décision, ni approuver les comptes, ni nommer un gérant, se trouvent dans cette situation. En revanche, un simple désaccord sur la stratégie, une hostilité personnelle qui n'empêche pas les assemblées de statuer, ou le mécontentement d'un minoritaire systématiquement mis en minorité ne suffisent pas : la loi de la majorité n'est pas une cause de dissolution. Le juge apprécie souverainement ces éléments au vu des circonstances de chaque espèce." },
      { type: 'paragraphe', texte: "La dissolution judiciaire est une **mesure ultime**, car elle détruit une entreprise qui peut être viable, avec ses emplois et ses contrats. Avant d'y recourir, l'associé et le juge disposent d'autres outils, étudiés aux chapitres 7 et 8 : l'**administration provisoire**, lorsque le fonctionnement normal est rendu impossible (art. 160-1) ; la désignation d'un **mandataire ad hoc** pour voter à la place d'un associé qui commet un abus de minorité ou d'égalité (art. 131) ; la **cession des titres** de l'un des associés à l'autre, éventuellement à dire d'expert (art. 59). Dans la pratique, la menace d'une dissolution judiciaire conduit souvent les associés à négocier le rachat des titres de celui qui veut partir. L'expert-comptable intervient alors pour évaluer ces titres." },
      { type: 'paragraphe', texte: "L'**annulation** du contrat de société (art. 200, 3°) et le **jugement de liquidation des biens** (art. 200, 6°) sont les deux autres causes judiciaires. La première sera étudiée en fin de chapitre. La seconde résulte d'une procédure collective ouverte parce que la société est en cessation des paiements et que sa situation est irrémédiablement compromise (chapitre 9) : la liquidation obéit alors aux règles de l'AUPCAP, conduite par un syndic sous le contrôle du juge-commissaire, et non aux règles de liquidation de l'AUSCGIE, qui ne s'appliquent pas dans ce cas (art. 203 al. 2)." },
      { type: 'paragraphe', texte: "La pratique congolaise connaît de nombreuses sociétés familiales où la mésentente naît d'une succession : au décès du fondateur, ses enfants deviennent associés, parfois avec la veuve, et les désaccords sur la gestion ou sur la distribution des bénéfices se multiplient. Avant d'en arriver à la dissolution, il est souvent possible d'organiser une sortie négociée : rachat des parts des héritiers qui ne souhaitent pas rester, par les autres ou par la société elle-même dans le cadre d'une réduction de capital non motivée par des pertes ; scission de la société pour attribuer à chaque branche familiale une partie des activités ; ou encore transformation de la gouvernance par un pacte d'associés organisant la répartition des fonctions. Le rôle de l'expert-comptable, dans ces situations, est d'objectiver les chiffres (valeur de l'entreprise, rémunérations, dividendes possibles) pour dépassionner le débat. La dissolution judiciaire, qui entraîne la vente de l'entreprise et souvent la perte d'une partie de sa valeur, doit rester le dernier recours." },
      { type: 'controle', question: QCM[2] },
    ],
  },
  {
    numero: '10.3',
    titre: "Les effets de la dissolution",
    navLabel: '10.3 Effets',
    blocs: [
      { type: 'filet', titre: "Article 201 al. 1 à 3 AUSCGIE", texte: "« La dissolution de la société n'a d'effet à l'égard des tiers qu'à compter de sa publication par avis inséré dans un journal habilité à recevoir les annonces légales dans l'État partie du siège social. La dissolution de la société pluripersonnelle entraîne de plein droit sa mise en liquidation. La personnalité morale de la société subsiste pour les besoins de la liquidation et jusqu'à la clôture de celle-ci. »" },
      { type: 'paragraphe', texte: "**La publicité.** La dissolution est publiée par un avis dans un journal d'annonces légales, par le dépôt au registre des actes ou procès-verbaux qui la décident ou la constatent, et par la modification de l'inscription au RCCM (art. 202). Elle n'est opposable aux tiers qu'à compter de cette publication (art. 201 al. 1). Tant que la dissolution n'est pas publiée, les tiers peuvent continuer à traiter avec la société comme si elle était en activité." },
      { type: 'paragraphe', texte: "**La liquidation de plein droit.** « La société est en liquidation dès l'instant de sa dissolution pour quelque cause que ce soit » (art. 204 al. 1). Les pouvoirs des dirigeants cessent au profit du liquidateur, et l'activité sociale est réduite aux opérations nécessaires à la liquidation : réalisation de l'actif, recouvrement des créances, paiement des dettes. Tous les actes et documents destinés aux tiers portent la mention « **société en liquidation** » et le nom du ou des liquidateurs (art. 204 al. 2), afin que les partenaires sachent qu'ils traitent avec une société en fin de vie." },
      { type: 'paragraphe', texte: "**La survie de la personnalité morale.** « La personnalité morale de la société subsiste pour les besoins de la liquidation et jusqu'à la publication de la clôture de celle-ci » (art. 205). Cette survie est indispensable : sans elle, les biens de la société deviendraient indivis entre les associés, et les créanciers sociaux seraient en concurrence avec les créanciers personnels des associés. Grâce à elle, la société conserve son patrimoine, qui reste le gage exclusif de ses créanciers ; elle peut agir en justice, vendre, encaisser, payer ; elle reste débitrice de ses impôts et cotisations. Mais cette personnalité est **finalisée** : elle ne vaut que pour les besoins de la liquidation, et ne permet pas de poursuivre l'exploitation sans autorisation (art. 231)." },
      { type: 'paragraphe', texte: "**Le cas de l'associé unique personne morale.** Lorsque tous les titres sont détenus par un seul associé, la dissolution entraîne la **transmission universelle du patrimoine** à cet associé, sans liquidation : c'est la « dissolution-confusion », très utilisée dans les groupes pour faire disparaître une filiale à 100 % en transférant son patrimoine à la société mère. Les créanciers peuvent former **opposition** dans les trente jours de la publication ; le juge rejette l'opposition ou ordonne le remboursement ou la constitution de garanties ; la transmission n'est réalisée qu'à l'issue du délai d'opposition ou après règlement de l'opposition (art. 201 al. 4). Ce mécanisme est exclu lorsque l'associé unique est une **personne physique** : la dissolution entraîne alors la liquidation de plein droit (art. 201 al. 5), pour éviter que l'entrepreneur ne mêle à nouveau le patrimoine de sa société au sien sans que les créanciers sociaux soient d'abord payés." },
      { type: 'paragraphe', texte: "La survie de la personnalité morale a des conséquences concrètes que l'on sous-estime souvent. La société en liquidation reste redevable des impôts et des cotisations sociales afférents à la période de liquidation ; elle doit continuer à tenir sa comptabilité ; ses contrats ne sont pas résiliés de plein droit par la dissolution, et le liquidateur doit les dénoncer ou les exécuter selon leurs termes ; ses salariés restent liés à elle jusqu'à la rupture de leurs contrats, qui obéit au droit du travail. La société peut aussi être poursuivie en justice et agir elle-même, par exemple pour recouvrer une créance ancienne. Tant que la clôture n'a pas été publiée, un créancier qui découvre une dette impayée peut encore s'adresser à la société en liquidation. C'est pourquoi une liquidation hâtive, clôturée sans que toutes les dettes aient été identifiées, expose le liquidateur à des actions en responsabilité et les associés à des actions en restitution." },
      { type: 'controle', question: QCM[3] },
      { type: 'controle', question: QCM[4] },
      { type: 'controle', question: QCM[5] },
      { type: 'controle', question: QCM[6] },
    ],
  },
  {
    numero: '10.4',
    titre: "Le liquidateur : nomination, statut et responsabilité",
    navLabel: '10.4 Liquidateur',
    blocs: [
      { type: 'paragraphe', texte: "Les règles générales de la liquidation (art. 203 à 222) s'appliquent à toute liquidation de société commerciale, qu'elle soit amiable, conformément aux statuts ou à l'accord des associés, ou ordonnée par le juge ; elles ne s'appliquent pas lorsque la liquidation intervient dans le cadre d'une procédure collective de l'AUPCAP (art. 203). Le personnage central en est le **liquidateur**." },
      { type: 'paragraphe', texte: "Lorsque la liquidation est décidée par les associés, le liquidateur est **nommé** à l'unanimité dans la SNC ; à l'unanimité des commandités et à la majorité en capital des commanditaires dans la SCS ; à la majorité en capital des associés dans la SARL ; aux conditions de l'AGE dans les sociétés par actions (art. 206). Il peut être un associé ou un tiers, personne physique ou **personne morale** (art. 207). À défaut de nomination par les associés, il est désigné par décision de justice à la demande de tout intéressé (art. 208). S'ils sont plusieurs, les liquidateurs peuvent agir séparément, sauf disposition contraire, mais présentent un rapport commun (art. 209). Sa **rémunération** est fixée par la décision qui le nomme (art. 210). Il peut être **révoqué** et remplacé selon les formes de sa nomination, et tout associé peut demander sa révocation en justice pour motifs légitimes (art. 211)." },
      { type: 'paragraphe', texte: "L'acte de nomination est **publié** ; la nomination et la révocation ne sont opposables aux tiers qu'à compter de cette publication, et, une fois la publication régulièrement faite, ni la société ni les tiers ne peuvent se prévaloir d'une irrégularité de la nomination pour se soustraire à leurs engagements (art. 212). Cette dernière règle protège la sécurité des actes du liquidateur : un acheteur qui a acquis un bien de la société auprès d'un liquidateur régulièrement publié ne peut voir son acquisition remise en cause au motif que la nomination aurait été irrégulière." },
      { type: 'paragraphe', texte: "La loi prévient les **conflits d'intérêts** du liquidateur et des anciens dirigeants. La cession de tout ou partie de l'actif au **liquidateur**, à ses employés ou à leurs conjoints, ascendants ou descendants est **interdite** (art. 214). La cession à une personne ayant été associé en nom, commandité, gérant, administrateur, directeur général ou autre dirigeant, ou commissaire aux comptes de la société, n'est possible qu'avec le consentement unanime des associés ou, à défaut, l'autorisation du juge, liquidateur et commissaire aux comptes entendus (art. 213). La **cession globale** de l'actif ou son apport à une autre société, notamment par fusion, obéit à des majorités renforcées : unanimité dans la SNC, conditions de modification des statuts dans la SARL, conditions de l'AGE dans les sociétés par actions (art. 215). Les délibérations et opérations contraires sont **nulles** (art. 215-1), et le liquidateur qui cède de mauvaise foi l'actif à un ancien dirigeant sans l'accord unanime des associés ou l'autorisation du juge commet une infraction (art. 904)." },
      { type: 'paragraphe', texte: "Le liquidateur est **responsable**, envers la société comme envers les tiers, des conséquences dommageables des fautes commises dans l'exercice de ses fonctions ; l'action sociale ou individuelle se prescrit par trois ans à compter du fait dommageable ou de sa révélation, dix ans si le fait est qualifié de crime (art. 221). Payer un créancier chirographaire avant un créancier privilégié, vendre un actif à vil prix, ou répartir un boni entre les associés alors que des dettes connues restent impayées sont des fautes classiques. Dans la pratique congolaise, la fonction de liquidateur est souvent confiée à un expert-comptable, dont la compétence en matière de comptes et d'évaluation est précieuse, mais qui doit aussi maîtriser les règles de droit et de procédure étudiées ici." },
      { type: 'paragraphe', texte: "Le choix du liquidateur mérite réflexion. Nommer le dernier dirigeant présente des avantages : il connaît l'entreprise, ses clients, ses dettes et ses dossiers en cours, et la transition est rapide. Mais il présente aussi un risque : le dirigeant est parfois celui dont la gestion est en cause, et il peut être tenté de dissimuler des irrégularités ou de favoriser certains créanciers ou certains associés. Nommer un tiers indépendant, souvent un expert-comptable ou un avocat, apporte une garantie de neutralité et une compétence technique, mais suppose un coût et un temps d'appropriation du dossier. Dans les sociétés où les associés sont divisés, ou lorsque des créanciers importants restent impayés, la nomination d'un liquidateur indépendant, éventuellement par le juge dans le cadre du régime encadré (art. 223 et 226), est souvent la meilleure solution. Dans tous les cas, l'acte de nomination doit préciser la rémunération du liquidateur (art. 210) et, le cas échéant, les limites internes de ses pouvoirs, qui restent inopposables aux tiers (art. 230)." },
      { type: 'controle', question: QCM[7] },
      { type: 'controle', question: QCM[8] },
      { type: 'controle', question: QCM[9] },
      { type: 'controle', question: QCM[10] },
    ],
  },
  {
    numero: '10.5',
    titre: "Le régime particulier de la liquidation encadrée",
    navLabel: '10.5 Liquidation encadrée',
    blocs: [
      { type: 'paragraphe', texte: "Les art. 224 à 241 organisent un **régime particulier** de liquidation, plus encadré. Il s'applique dans deux hypothèses (art. 223) : en cas de liquidation amiable, lorsque les statuts ou une convention entre associés ne règlent pas la liquidation, ou lorsqu'une convention prévoit expressément son application ; ou sur **décision de justice** rendue à bref délai à la demande de la majorité des associés d'une SNC, d'associés représentant au moins le dixième du capital dans les autres sociétés, de créanciers sociaux ou du représentant de la masse des obligataires, justifiant d'un intérêt légitime. Dans ce second cas, les clauses statutaires ou conventionnelles contraires sont réputées non écrites. Le régime protège ainsi les minoritaires et les créanciers qui craignent une liquidation opaque conduite par la majorité." },
      { type: 'paragraphe', texte: "Lorsque le juge ordonne la liquidation, les pouvoirs du conseil d'administration ou des dirigeants **prennent fin** à la date de sa décision (art. 224), qui désigne un ou plusieurs liquidateurs (art. 226). La dissolution ne met pas fin aux fonctions du **commissaire aux comptes**, qui continue d'exercer sa mission pendant la liquidation (art. 225). Le mandat du liquidateur ne peut excéder **trois ans**, renouvelables par décision de justice sur demande motivée (art. 227). Dans les **six mois** de sa nomination, prorogeables à douze mois par le juge, le liquidateur convoque l'assemblée des associés et lui fait rapport sur l'actif et le passif, la poursuite des opérations et le délai nécessaire pour les achever ; l'assemblée statue aux conditions de modification des statuts ; à défaut de convocation, un mandataire ad hoc peut être désigné (art. 228). Si l'assemblée ne peut être réunie ou ne décide rien, le liquidateur demande au juge les autorisations nécessaires (art. 229)." },
      { type: 'paragraphe', texte: "Pendant la liquidation, le liquidateur tient une **comptabilité** et rend des comptes. Dans les trois mois de la clôture de chaque exercice, il établit les états financiers au vu d'un inventaire et un rapport écrit sur les opérations de l'exercice (art. 232) ; il convoque, sauf dispense judiciaire, l'assemblée au moins une fois par an, dans les six mois de la clôture, pour statuer sur ces comptes, donner les autorisations nécessaires et renouveler le mandat du commissaire aux comptes ; à défaut, son rapport est déposé au RCCM (art. 233). Les associés conservent leur **droit de communication** des documents sociaux (art. 234). Les décisions sont prises à l'unanimité dans la SNC, à la majorité en capital dans la SARL, aux conditions de l'AGE dans les sociétés par actions, le juge statuant si la majorité ne peut être réunie ; les associés liquidateurs prennent part au vote (art. 235). En cas de continuation de l'exploitation, les mêmes obligations d'information s'appliquent (art. 236)." },
      { type: 'carte', titre: "Liquidation amiable et liquidation encadrée", tableau: { entetes: ['Point', 'Règles générales (art. 203 à 222)', 'Régime particulier (art. 223 à 241)'], lignes: [
        ["Application", "Toute liquidation hors procédure collective", "À défaut de clauses, par convention, ou sur décision de justice"],
        ["Nomination du liquidateur", "Par les associés (art. 206) ou le juge (art. 208)", "Par le juge lorsqu'il ordonne la liquidation (art. 226)"],
        ["Durée du mandat", "Liée au délai de clôture de trois ans (art. 216)", "Trois ans au plus, renouvelables par le juge (art. 227)"],
        ["Information des associés", "Assemblée de clôture (art. 217)", "Rapport dans les six mois, comptes annuels, assemblée annuelle (art. 228, 232, 233)"],
        ["Pouvoirs", "Selon l'acte de nomination", "Les plus étendus pour réaliser l'actif ; continuation seulement avec autorisation judiciaire (art. 230, 231)"],
      ] } },
      { type: 'paragraphe', texte: "La possibilité, pour des associés minoritaires ou pour des créanciers, de demander au juge une liquidation selon le régime encadré est une protection importante. Imaginons une SA dont l'actionnaire majoritaire, également dirigeant, a fait voter la dissolution et s'est fait nommer liquidateur. Les minoritaires craignent qu'il ne vende les actifs à des sociétés qu'il contrôle, à des prix sous-évalués, puis ne s'attribue l'essentiel du boni par des manœuvres comptables. En représentant au moins le dixième du capital et en justifiant d'un intérêt légitime, ils peuvent demander au juge, statuant à bref délai, d'ordonner que la liquidation suive le régime des art. 224 à 241 (art. 223). Le juge désigne alors un liquidateur (art. 226), qui doit faire rapport dans les six mois (art. 228), établir des comptes annuels et réunir les associés chaque année (art. 232 et 233). Les clauses statutaires contraires sont réputées non écrites. Le commissaire aux comptes reste en fonctions et continue de contrôler les comptes pendant la liquidation (art. 225)." },
      { type: 'controle', question: QCM[15] },
      { type: 'controle', question: QCM[16] },
      { type: 'controle', question: QCM[17] },
    ],
  },
  {
    numero: '10.6',
    titre: "Les opérations de liquidation : réaliser, payer, partager",
    navLabel: '10.6 Opérations',
    blocs: [
      { type: 'filet', titre: "Articles 230 et 231 AUSCGIE", texte: "« Le liquidateur représente la société qu'il engage pour tous les actes de la liquidation. Il est investi des pouvoirs les plus étendus pour réaliser l'actif, même à l'amiable. Les restrictions à ces pouvoirs, résultant des statuts ou de l'acte de nomination, ne sont pas opposables aux tiers. » — « Le liquidateur est habilité à payer les créanciers et à répartir entre les associés le solde disponible. Il ne peut continuer les affaires en cours ou en engager de nouvelles, pour les besoins de la liquidation, que s'il y a été autorisé par décision de justice. »" },
      { type: 'paragraphe', texte: "La liquidation comporte trois grandes étapes. **Réaliser l'actif** : vendre les biens (immeubles, véhicules, stocks, fonds de commerce), recouvrer les créances clients, récupérer les dépôts et cautionnements, céder les participations. Le liquidateur dispose des pouvoirs les plus étendus pour y procéder, même à l'amiable, c'est-à-dire sans enchères publiques ; les restrictions statutaires ne sont pas opposables aux tiers (art. 230). Il ne peut en revanche poursuivre l'exploitation qu'avec une autorisation judiciaire (art. 231), par exemple pour achever un contrat en cours dont l'abandon causerait des pénalités, ou pour vendre l'entreprise en activité à un meilleur prix." },
      { type: 'paragraphe', texte: "**Payer le passif** : salaires et indemnités de fin de contrat des travailleurs, impôts et cotisations sociales, dettes bancaires, fournisseurs. Le liquidateur doit respecter les **privilèges** et sûretés des créanciers ; il est responsable des fautes commises dans ce paiement (art. 221). Lorsque l'actif ne suffit pas à payer tout le passif, la liquidation amiable n'est plus possible : la société est en cessation des paiements, et le liquidateur doit la déclarer pour qu'une procédure collective soit ouverte (chapitre 9) ; il ne peut pas choisir de payer certains créanciers au détriment des autres. **Partager le solde** : après paiement des dettes, les associés sont d'abord remboursés du nominal de leurs titres, puis le **boni de liquidation**, c'est-à-dire les capitaux propres subsistant au-delà du capital, est partagé « dans les mêmes proportions que leur participation au capital social », sauf clause contraire des statuts (art. 237)." },
      { type: 'paragraphe', texte: "Les **répartitions** sont encadrées. Sous réserve des droits des créanciers, le liquidateur décide s'il y a lieu de distribuer des fonds en cours de liquidation ; après une mise en demeure restée vaine, tout intéressé peut demander au juge de statuer sur l'opportunité d'une répartition (art. 241). Toute décision de répartition est publiée et notifiée aux titulaires de titres nominatifs (art. 238). Les sommes affectées aux répartitions sont déposées dans les **quinze jours** sur un compte bancaire au nom de la société en liquidation, dans l'État du siège (art. 239). Celles qui n'ont pu être versées sont déposées, un an après la clôture, sur un **compte séquestre** auprès du Trésor public (art. 240). Le liquidateur qui ne respecte pas ces obligations de dépôt en liquidation judiciaire encourt une sanction pénale (art. 903)." },
      { type: 'carte', titre: "Exemple : la liquidation de la SARL BENI TRANSPORT", texte: "Capital : 50 000 000 FC (5 000 parts de 10 000 FC ; associé A 60 %, associé B 40 %). À la dissolution, l'actif est vendu pour 180 000 000 FC ; les frais de liquidation s'élèvent à 8 000 000 FC ; les dettes (salaires, impôts, banque, fournisseurs) à 92 000 000 FC.", liste: [
        "Solde après paiement des frais et des dettes : 180 000 000 − 8 000 000 − 92 000 000 = 80 000 000 FC.",
        "Remboursement du nominal : 50 000 000 FC (A : 30 000 000 ; B : 20 000 000).",
        "Boni de liquidation : 80 000 000 − 50 000 000 = 30 000 000 FC, partagé à proportion du capital (art. 237) : A 18 000 000 FC, B 12 000 000 FC.",
        "Chaque associé reçoit au total : A 48 000 000 FC, B 32 000 000 FC.",
      ], note: "Si l'actif net avait été inférieur au capital, les associés auraient reçu moins que leur apport : c'est le mali de liquidation, qu'ils supportent dans la limite de leurs apports dans une SARL." },
      { type: 'paragraphe', texte: "La liquidation a aussi des conséquences **fiscales** en RDC. En cas de dissolution, de liquidation de société ou de cessation d'affaires, la déclaration de l'impôt sur les sociétés est remise dans le mois et, en tout cas, avant que le dirigeant ne quitte le territoire (loi n° 004/2003 portant réforme des procédures fiscales, art. 16). Le liquidateur doit aviser l'administration fiscale de la dissolution ou de la liquidation ; à défaut, il est tenu au paiement des impôts dus **solidairement** avec la société (art. 80 de la même loi). Le liquidateur prudent obtient donc, avant toute répartition aux associés, la situation fiscale de la société et règle ou provisionne les impôts dus. Les dettes sociales (CNSS) et le sort des contrats de travail doivent de même être traités selon le droit du travail et de la sécurité sociale." },
      { type: 'paragraphe', texte: "La comptabilité de la liquidation obéit à une logique particulière. À la date de la dissolution, l'expert-comptable arrête les comptes et évalue les actifs à leur valeur probable de réalisation, les passifs à leur montant exigible. Pendant la liquidation, les ventes d'actifs font apparaître des plus-values ou des moins-values de cession ; les frais de liquidation (honoraires du liquidateur, frais de publicité, indemnités de licenciement) sont constatés en charges. À la fin, les comptes définitifs font apparaître le solde disponible, qui est d'abord affecté au remboursement du capital, puis, s'il excède celui-ci, constitue le boni de liquidation, partagé selon l'art. 237. Si le solde est inférieur au capital, les associés subissent une perte, le mali de liquidation. Sur le plan fiscal, le boni distribué aux associés peut, pour la part qui excède le remboursement des apports, relever du régime des revenus distribués étudié au chapitre 2 ; il appartient à l'expert-comptable de vérifier le traitement applicable au moment de la répartition, selon la législation fiscale en vigueur." },
      { type: 'controle', question: QCM[18] },
      { type: 'controle', question: QCM[19] },
      { type: 'controle', question: QCM[20] },
      { type: 'controle', question: QCM[21] },
    ],
  },
  {
    numero: '10.7',
    titre: "La clôture de la liquidation et les prescriptions",
    navLabel: '10.7 Clôture',
    blocs: [
      { type: 'paragraphe', texte: "La liquidation ne doit pas s'éterniser. « La clôture de la liquidation doit intervenir dans un délai de trois (3) ans à compter de la dissolution de la société » ; à défaut, le ministère public ou tout intéressé peut saisir le juge du siège pour qu'il soit procédé à la liquidation ou à son achèvement (art. 216). En RDC comme ailleurs, de nombreuses sociétés dissoutes restent des années « en liquidation » sans que rien ne se passe, ce qui laisse les créanciers dans l'incertitude et maintient des inscriptions obsolètes au RCCM ; la règle des trois ans donne un moyen d'y mettre fin." },
      { type: 'paragraphe', texte: "En fin de liquidation, les associés sont convoqués pour statuer sur les **comptes définitifs**, sur le **quitus** de la gestion du liquidateur et la **décharge** de son mandat, et pour **constater la clôture** ; à défaut de convocation, tout associé peut obtenir du juge la désignation d'un mandataire ad hoc (art. 217). Si l'assemblée ne peut délibérer ou refuse d'approuver les comptes, le juge statue à sa place, à la demande du liquidateur ou de tout intéressé, les comptes étant alors déposés au RCCM où tout intéressé peut les consulter (art. 218). Les comptes définitifs sont déposés au RCCM avec la décision d'approbation ou le jugement (art. 219), puis le liquidateur demande la **radiation** de la société dans le mois de la publication de la clôture (art. 220). La radiation marque la disparition définitive de la personne morale." },
      { type: 'paragraphe', texte: "Deux **prescriptions** encadrent les actions après la liquidation. L'action, sociale ou individuelle, contre le **liquidateur** pour ses fautes se prescrit par trois ans à compter du fait dommageable ou de sa révélation, dix ans pour les crimes (art. 221). Toute action contre les **associés non liquidateurs**, leurs conjoints survivants, héritiers ou ayants cause, se prescrit par **cinq ans** à compter de la publication de la dissolution au RCCM (art. 222). Ce délai concerne notamment les créanciers qui n'auraient pas été payés et qui voudraient agir contre les associés tenus des dettes sociales, par exemple les associés de SNC, indéfiniment responsables, ou les associés qui ont reçu un boni de liquidation alors que des dettes restaient impayées." },
      { type: 'carte', titre: "Calendrier type d'une liquidation amiable", liste: [
        "Décision de dissolution anticipée et nomination du liquidateur (art. 200, 4° ; art. 206).",
        "Publication de la dissolution et de la nomination du liquidateur ; modification de l'inscription au RCCM (art. 201, 202, 212) ; déclaration fiscale dans le mois et avis à l'administration (loi n° 004/2003, art. 16 et 80).",
        "Réalisation de l'actif, paiement du passif, dépôt des sommes à répartir (art. 230, 231, 239).",
        "Assemblée de clôture : comptes définitifs, quitus, décharge, constatation de la clôture (art. 217), au plus tard trois ans après la dissolution (art. 216).",
        "Dépôt des comptes définitifs au RCCM (art. 219) puis demande de radiation dans le mois de la publication de la clôture (art. 220).",
        "Un an après la clôture : dépôt au Trésor des sommes non réclamées (art. 240).",
      ] },
      { type: 'paragraphe', texte: "Lorsque l'assemblée de clôture **refuse d'approuver** les comptes du liquidateur, ou ne peut délibérer faute de quorum, le juge statue à sa place sur ces comptes et, le cas échéant, sur la clôture de la liquidation, à la demande du liquidateur ou de tout intéressé ; les comptes sont alors déposés au RCCM, où chacun peut en prendre connaissance (art. 218). Cette règle évite qu'un associé récalcitrant bloque indéfiniment la clôture. Le quitus donné au liquidateur par l'assemblée n'empêche pas, en revanche, l'action en responsabilité pour les fautes qui auraient été dissimulées : la prescription triennale ne court, dans ce cas, qu'à compter de leur révélation (art. 221). Le liquidateur prudent conserve donc, pendant au moins ce délai, l'ensemble des pièces justificatives des opérations de liquidation : actes de vente, justificatifs des paiements, correspondances avec les créanciers et l'administration fiscale." },
      { type: 'controle', question: QCM[11] },
      { type: 'controle', question: QCM[12] },
      { type: 'controle', question: QCM[13] },
      { type: 'controle', question: QCM[14] },
    ],
  },
  {
    numero: '10.8',
    titre: "La nullité de la société : des causes limitées et une régularisation encouragée",
    navLabel: '10.8 Nullité de la société',
    blocs: [
      { type: 'filet', titre: "Article 242 AUSCGIE", texte: "« La nullité d'une société ne peut résulter que d'une disposition du présent Acte uniforme la prévoyant expressément ou, sous réserve des dispositions de l'alinéa suivant, des textes régissant la nullité des contrats. La nullité de la société emporte sa dissolution suivie de sa liquidation conformément aux dispositions du présent Acte uniforme. Dans les sociétés à responsabilité limitée et dans les sociétés par actions, la nullité de la société ne peut résulter ni d'un vice de consentement ni de l'incapacité d'un associé à moins que celle-ci n'atteigne tous les associés fondateurs. »" },
      { type: 'paragraphe', texte: "La nullité d'une société est une sanction grave : elle détruit une personne morale qui a pu fonctionner pendant des années, avec des salariés, des clients et des créanciers. L'Acte uniforme en limite donc strictement les causes (art. 242). Il faut soit une **disposition expresse** de l'Acte uniforme (par exemple l'absence d'intervention de tous les associés à l'acte constitutif de SARL, art. 315, ou l'objet illicite), soit l'application des **règles générales de nullité des contrats** (absence de consentement, incapacité, objet ou cause illicite). Mais, dans les **SARL et sociétés par actions**, ni le vice du consentement ni l'incapacité d'un associé n'entraînent la nullité, sauf s'ils atteignent **tous les fondateurs** : l'actionnaire qui a été trompé lors de la souscription peut obtenir réparation, mais ne peut faire tomber la société entière." },
      { type: 'paragraphe', texte: "Les **sociétés de personnes** connaissent une cause particulière : dans la SNC et la SCS, l'accomplissement des formalités de **publicité** est requis à peine de nullité de la société ou de l'acte, sans que les associés et la société puissent opposer cette nullité aux tiers ; le juge peut ne pas prononcer la nullité si aucune fraude n'est constatée (art. 245). La règle s'explique par la responsabilité indéfinie des associés : les tiers doivent savoir qui est associé et qui s'est retiré." },
      { type: 'paragraphe', texte: "L'Acte uniforme encourage la **régularisation**. L'action en nullité est **éteinte** lorsque la cause de nullité a cessé d'exister au jour où le juge statue en première instance, sauf si la nullité est fondée sur l'illicéité de l'objet social (art. 246). Le juge peut, même d'office, fixer un délai pour couvrir la nullité, et ne peut la prononcer moins de deux mois après l'assignation ; si une assemblée doit être convoquée pour régulariser, il accorde le délai nécessaire (art. 247). En cas de vice du consentement ou d'incapacité d'un associé, tout intéressé peut mettre l'associé en demeure de régulariser ou d'agir en nullité dans les **six mois**, à peine de forclusion (art. 248) ; la société ou un associé peut proposer au juge toute mesure supprimant l'intérêt à agir, notamment le **rachat des titres** de l'associé concerné, que le juge peut rendre obligatoire si elle a été adoptée aux conditions de modification des statuts (art. 249). Pour une nullité fondée sur un défaut de **publicité**, tout intéressé peut mettre la société en demeure de régulariser dans les trente jours, puis obtenir la désignation d'un mandataire chargé d'accomplir la formalité (art. 250). Ces règles s'appliquent à toutes les nullités (art. 250-1)." },
      { type: 'paragraphe', texte: "Les actions en nullité de la société se **prescrivent** par trois ans à compter de l'immatriculation ou de la publication de l'acte modificatif, sauf objet illicite (art. 251 al. 1). La **tierce opposition** contre une décision prononçant la nullité n'est recevable que pendant six mois à compter de sa publication (art. 252). Ces délais courts traduisent la même préoccupation : la stabilité des sociétés et la sécurité des tiers qui traitent avec elles." },
      { type: 'paragraphe', texte: "En pratique, les actions en nullité de la société sont rares, parce que l'Acte uniforme en limite les causes et favorise la régularisation. Les causes les plus fréquentes sont l'**irrégularité de la constitution** (défaut de signature d'un associé dans une SARL, absence de libération ou de dépôt des fonds, défaut de publicité d'une SNC) et l'**objet illicite**. Ce dernier mérite une attention particulière : une société constituée pour exercer une activité interdite, par exemple l'exploitation minière sans titre ou un commerce prohibé, est nulle, et la nullité ne peut être couverte par une régularisation (art. 246), ni l'action enfermée dans le délai de trois ans (art. 251). Les associés et dirigeants auxquels la nullité est imputable engagent en outre leur responsabilité (art. 256). Pour l'expert-comptable, la vérification de la régularité de la constitution et de la licéité de l'objet fait partie des diligences d'acceptation d'une nouvelle mission : on ne certifie pas les comptes d'une société dont l'existence même est contestable sans en tirer les conséquences dans son rapport." },
      { type: 'controle', question: QCM[22] },
      { type: 'controle', question: QCM[23] },
      { type: 'paragraphe', texte: "La nullité se distingue d'autres sanctions voisines qu'il ne faut pas confondre. La **clause réputée non écrite** disparaît seule, sans affecter le reste des statuts ni la société : c'est le sort des clauses léonines (art. 54) ou des clauses contraires aux dispositions impératives de l'Acte uniforme (art. 2). L'**inopposabilité** laisse l'acte valable entre les parties, mais empêche de s'en prévaloir envers les tiers : c'est le sort des limitations statutaires des pouvoirs des dirigeants (art. 121) ou d'une fusion à l'égard du créancier dont l'opposition a été accueillie sans que la société le rembourse ou lui donne des garanties (art. 679). La **dissolution de plein droit** frappe la société sans intervention du juge, par exemple à l'arrivée du terme (art. 200). La nullité, enfin, suppose une décision de justice, s'accompagne d'un régime de régularisation et produit ses effets sans rétroactivité. Savoir qualifier la sanction applicable est une compétence essentielle pour conseiller une société ou un associé." },
      { type: 'controle', question: QCM[24] },
      { type: 'controle', question: QCM[28] },
    ],
  },
  {
    numero: '10.9',
    titre: "La nullité des actes et délibérations et les effets des nullités",
    navLabel: '10.9 Nullité des actes',
    blocs: [
      { type: 'paragraphe', texte: "Les **actes, décisions et délibérations** de la société peuvent aussi être annulés, et c'est de loin le contentieux le plus fréquent. L'Acte uniforme distingue deux catégories. La nullité des actes **modifiant les statuts** ne peut résulter que d'une disposition expresse de l'Acte uniforme, des textes régissant la nullité des contrats en général, ou de la violation d'une clause statutaire jugée essentielle par le juge (art. 243). La nullité des actes **ne modifiant pas les statuts** peut en outre résulter de la violation d'une disposition **impérative** de l'Acte uniforme ou des textes régissant les contrats (art. 244). On a rencontré tout au long de ce cours des nullités expresses : délibérations prises sans le rapport du commissaire aux comptes, violation des règles de quorum et de majorité, abus de majorité, défaut de feuille de présence certifiée, conventions interdites, cessions de titres contraires aux clauses d'agrément." },
      { type: 'paragraphe', texte: "Les actions en nullité des actes, décisions ou délibérations se prescrivent par **trois ans** à compter du jour où la nullité est encourue, sauf objet illicite (art. 251 al. 2) ; l'action en nullité d'une **fusion ou d'une scission** se prescrit par **six mois** à compter de la dernière inscription au RCCM rendue nécessaire par l'opération (art. 251 al. 3). La décision qui annule une fusion ou une scission est publiée dans le mois où elle devient définitive ; elle est sans effet sur les obligations nées entre la prise d'effet de l'opération et la publication de l'annulation, les sociétés participantes en répondant solidairement (art. 254)." },
      { type: 'filet', titre: "Article 253 AUSCGIE", texte: "« Lorsque la nullité de la société est prononcée, elle met fin, sans rétroactivité, à l'exécution du contrat. Il est procédé à sa dissolution et, pour ce qui concerne les sociétés pluripersonnelles, à leur liquidation. »" },
      { type: 'paragraphe', texte: "Les **effets** de la nullité de la société sont aménagés pour protéger les tiers. La nullité opère **sans rétroactivité** : on ne défait pas les contrats conclus, les salaires versés, les impôts payés ; la société a existé en fait, et l'on procède à sa dissolution et à sa liquidation comme pour une dissolution ordinaire (art. 253). Surtout, « ni la société, ni les associés ne peuvent se prévaloir d'une nullité à l'égard des tiers de bonne foi », sauf pour la nullité fondée sur un vice du consentement ou l'incapacité, que l'incapable, son représentant légal ou la personne dont le consentement a été vicié peuvent opposer même aux tiers de bonne foi (art. 255). Les associés et les dirigeants auxquels la nullité est imputable peuvent être déclarés **solidairement responsables** du dommage causé aux tiers par l'annulation ; l'action se prescrit par trois ans à compter du jour où la décision d'annulation est passée en force de chose jugée, et la disparition de la cause de nullité n'empêche pas d'agir en réparation du préjudice causé par le vice, dans les trois ans de la régularisation (art. 256)." },
      { type: 'carte', titre: "Les délais à retenir en matière de nullité", tableau: { entetes: ['Action', 'Délai', 'Point de départ', 'Texte'], lignes: [
        ["Nullité de la société", "3 ans", "Immatriculation ou publication de l'acte modificatif", "Art. 251"],
        ["Nullité d'un acte ou d'une délibération", "3 ans", "Jour où la nullité est encourue", "Art. 251"],
        ["Nullité d'une fusion ou d'une scission", "6 mois", "Dernière inscription au RCCM", "Art. 251"],
        ["Mise en demeure de l'associé incapable ou au consentement vicié", "6 mois", "Mise en demeure", "Art. 248"],
        ["Tierce opposition au jugement de nullité", "6 mois", "Publication du jugement", "Art. 252"],
        ["Responsabilité des auteurs de la nullité", "3 ans", "Force de chose jugée de la décision", "Art. 256"],
        ["Objet social illicite", "Pas d'extinction par régularisation ni de prescription triennale", "—", "Art. 246, 251"],
      ] } },
      { type: 'paragraphe', texte: "Les nullités d'**actes et de délibérations** sont, elles, fréquentes dans le contentieux des sociétés, parce qu'elles sont l'arme des associés minoritaires. Un associé qui conteste une décision de l'assemblée invoquera la violation d'une règle de convocation, de quorum, de majorité ou d'information, l'absence d'un rapport obligatoire du commissaire aux comptes, ou l'abus de majorité. La régularisation reste possible : l'action est éteinte si la cause de nullité a disparu au jour où le juge statue en première instance (art. 246 et 250-1), par exemple lorsqu'une nouvelle assemblée, régulièrement convoquée, confirme la décision contestée. Pour la société et ses dirigeants, la prévention passe par un formalisme rigoureux : convocations dans les délais, documents mis à disposition, feuille de présence certifiée, procès-verbaux complets et signés. Pour l'expert-comptable, qui prépare souvent ces documents, la connaissance des causes de nullité est une compétence professionnelle à part entière." },
      { type: 'controle', question: QCM[25] },
      { type: 'controle', question: QCM[26] },
      { type: 'paragraphe', texte: "Un exemple montre l'articulation de ces règles. Une SA a approuvé en AGE une augmentation de capital réservée à un investisseur, sans que le rapport du commissaire aux comptes sur la suppression du droit préférentiel de souscription ait été établi. La délibération est nulle, puisque l'Acte uniforme prévoit expressément cette sanction (art. 591). Un actionnaire minoritaire peut agir dans les trois ans du jour où la nullité est encourue (art. 251). Mais la société peut régulariser : si, avant que le juge statue en première instance, une nouvelle AGE régulièrement convoquée ratifie l'augmentation au vu du rapport du commissaire, l'action est éteinte (art. 246 et 250-1). Si la nullité est néanmoins prononcée, elle n'est pas opposable aux tiers de bonne foi (art. 255), par exemple aux créanciers qui ont traité avec la société sur la foi de son capital augmenté ; et les dirigeants auxquels la nullité est imputable peuvent être condamnés à réparer le préjudice causé (art. 256)." },
      { type: 'controle', question: QCM[27] },
    ],
  },
  {
    numero: '10.10',
    titre: "Les infractions liées à la dissolution et à la liquidation",
    navLabel: '10.10 Infractions',
    blocs: [
      { type: 'paragraphe', texte: "L'Acte uniforme assortit plusieurs obligations de la fin de vie sociale de **sanctions pénales**, dont il définit les éléments constitutifs, les peines relevant du droit national (sur la situation particulière de la RDC, voir le chapitre 7). Pour les **dirigeants**, deux comportements sont incriminés lorsque les capitaux propres deviennent inférieurs à la moitié du capital du fait des pertes : ne pas avoir fait convoquer, dans les quatre mois de l'approbation des comptes ayant fait apparaître ces pertes, l'assemblée appelée à décider s'il y a lieu à dissolution anticipée ; et ne pas avoir déposé au RCCM et publié la dissolution (art. 901)." },
      { type: 'paragraphe', texte: "Pour le **liquidateur**, l'Acte uniforme distingue trois séries d'infractions. En toute liquidation, il est punissable s'il n'a pas, sciemment, publié l'acte le nommant et déposé les décisions de dissolution dans le mois de sa nomination, convoqué les associés en fin de liquidation pour statuer sur les comptes définitifs, le quitus et la clôture, ou déposé ses comptes définitifs au RCCM dans le cas où l'assemblée n'a pu statuer (art. 902). En liquidation ordonnée par le juge, il est en outre punissable s'il n'a pas présenté son rapport dans les six mois, établi les états financiers dans les trois mois de la clôture de chaque exercice, permis aux associés d'exercer leur droit de communication, convoqué les associés au moins une fois par an en cas de continuation, déposé les sommes à répartir dans les quinze jours, ou consigné au Trésor les sommes non réclamées dans l'année de la clôture (art. 903). Enfin, il commet une infraction s'il fait, de mauvaise foi, des biens ou du crédit de la société un usage contraire à l'intérêt de celle-ci, ou s'il cède l'actif à un ancien associé en nom, commandité, gérant, administrateur ou commissaire aux comptes sans l'accord unanime des associés ou l'autorisation du juge (art. 904)." },
      { type: 'paragraphe', texte: "Ces incriminations dessinent, en creux, le **code de conduite** du liquidateur : transparence (publicité, information des associés, dépôt des comptes), rigueur financière (dépôt des fonds sur un compte au nom de la société, consignation des sommes non réclamées), loyauté (interdiction de s'enrichir aux dépens de la société ou de favoriser les anciens dirigeants). L'expert-comptable désigné liquidateur doit en outre respecter ses obligations déontologiques professionnelles. Plus largement, la fin de la société, souvent négligée, mérite la même rigueur que sa constitution : une liquidation bien conduite protège les créanciers, qui sont payés, les associés, qui récupèrent ce qui leur revient, et les dirigeants, qui évitent les actions en responsabilité et les poursuites." },
      { type: 'carte', titre: "Synthèse du chapitre : de la dissolution à la radiation", liste: [
        "Une cause de dissolution survient : légale, volontaire, judiciaire ou statutaire (art. 200).",
        "La dissolution est publiée et devient opposable aux tiers ; la société entre en liquidation, sauf transmission universelle à un associé unique personne morale (art. 201, 202, 204).",
        "Un liquidateur est nommé et publié ; les conflits d'intérêts sont interdits ou encadrés (art. 206 à 215-1).",
        "L'actif est réalisé, le passif payé, le boni partagé, les obligations fiscales respectées (art. 230 à 241 ; loi n° 004/2003, art. 16 et 80).",
        "La clôture intervient dans les trois ans ; comptes définitifs, quitus, dépôt et radiation (art. 216 à 220).",
        "Les actions contre le liquidateur se prescrivent par trois ans, contre les associés par cinq ans (art. 221, 222).",
      ] },
      { type: 'paragraphe', texte: "Ce chapitre clôt l'étude du cycle de vie de la société, de sa constitution (chapitre 1) à sa disparition. Il montre que la fin de la société n'est pas un simple événement, mais un processus juridique, comptable et fiscal qui s'étend souvent sur plusieurs mois ou années, et qui engage la responsabilité de ceux qui le conduisent. Le dernier chapitre de ce module s'intéressera à deux situations particulières, la société en participation et la société de fait, qui se situent aux frontières de la notion de société : l'une parce qu'elle choisit de ne pas avoir de personnalité morale, l'autre parce qu'elle existe sans l'avoir voulu. On y retrouvera d'ailleurs la logique de l'art. 253 : lorsqu'une société est annulée, elle a néanmoins existé en fait, et ses rapports passés doivent être liquidés comme ceux d'une société." },
      { type: 'controle', question: QCM[29] },
    ],
  },
]

const CAS: Chapitre['casPratiques'] = [
  {
    id: 'cas1',
    titre: 'La mésentente des associés de la SARL KASAÏ MOTORS',
    contexte: "La SARL KASAÏ MOTORS, garage automobile à Kananga, est détenue à parts égales par deux associés, cogérants. Depuis deux ans, ils ne se parlent plus : les assemblées n'atteignent jamais la majorité, les comptes des deux derniers exercices n'ont pas été approuvés, les fournisseurs ne savent plus à qui s'adresser. L'un des associés demande la dissolution judiciaire ; l'autre soutient que la société reste rentable.",
    questions: [
      { num: 1, enonce: "Les conditions de la dissolution pour justes motifs sont-elles réunies ?", correction: "Vraisemblablement oui. La dissolution anticipée peut être prononcée à la demande d'un associé pour justes motifs, « notamment en cas […] de mésentente entre associés empêchant le fonctionnement normal de la société » (art. 200, 5°). Ici, la mésentente est durable et paralyse la société : aucune décision collective ne peut être adoptée, les comptes ne sont plus approuvés. La rentabilité de la société n'empêche pas la dissolution si son fonctionnement est impossible, mais le juge l'appréciera au regard des circonstances." },
      { num: 2, enonce: "Existe-t-il des solutions moins radicales ?", correction: "Oui. Le juge pourrait nommer un administrateur provisoire, puisque le fonctionnement normal est rendu impossible du fait des organes et des associés (art. 160-1), pour six mois au plus, prorogeables jusqu'à douze (art. 160-2). Les associés peuvent aussi négocier la cession des parts de l'un à l'autre, le prix étant fixé à dire d'expert à défaut d'accord (art. 59). L'associé qui bloque systématiquement des décisions nécessaires sans intérêt légitime pourrait même se voir opposer un abus d'égalité, le juge désignant un mandataire ad hoc pour voter à sa place (art. 131)." },
      { num: 3, enonce: "Si la dissolution est prononcée, que se passe-t-il ?", correction: "La société entre en liquidation (art. 201 et 204) ; sa personnalité subsiste pour les besoins de la liquidation (art. 205). À défaut d'accord des associés sur la nomination du liquidateur, à la majorité en capital (art. 206), impossible à obtenir ici, le liquidateur est désigné par le juge à la demande de tout intéressé (art. 208). Un associé détenant le dixième du capital peut demander que la liquidation suive le régime encadré des art. 224 à 241 (art. 223)." },
    ],
  },
  {
    id: 'cas2',
    titre: "La dissolution de la filiale LUALABA SERVICES",
    contexte: "La SA LUALABA SERVICES est une filiale à 100 % de la société minière KATANGA MINING SA. Le groupe décide de la dissoudre pour regrouper ses activités dans la société mère. LUALABA SERVICES doit 45 000 000 FCFA à un sous-traitant, qui craint de ne pas être payé.",
    questions: [
      { num: 1, enonce: "Faut-il liquider LUALABA SERVICES ?", correction: "Non. « La dissolution d'une société dans laquelle tous les titres sont détenus par un seul associé entraîne la transmission universelle du patrimoine de la société à cet associé, sans qu'il y ait lieu à liquidation » (art. 201 al. 4). L'associé unique étant une personne morale, le mécanisme s'applique (il serait exclu pour un associé unique personne physique, art. 201 al. 5). Tout l'actif et le passif de la filiale passent à KATANGA MINING." },
      { num: 2, enonce: "Comment le sous-traitant est-il protégé ?", correction: "Les créanciers peuvent former opposition à la dissolution devant la juridiction compétente dans les trente jours de sa publication ; le juge rejette l'opposition ou ordonne le remboursement des créances ou la constitution de garanties. La transmission du patrimoine et la disparition de la société n'interviennent qu'à l'issue du délai d'opposition, ou après rejet de l'opposition, remboursement ou constitution des garanties (art. 201 al. 4). En tout état de cause, KATANGA MINING deviendra débitrice du sous-traitant par l'effet de la transmission universelle." },
      { num: 3, enonce: "Quelles formalités accomplir ?", correction: "La dissolution est publiée par avis dans un journal d'annonces légales, par dépôt au registre de l'acte qui la décide et par modification de l'inscription au RCCM (art. 202) ; elle n'est opposable aux tiers qu'à compter de cette publication (art. 201 al. 1). Sur le plan fiscal, la déclaration de la société dissoute est remise dans le mois (loi n° 004/2003, art. 16). L'expert-comptable établit une situation comptable à la date de la transmission et vérifie le traitement de l'écart entre la valeur des titres chez la mère et l'actif net transmis." },
    ],
  },
  {
    id: 'cas3',
    titre: "Le liquidateur de la SNC FRÈRES KALALA",
    contexte: "Les trois associés de la SNC FRÈRES KALALA décident de dissoudre la société. Deux d'entre eux veulent nommer liquidateur M. KALALA aîné, gérant de la société ; le troisième préfère un expert-comptable indépendant. Une fois nommé, le liquidateur envisage de vendre le camion de la société à son propre fils, et le stock à l'ancien commissaire aux comptes de la société.",
    questions: [
      { num: 1, enonce: "Comment le liquidateur est-il nommé ?", correction: "Dans la SNC, le liquidateur est nommé « à l'unanimité des associés » (art. 206, 1°). Faute d'unanimité, il ne peut être nommé par les associés ; il sera désigné par décision de justice à la demande de tout intéressé (art. 208). Le liquidateur peut être un associé, comme M. KALALA aîné, ou un tiers, personne physique ou morale (art. 207)." },
      { num: 2, enonce: "La vente du camion au fils du liquidateur est-elle possible ?", correction: "Non. « La cession de tout ou partie de l'actif de la société en liquidation au liquidateur, à ses employés ou à leurs conjoints, ascendants ou descendants, est interdite » (art. 214) ; l'opération serait nulle (art. 215-1). Le fils est un descendant du liquidateur : l'interdiction est absolue." },
      { num: 3, enonce: "Et la vente du stock à l'ancien commissaire aux comptes ?", correction: "Elle n'est possible qu'avec le consentement unanime des associés ou, à défaut, l'autorisation de la juridiction compétente, le liquidateur et le commissaire aux comptes entendus (art. 213) ; sinon, elle est nulle (art. 215-1). Le liquidateur qui la réaliserait de mauvaise foi sans ces conditions commettrait une infraction (art. 904, 2°)." },
    ],
  },
  {
    id: 'cas4',
    titre: "Les comptes de la liquidation de la SA KINSHASA PLASTIQUES",
    contexte: "La SA KINSHASA PLASTIQUES, au capital de 100 000 000 FCFA (10 000 actions de 10 000 FCFA), est en liquidation amiable. Le liquidateur a vendu l'actif pour 420 000 000 FCFA ; les frais de liquidation s'élèvent à 20 000 000 FCFA et le passif à 250 000 000 FCFA, dont 30 000 000 FCFA d'impôts. Il envisage de répartir immédiatement le solde entre les actionnaires, sans avoir averti l'administration fiscale de la liquidation.",
    questions: [
      { num: 1, enonce: "Calculez le boni de liquidation et la somme revenant à chaque action.", correction: "Solde disponible après frais et passif : 420 000 000 − 20 000 000 − 250 000 000 = 150 000 000 FCFA. Remboursement du nominal : 100 000 000 FCFA, soit 10 000 FCFA par action. Boni de liquidation : 150 000 000 − 100 000 000 = 50 000 000 FCFA, partagé proportionnellement au capital sauf clause contraire (art. 237), soit 5 000 FCFA par action. Chaque action reçoit au total 15 000 FCFA." },
      { num: 2, enonce: "Le liquidateur peut-il répartir le solde sans avoir réglé la situation fiscale ?", correction: "C'est très imprudent. En cas de dissolution ou de liquidation, le liquidateur doit en aviser l'administration ; à défaut, il est tenu au paiement des impôts dus solidairement avec la société (loi n° 004/2003, art. 80). La déclaration doit être déposée dans le mois de la dissolution (art. 16). Le liquidateur doit d'abord payer ou provisionner les 30 000 000 FCFA d'impôts, et plus généralement tout le passif, sous peine d'engager sa responsabilité envers les créanciers (art. 221)." },
      { num: 3, enonce: "Comment la répartition doit-elle être réalisée ?", correction: "La décision de répartition est publiée et notifiée aux titulaires de titres nominatifs (art. 238). Les sommes sont déposées dans les quinze jours sur un compte ouvert au nom de la société en liquidation dans une banque de l'État du siège (art. 239). Celles qui n'auront pu être versées aux actionnaires seront déposées, un an après la clôture, sur un compte séquestre auprès du Trésor (art. 240). En fin de liquidation, les actionnaires, réunis aux conditions de l'AGE, statuent sur les comptes définitifs, le quitus et la clôture (art. 217 et 235), puis le liquidateur dépose les comptes et demande la radiation dans le mois (art. 219 et 220)." },
    ],
  },
  {
    id: 'cas5',
    titre: "La nullité de la SARL GOMA TECH",
    contexte: "La SARL GOMA TECH a été constituée en 2024 par trois associés. L'un d'eux, M. BAHATI, n'a pas signé les statuts : son frère a signé à sa place sans procuration. En 2026, M. BAHATI, fâché avec ses coassociés, assigne la société en nullité. Par ailleurs, un quatrième associé entré en 2025 prétend que son consentement a été vicié par des informations mensongères du gérant et demande lui aussi l'annulation de la société.",
    questions: [
      { num: 1, enonce: "L'absence de signature de M. BAHATI peut-elle entraîner la nullité ?", correction: "Oui, c'est une nullité expresse : les associés doivent tous intervenir à l'acte instituant la société, en personne ou par mandataire justifiant d'un pouvoir spécial, « à défaut, la société est nulle » (art. 315). L'action, intentée en 2026, n'est pas prescrite : le délai est de trois ans à compter de l'immatriculation (art. 251)." },
      { num: 2, enonce: "La nullité peut-elle être évitée ?", correction: "Oui. L'action en nullité est éteinte si la cause de nullité a cessé d'exister au jour où le juge statue en première instance (art. 246). M. BAHATI peut ratifier l'acte ; à défaut, la société peut proposer au juge une mesure supprimant son intérêt à agir, notamment le rachat de ses parts, adoptée aux conditions de modification des statuts, que le juge peut rendre obligatoire (art. 249). Le juge peut d'ailleurs, même d'office, accorder un délai pour régulariser et ne peut prononcer la nullité moins de deux mois après l'assignation (art. 247)." },
      { num: 3, enonce: "Le vice du consentement du quatrième associé permet-il d'annuler la société ?", correction: "Non. Dans les SARL et les sociétés par actions, la nullité ne peut résulter ni d'un vice du consentement ni de l'incapacité d'un associé, à moins qu'ils n'atteignent tous les associés fondateurs (art. 242 al. 3). Ce nouvel associé peut seulement obtenir réparation de son préjudice, par exemple par une action en responsabilité contre le gérant (art. 162). Si la société était annulée pour l'autre cause, la nullité produirait ses effets sans rétroactivité (art. 253), et les associés ne pourraient l'opposer aux tiers de bonne foi (art. 255)." },
    ],
  },
  {
    id: 'cas6',
    titre: "La liquidation sans fin de la SA BANDUNDU BOIS",
    contexte: "La SA BANDUNDU BOIS a été dissoute par son AGE en janvier 2022. Le liquidateur, nommé à la même date, n'a jamais publié sa nomination, n'a pas réuni les actionnaires depuis, et la liquidation n'est toujours pas close en septembre 2026. Un ancien fournisseur, créancier de 25 000 000 FCFA, n'a jamais été payé ; les associés se sont partagé une partie des fonds en 2023.",
    questions: [
      { num: 1, enonce: "Quelles règles de délai ont été méconnues ?", correction: "La clôture de la liquidation doit intervenir dans les trois ans de la dissolution, soit au plus tard en janvier 2025 ; à défaut, le ministère public ou tout intéressé, notamment le fournisseur, peut saisir le juge pour qu'il soit procédé à la liquidation ou à son achèvement (art. 216). L'acte de nomination du liquidateur devait être publié, et sa nomination n'est pas opposable aux tiers tant qu'elle ne l'est pas (art. 212)." },
      { num: 2, enonce: "Le liquidateur engage-t-il sa responsabilité ?", correction: "Oui. Il est responsable envers la société et les tiers des fautes commises dans ses fonctions (art. 221). Avoir laissé répartir des fonds entre les associés alors qu'un créancier connu restait impayé est une faute ; l'action du fournisseur se prescrit par trois ans à compter du fait dommageable ou de sa révélation. Sur le plan pénal, l'absence de publication de sa nomination dans le mois, si elle est faite sciemment, est incriminée (art. 902, 1°)." },
      { num: 3, enonce: "Le fournisseur peut-il agir contre les actionnaires ?", correction: "Les actionnaires d'une SA ne sont tenus des dettes sociales que dans la limite de leurs apports ; mais une répartition faite alors qu'un créancier connu restait impayé est irrégulière, et le fournisseur pourra rechercher, outre la responsabilité du liquidateur, la restitution des sommes indûment réparties, selon le droit commun. Toute action contre les associés non liquidateurs se prescrit par cinq ans à compter de la publication de la dissolution au RCCM (art. 222). Si la dissolution a été publiée en janvier 2022, le fournisseur doit agir avant janvier 2027." },
    ],
  },
]

export const chapitre: Chapitre = {
  ue: 'ue2',
  numero: 10,
  id: 'ue2-chapitre-10',
  titre: 'Dissolution, liquidation et nullités',
  sousTitre: "AUSCGIE révisé, art. 200 à 256 et 901 à 904 · loi n° 004/2003 portant réforme des procédures fiscales, art. 16 et 80",
  infoBulle: "Les causes de dissolution, la dissolution judiciaire pour justes motifs, les effets de la dissolution et la transmission universelle au profit de l'associé unique, le liquidateur, le régime encadré de liquidation, les opérations de liquidation et le partage du boni, les obligations fiscales en RDC, la clôture et les prescriptions, la nullité de la société et des actes, les infractions liées à la dissolution et à la liquidation.",
  loiRef: 'Art. 200-256, 901-904, 908-914 AUSCGIE · loi n° 004/2003, art. 16 et 80',
  moduleLabel: 'UE 2 · Droit des sociétés',
  retourRoute: '/ue2-droit-societes',
  coursId: 'ue2-droit-societes',
  objectifs: [
    "Identifier les causes de dissolution et leur nature (art. 200 et causes propres à chaque forme)",
    "Apprécier les conditions de la dissolution judiciaire pour justes motifs et les alternatives (art. 200, 5° ; art. 131, 160-1)",
    "Déterminer les effets de la dissolution, y compris la transmission universelle au profit d'un associé unique (art. 201 à 205)",
    "Organiser la nomination, les pouvoirs et la responsabilité du liquidateur et prévenir ses conflits d'intérêts (art. 206 à 215-1, 221)",
    "Appliquer le régime encadré de liquidation (art. 223 à 236)",
    "Conduire les opérations de liquidation, calculer le boni et respecter les obligations fiscales (art. 230 à 241 ; loi n° 004/2003, art. 16 et 80)",
    "Clôturer la liquidation et appliquer les prescriptions (art. 216 à 222)",
    "Qualifier et traiter une cause de nullité de la société ou d'un acte social, et en mesurer les effets (art. 242 à 256)",
  ],
  sections: SECTIONS,
  aRetenir: [
    "La société prend fin par l'expiration de sa durée, la réalisation ou l'extinction de son objet, l'annulation, la décision des associés aux conditions de modification des statuts, la dissolution judiciaire pour justes motifs, la liquidation des biens ou une cause statutaire (art. 200) ; s'y ajoutent des causes propres (réunion des titres, capital sous le minimum, perte de la moitié du capital non régularisée).",
    "La dissolution pour justes motifs suppose notamment l'inexécution de ses obligations par un associé ou une mésentente empêchant le fonctionnement normal de la société (art. 200, 5°) ; l'administration provisoire, le mandataire ad hoc et le rachat des titres sont des alternatives moins radicales.",
    "La dissolution est opposable aux tiers après publication (art. 201, 202) ; la société est en liquidation dès sa dissolution et porte la mention « société en liquidation » (art. 204) ; sa personnalité subsiste pour les besoins de la liquidation jusqu'à la publication de la clôture (art. 205).",
    "La dissolution d'une société à associé unique personne morale entraîne la transmission universelle de son patrimoine sans liquidation, après un délai d'opposition de trente jours ouvert aux créanciers ; si l'associé unique est une personne physique, la liquidation s'impose (art. 201).",
    "Le liquidateur, associé ou tiers, personne physique ou morale, est nommé selon des majorités propres à chaque forme ou par le juge (art. 206 à 208) ; sa nomination est publiée (art. 212) ; la cession d'actif au liquidateur et à ses proches est interdite, celle aux anciens dirigeants et commissaires aux comptes requiert l'unanimité ou le juge (art. 213, 214) ; il répond de ses fautes pendant trois ans (art. 221).",
    "Le régime encadré, applicable à défaut de clauses ou sur décision de justice à la demande notamment d'associés détenant le dixième du capital ou de créanciers, impose un rapport dans les six mois, des comptes annuels et une assemblée annuelle, un mandat de trois ans au plus, et une autorisation judiciaire pour poursuivre l'exploitation (art. 223 à 236).",
    "Le liquidateur réalise l'actif avec les pouvoirs les plus étendus, paie les créanciers dans le respect de leurs droits, puis rembourse le nominal et partage le boni à proportion du capital sauf clause contraire (art. 230, 231, 237) ; les fonds à répartir sont déposés dans les quinze jours, les sommes non réclamées consignées au Trésor après un an (art. 239, 240).",
    "En RDC, la déclaration fiscale est remise dans le mois de la dissolution ou de la liquidation et avant le départ du dirigeant, et le liquidateur qui n'avise pas l'administration est solidaire des impôts dus (loi n° 004/2003, art. 16 et 80).",
    "La clôture intervient dans les trois ans de la dissolution (art. 216) ; l'assemblée statue sur les comptes définitifs, le quitus et la clôture, le juge statuant à défaut (art. 217, 218) ; comptes déposés et radiation demandée dans le mois (art. 219, 220) ; l'action contre les associés non liquidateurs se prescrit par cinq ans (art. 222).",
    "La nullité de la société n'est admise que sur texte exprès ou selon le droit des contrats, jamais pour vice du consentement ou incapacité d'un seul associé de SARL ou de société par actions (art. 242) ; la régularisation éteint l'action sauf objet illicite (art. 246 à 250-1) ; prescription de trois ans, six mois pour une fusion (art. 251) ; la nullité opère sans rétroactivité et n'est pas opposable aux tiers de bonne foi, sauf vice du consentement ou incapacité (art. 253, 255) ; ses auteurs répondent du dommage (art. 256).",
  ],
  references: [
    { genre: 'texte', intitule: "Acte uniforme révisé relatif au droit des sociétés commerciales et du groupement d'intérêt économique (AUSCGIE)", precision: "30 janvier 2014 ; art. 59, 60, 66, 131, 160-1, 200 à 256, 290, 315, 368, 371 à 373, 664, 665, 883, 884, 901 à 904 et 908 à 914" },
    { genre: 'texte', intitule: "Loi n° 004/2003 du 13 mars 2003 portant réforme des procédures fiscales", precision: "art. 16 et 80, dans leur rédaction consolidée" },
    { genre: 'ouvrage', auteur: "Pougoué P.-G., Anoukaha F. et Nguebou Toukam J.", titre: "Le droit des sociétés commerciales et du groupement d'intérêt économique OHADA", editeur: "Presses universitaires d'Afrique", lieu: "Yaoundé", annee: "1998" },
    { genre: 'ouvrage', auteur: "Anoukaha F., Cissé A., Diouf N., Nguebou Toukam J., Pougoué P.-G. et Samb M.", titre: "OHADA. Sociétés commerciales et GIE", editeur: "Bruylant, coll. Droit uniforme africain", lieu: "Bruxelles", annee: "2002" },
    { genre: 'ouvrage', auteur: "Pougoué P.-G. (dir.)", titre: "Encyclopédie du droit OHADA", editeur: "Lamy", lieu: "Paris", annee: "2011" },
    { genre: 'ouvrage', auteur: "Diouf N., Masamba Makela R., Pougoué P.-G. et Sawadogo F. M. (coord.)", titre: "Code vert OHADA 2025. Traité et actes uniformes commentés et annotés", editeur: "Juriscope", lieu: "Poitiers", annee: "2025" },
  ],
  qcm: QCM,
  casPratiques: CAS,
  sources: "Sources : AUSCGIE révisé du 30 janvier 2014, art. 200 à 256, 901 à 904 et 908 à 914 · Loi n° 004/2003 du 13 mars 2003 portant réforme des procédures fiscales.",
}

export default chapitre
